//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class _IDSBatchIDQueryController;

@interface IDSBatchIDQueryController : NSObject
{
    _IDSBatchIDQueryController *_internal;
}

- (void).cxx_destruct;
- (void)invalidate;
- (void)setDestinations:(id)arg1;
- (void)dealloc;
- (id)initWithService:(id)arg1 delegate:(id)arg2 queue:(id)arg3;

@end

