//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Foundation/NSEqualityPredicateOperator.h>

@class NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface NSMemoryStoreEqualityPredicateOperator : NSEqualityPredicateOperator
{
    NSManagedObjectContext *_context;
}

- (_Bool)performPrimitiveOperationUsingObject:(id)arg1 andObject:(id)arg2;
- (void)setContext:(id)arg1;
- (void)dealloc;

@end

