//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ClockKit/CLKComplicationTemplate.h>

@class CLKTextProvider, NSData;

@interface CLKComplicationTemplateGraphicRectangularStandardBodyViewBridge : CLKComplicationTemplate
{
    NSData *_headerLabelData;
    CLKTextProvider *_headerTextProvider;
    CLKTextProvider *_body1TextProvider;
    CLKTextProvider *_body2TextProvider;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CLKTextProvider *body2TextProvider; // @synthesize body2TextProvider=_body2TextProvider;
@property(copy, nonatomic) CLKTextProvider *body1TextProvider; // @synthesize body1TextProvider=_body1TextProvider;
@property(copy, nonatomic) CLKTextProvider *headerTextProvider; // @synthesize headerTextProvider=_headerTextProvider;
@property(retain, nonatomic) NSData *headerLabelData; // @synthesize headerLabelData=_headerLabelData;
- (id)serializableCopyWithImageProviders:(id)arg1;
- (_Bool)needsSerializableCopy;
- (_Bool)usesSwiftUI;
- (id)viewDataKeyForSwiftUIViewKey:(id)arg1;
- (void)_enumerateSwiftUIViewDataKeysWithBlock:(CDUnknownBlockType)arg1;
- (void)_enumerateTextProviderKeysWithBlock:(CDUnknownBlockType)arg1;
- (long long)compatibleFamily;

@end

