//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WKGeolocationProviderIOS;
@protocol WKProcessGroupDelegate;

@interface WKProcessGroup : NSObject
{
    struct RefPtr<WebKit::WebProcessPool, WTF::DumbPtrTraits<WebKit::WebProcessPool>> _processPool;
    struct WeakObjCPtr<id<WKProcessGroupDelegate>> _delegate;
    struct RetainPtr<WKGeolocationProviderIOS> _geolocationProvider;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property id <WKProcessGroupDelegate> delegate;
- (id)initWithInjectedBundleURL:(id)arg1;
- (id)init;
@property(readonly) WKGeolocationProviderIOS *_geolocationProvider;
- (void)_setAllowsSpecificHTTPSCertificate:(id)arg1 forHost:(id)arg2;
@property(readonly) struct OpaqueWKContext *_contextRef;

@end

