//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableDictionary;

@interface MFMailMessageStoreSearchResult : NSObject
{
    NSDate *_continueOffset;
    NSMutableDictionary *_mailboxToRemoteIdDictionary;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *mailboxToRemoteIdDictionary; // @synthesize mailboxToRemoteIdDictionary=_mailboxToRemoteIdDictionary;
@property(retain, nonatomic) NSDate *continueOffset; // @synthesize continueOffset=_continueOffset;
- (void)enumerateMailboxesAndRemoteIDsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) unsigned long long count;
- (void)addRemoteID:(id)arg1 mailbox:(id)arg2;
- (id)init;

@end

