//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSRegularExpression, NSString;

@interface _ECSubjectFormatterContext : NSObject
{
    _Bool _prefixLastStrongDirectionalityIsLeftToRight;
    NSRegularExpression *_regex;
    NSString *_localizedPrefix;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool prefixLastStrongDirectionalityIsLeftToRight; // @synthesize prefixLastStrongDirectionalityIsLeftToRight=_prefixLastStrongDirectionalityIsLeftToRight;
@property(readonly, copy, nonatomic) NSString *localizedPrefix; // @synthesize localizedPrefix=_localizedPrefix;
@property(readonly, nonatomic) NSRegularExpression *regex; // @synthesize regex=_regex;
- (id)initWithRegex:(id)arg1 localizedPrefix:(id)arg2;

@end

