//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection;
@protocol OTAAgentServices;

@interface OSAServicesClient : NSObject
{
    NSXPCConnection *_connection;
    id <OTAAgentServices> _synchRemoteObjectProxy;
}

+ (id)sharedClient;
- (void).cxx_destruct;
- (unsigned int)uidForUser:(id)arg1;
- (id)awdKey;
- (id)crashreporterKey;
- (id)queryKey:(struct __CFString *)arg1;
- (_Bool)deletePreference:(id)arg1 forUser:(id)arg2 inDomain:(id)arg3;
- (_Bool)setPreference:(id)arg1 forUser:(id)arg2 inDomain:(id)arg3 toValue:(void *)arg4;
- (void)dealloc;
- (id)init;

@end

