//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/NSObject-Protocol.h>

@class NSArray, PSSpecifier;
@protocol PSSpecifierObserver;

@protocol PSSpecifierDataSource <NSObject>
+ (id)sharedInstance;
- (NSArray *)specifiersForSpecifier:(PSSpecifier *)arg1 observer:(id <PSSpecifierObserver>)arg2;
- (void)removeObserver:(id <PSSpecifierObserver>)arg1;
- (void)addObserver:(id <PSSpecifierObserver>)arg1;
@end

