//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface VOSOutputEvent : NSObject
{
    NSString *_rawValue;
    _Bool _supportsSoundEffect;
    _Bool _supportsHaptic;
}

+ (id)eventWithStringValue:(id)arg1;
+ (id)allOutputEvents;
+ (id)SensitiveContent;
+ (id)TouchIDFailed;
+ (id)TouchIDAuthenticated;
+ (id)ReachabilityDidEnd;
+ (id)ReachabilityDidBegin;
+ (id)DockDidDisappear;
+ (id)DockDidAppear;
+ (id)ItemMemorizationInProgress;
+ (id)ItemMemorizationFailed;
+ (id)BrailleDisplayDisconnected;
+ (id)BrailleDisplayConnected;
+ (id)FolderDidClose;
+ (id)FolderDidOpen;
+ (id)FolderWillOpen;
+ (id)CollaborationOccurred;
+ (id)ScreenDidChange;
+ (id)ItemMemorizationSucceeded;
+ (id)KeyboardDisappeared;
+ (id)KeyboardAppeared;
+ (id)InsertionPointDidMove;
+ (id)ScreenDidTurnOff;
+ (id)ItemDidLoad;
+ (id)ItemIsLoading;
+ (id)AutofillDidDismiss;
+ (id)AutofillDidAppear;
+ (id)PopoverDidAppear;
+ (id)AlertDidAppear;
+ (id)TVDidEndInteractionWithRotor;
+ (id)TVDidBeginInteractionWithRotor;
+ (id)DidDisableQuickNav;
+ (id)DidEnableQuickNav;
+ (id)DidWrapForwards;
+ (id)DidWrapBackwards;
+ (id)DidReorderItem;
+ (id)DidChangeVolume;
+ (id)DidEnterTouchContainer;
+ (id)DidSyncWithSystemFocus;
+ (id)DidLeaveTargetArea;
+ (id)DidEnterTargetArea;
+ (id)DidRecognizeMLContent;
+ (id)UnknownCommand;
+ (id)DidChangeTextSelectionDirection;
+ (id)DidEnterSecureText;
+ (id)NextRotorProgress;
+ (id)PreviousRotorProgress;
+ (id)DidSelectNextRotor;
+ (id)DidSelectPreviousRotor;
+ (id)DidBeginPassthrough;
+ (id)DidSelectAutofill;
+ (id)NoItemExists;
+ (id)BoundaryEncountered;
+ (id)DidScrollByPage;
+ (id)DidFocusOnElement;
+ (id)NoResultsFound;
+ (id)DidActivateElement;
- (void).cxx_destruct;
@property(nonatomic) _Bool supportsHaptic; // @synthesize supportsHaptic=_supportsHaptic;
@property(nonatomic) _Bool supportsSoundEffect; // @synthesize supportsSoundEffect=_supportsSoundEffect;
- (id)description;
@property(readonly, nonatomic) NSString *localizedName;
@property(readonly, nonatomic) NSString *rawValue;
- (id)_initOutputEventWithRawValue:(id)arg1 supportsSoundEffect:(_Bool)arg2 supportsHaptic:(_Bool)arg3;

@end

