//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__CollectionViewAccessibility_super.h"

@interface CollectionViewAccessibility : __CollectionViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)accessibilityElements;
- (id)accessibilityLabel;
- (id)_axNonHiddenViewForKey:(id)arg1;
- (_Bool)isAccessibilityElement;
- (void)_accessibilityLoadAccessibilityInformation;

@end

