//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CXCallObserverDelegate-Protocol.h"

@class CXCallObserver, NSString;
@protocol MRDPhoneCallObserverDelegate;

@interface MRDPhoneCallObserver : NSObject <CXCallObserverDelegate>
{
    CXCallObserver *_callObserver;
    unsigned long long _numberOfActiveCalls;
    id <MRDPhoneCallObserverDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MRDPhoneCallObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void)numberOfActivePhoneCalls:(CDUnknownBlockType)arg1;
- (void)_notifyDelegate:(id)arg1;
- (void)phoneCallDidChangeNotification:(id)arg1;
- (void)callObserver:(id)arg1 callChanged:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

