//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NUTileInfo : NSObject
{
    long long _index;
    CDStruct_d58201db _size;
    CDStruct_996ac03c _frameRect;
    CDStruct_996ac03c _contentRect;
}

+ (id)tileInfoWithIndex:(long long)arg1 size:(CDStruct_912cb5d2)arg2 frameRect:(CDStruct_996ac03c)arg3 contentRect:(CDStruct_996ac03c)arg4;
@property(readonly, nonatomic) CDStruct_996ac03c contentRect; // @synthesize contentRect=_contentRect;
@property(readonly, nonatomic) CDStruct_996ac03c frameRect; // @synthesize frameRect=_frameRect;
@property(readonly, nonatomic) CDStruct_912cb5d2 size; // @synthesize size=_size;
@property(readonly, nonatomic) long long index; // @synthesize index=_index;
- (id)debugDescription;
- (id)translatedAndClippedRegion:(id)arg1;

@end

