//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <AVConference/NSObject-Protocol.h>

@class NSNumber, NSString, VCTelephonyInterface;

@protocol VCTelephonyInterfaceDelegate <NSObject>

@optional
- (void)telephonyInterface:(VCTelephonyInterface *)arg1 anbrRecommendation:(unsigned int)arg2 forDirection:(long long)arg3;
- (void)telephonyInterface:(VCTelephonyInterface *)arg1 anbrActivationUpdate:(_Bool)arg2;
- (void)telephonyInterface:(VCTelephonyInterface *)arg1 vocoderInfoChangedToType:(NSString *)arg2 sampleRate:(NSNumber *)arg3;
@end

