//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__QLMarkupItemViewControllerAccessibility_super.h"

@interface QLMarkupItemViewControllerAccessibility : __QLMarkupItemViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_axPhotoDescriptionFromContext:(id)arg1;
- (void)previewDidAppear:(_Bool)arg1;
- (void)loadPreviewControllerWithContents:(id)arg1 context:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_accessibilityLoadAccessibilityInformation;

@end

