//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <UIKit/_UIHyperInteractor.h>

@interface _UIHyperInteractor (SBAdditions)
- (_Bool)sbpip_isInteractive;
- (void)sbpip_setInteractive:(_Bool)arg1;
- (_Bool)sbpip_isRubberBanding;
@end

