//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <CameraUI/NSObject-Protocol.h>

@class CAMControlDrawer;

@protocol CAMControlDrawerDelegate <NSObject>
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeValueForControlType:(long long)arg2;
- (void)controlDrawerDidCreateSemanticStyleControl:(CAMControlDrawer *)arg1;
- (void)controlDrawerDidCreateExposureSlider:(CAMControlDrawer *)arg1;
- (void)controlDrawerDidCreateLowLightSlider:(CAMControlDrawer *)arg1;
- (void)controlDrawerDidCreateIntensitySlider:(CAMControlDrawer *)arg1;
- (void)controlDrawerDidCreateApertureSlider:(CAMControlDrawer *)arg1;
- (void)controlDrawerDidCreateFilterScrubber:(CAMControlDrawer *)arg1;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didCreateControlForType:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeVideoStabilizationMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeSharedLibraryMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeProResVideoMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeRAWMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 wantsFilterScrubberVisible:(_Bool)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeTimerDuration:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeLivePhotoMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeAspectRatio:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeFlashMode:(long long)arg2;
- (void)controlDrawerFlashButtonUnavailable:(CAMControlDrawer *)arg1;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didChangeHDRMode:(long long)arg2;
- (void)controlDrawer:(CAMControlDrawer *)arg1 didSelectMenuItemForControlType:(long long)arg2;
@end

