//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface HMIDataReader : NSObject
{
    NSData *_data;
    unsigned long long _position;
}

- (void).cxx_destruct;
- (id)readData:(unsigned long long)arg1;
- (void)seek:(unsigned long long)arg1;
- (unsigned long long)readUInt64;
- (unsigned int)readUInt32;
- (unsigned long long)length;
- (unsigned long long)position;
- (id)initWithData:(id)arg1;

@end

