//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError;

@protocol DAActionConsumer
- (void)actionFailed:(long long)arg1 forTask:(id)arg2 error:(NSError *)arg3;
@end

