//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreDuet/_CDSpotlightEventIndexerDataSource.h>

@interface _CDSpotlightIntentIndexerDataSource : _CDSpotlightEventIndexerDataSource
{
}

- (id)bundleIDToSearchableItemsDictionaryFromEvents:(id)arg1;
- (id)initWithKnowledgeStore:(id)arg1;

@end

