//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CNDeduplication : NSObject
{
}

+ (id)os_log;
- (id)identifierSetFromContacts:(id)arg1;
- (void)addContactsForIds:(id)arg1 toGroup:(id)arg2 usingRequest:(id)arg3 store:(id)arg4;
- (id)contactsForGroup:(id)arg1 store:(id)arg2;
- (void)deduplicateKeeping:(id)arg1 deleting:(id)arg2 store:(id)arg3;
- (void)deduplicateContainer:(id)arg1 store:(id)arg2;
- (void)deduplicateAllContainers:(id)arg1;

@end

