//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Contacts/CoreTelephonyClientDelegate-Protocol.h>
#import <Contacts/TUCallProviderManagerDelegate-Protocol.h>

@class CNContactsEnvironment, CoreTelephonyClient, NSMapTable, NSString, TUCallProviderManager;
@protocol OS_dispatch_queue;

@interface CNGeminiManager : NSObject <CoreTelephonyClientDelegate, TUCallProviderManagerDelegate>
{
    CNContactsEnvironment *_environment;
    CoreTelephonyClient *_coreTelephonyClient;
    TUCallProviderManager *_callProviderManager;
    NSObject<OS_dispatch_queue> *_queue;
    NSMapTable *_delegateToQueue;
    unsigned long long _dataSourceExclusions;
}

+ (id)channelStringFromSenderIdentity:(id)arg1;
+ (id)descriptorForRequiredKeys;
+ (_Bool)deviceSupportsGemini;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long dataSourceExclusions; // @synthesize dataSourceExclusions=_dataSourceExclusions;
- (id)badgeLabelForSubscription:(id)arg1 error:(id *)arg2;
- (id)bestSubscriptionForHandle:(id)arg1 contactStore:(id)arg2 error:(id *)arg3;
- (id)bestSubscriptionForContact:(id)arg1 error:(id *)arg2;
- (void)danglingPlansDidUpdate:(id)arg1;
- (void)providersChangedForProviderManager:(id)arg1;
- (void)subscriptionInfoDidChange;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1 queue:(id)arg2;
- (_Bool)isReferencedByContactsForSenderLabelIdentifier:(id)arg1 store:(id)arg2;
- (_Bool)remapContactsHavingPreferredChannelIdentifier:(id)arg1 toPreferredChannelIdentifier:(id)arg2 contactStore:(id)arg3 error:(id *)arg4;
- (_Bool)remapChannelIdentifier:(id)arg1 toIdentifier:(id)arg2 error:(id *)arg3;
- (id)badgeLabelForSenderIdentity:(id)arg1 error:(id *)arg2;
- (id)bestSenderIdentityForFavoritesEntry:(id)arg1 error:(id *)arg2;
- (id)channelForFavoritesEntry:(id)arg1 error:(id *)arg2;
- (id)geminiResultForHandle:(id)arg1 contactStore:(id)arg2 error:(id *)arg3;
- (id)bestSenderIdentityForHandle:(id)arg1 contactStore:(id)arg2 error:(id *)arg3;
- (id)geminiResultForContact:(id)arg1 substituteDefaultForDangling:(_Bool)arg2 error:(id *)arg3;
- (id)geminiResultForContact:(id)arg1 error:(id *)arg2;
- (id)remoteBestSenderIdentityForHandle:(id)arg1 contactStore:(id)arg2 error:(id *)arg3;
- (id)remoteGeminiResultForContact:(id)arg1 substituteDefaultForDangling:(_Bool)arg2 error:(id *)arg3;
- (id)bestSenderIdentityForContact:(id)arg1 error:(id *)arg2;
- (id)channelForContact:(id)arg1 error:(id *)arg2;
- (id)fetchedSenderIdentitiesWithError:(id *)arg1;
- (id)initWithEnvironment:(id)arg1 coreTelephonyClient:(id)arg2 callProviderManager:(id)arg3;
- (id)initWithCallProviderManager:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

