//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ML3MusicLibrary;

@protocol ML3DatabaseValidationDelegate <NSObject>
- (_Bool)shouldValidateDatabaseForLibrary:(ML3MusicLibrary *)arg1;
@end

