//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitUI/PKExplanationViewController.h>

#import <PassKitUI/PKExplanationViewControllerDelegate-Protocol.h>
#import <PassKitUI/PKPaymentSetupPresentationProtocol-Protocol.h>

@class NSString;
@protocol PKPaymentSetupViewControllerDelegate;

@interface PKPasscodeUpgradeExplanationViewController : PKExplanationViewController <PKExplanationViewControllerDelegate, PKPaymentSetupPresentationProtocol>
{
    id <PKPaymentSetupViewControllerDelegate> _setupDelegate;
    long long _context;
    _Bool _isForWatch;
    _Bool _upgradeRequiredToAddNewPass;
    CDUnknownBlockType _continuationHandler;
    CDUnknownBlockType _dismissalHandler;
}

@property(nonatomic) _Bool upgradeRequiredToAddNewPass; // @synthesize upgradeRequiredToAddNewPass=_upgradeRequiredToAddNewPass;
@property(copy, nonatomic) CDUnknownBlockType dismissalHandler; // @synthesize dismissalHandler=_dismissalHandler;
@property(copy, nonatomic) CDUnknownBlockType continuationHandler; // @synthesize continuationHandler=_continuationHandler;
- (void).cxx_destruct;
- (void)_terminateSetupFlow;
- (id)paymentSetupMarker;
- (void)explanationViewDidSelectContinue:(id)arg1;
- (void)explanationViewDidSelectSetupLater:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithContext:(long long)arg1 setupDelegate:(id)arg2 isForWatch:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

