//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ChatKit/CKBalloonViewDelegate-Protocol.h>

@class CKBalloonView;

@protocol CKTitledImageBalloonViewDelegate <CKBalloonViewDelegate>
- (void)balloonViewTitleTapped:(CKBalloonView *)arg1;
@end

