//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class NSArray, NSString, NSURL, _TtC14BookFoundation12MResourceSet;

@interface (null) (BookFoundation)
@property(nonatomic, readonly) NSURL *url;
@property(nonatomic, readonly) _Bool isOrdered;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) _TtC14BookFoundation12MResourceSet *assetsResourceSet;
- (void)fetchAllAssetsWithCompletionHandler:(void (^)(NSError *))arg1;
- (void)fetchNextAssetsWithCompletionHandler:(void (^)(NSError *))arg1;
@property(nonatomic, readonly) NSArray *_assets;
@property(nonatomic, readonly) NSArray *assets;
@end

