//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class MKVibrantLabel;

__attribute__((visibility("hidden")))
@interface CarDestinationsTableHeaderView : UITableViewHeaderFooterView
{
    MKVibrantLabel *_titleLabel;
}

+ (id)reuseIdentifier;
@property(retain, nonatomic) MKVibrantLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (id)initWithReuseIdentifier:(id)arg1;

@end

