//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TraceSliderView;

@protocol TraceSliderViewDelegate <NSObject>
- (void)traceSliderViewCancelledEditing:(TraceSliderView *)arg1;
- (void)traceSliderView:(TraceSliderView *)arg1 editingEndedAtTime:(double)arg2;
- (void)traceSliderViewEditingDidBegin:(TraceSliderView *)arg1;
@end

