//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VideosUI/NSObject-Protocol.h>

@class NSNumber, VUIDownloadEntity;

@protocol VUIDownloadEntityDelegate <NSObject>

@optional
- (void)downloadEntity:(VUIDownloadEntity *)arg1 numberOfItemsDownloadingDidChange:(NSNumber *)arg2;
- (void)downloadEntity:(VUIDownloadEntity *)arg1 numberOfItemsDidChange:(unsigned long long)arg2;
@end

