//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UISDisplayContext;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface _UIScreenInitialDisplayConfigurationLoader : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    UISDisplayContext *_context;
    _Bool _hasRequestedPreload;
}

+ (id)sharedLoader;
- (void).cxx_destruct;
@property(readonly, nonatomic) UISDisplayContext *initialDisplayContext;
- (id)initialDisplayConfiguration;
- (void)_startPreloadInitialDisplayContext;

@end

