//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DownloadDataConsumer.h"

#import "SZExtractorDelegate-Protocol.h"

@class NSDictionary, NSString, SZExtractor;

@interface StreamingZipDownloadDataConsumer : DownloadDataConsumer <SZExtractorDelegate>
{
    SZExtractor *_extractor;
    _Bool _hasConsumedData;
    NSDictionary *_options;
    NSString *_path;
    double _percentComplete;
    unsigned long long _resumptionOffset;
}

- (void).cxx_destruct;
- (unsigned long long)resumptionOffset;
- (double)percentComplete;
- (_Bool)hasConsumedData;
- (id)_stringWithFileSystemRepresentation:(const char *)arg1 length:(unsigned long long)arg2;
- (id)_stringWithFileSystemRepresentation:(const char *)arg1;
- (unsigned long long)_diskUsageForPath:(id)arg1;
- (void)_initializeExtractorWithPath:(id)arg1 options:(id)arg2;
- (void)setExtractionProgress:(double)arg1;
- (void)truncate;
- (void)suspend;
- (void)reset;
- (_Bool)finish:(id *)arg1;
- (unsigned long long)diskUsage;
- (_Bool)consumeData:(id)arg1 error:(id *)arg2;
- (id)initWithPath:(id)arg1 options:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

