//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC9Reminders27TTRIReminderDetailPresenter.h"

#import "CNContactPickerDelegate-Protocol.h"

@interface _TtC9Reminders27TTRIReminderDetailPresenter (Reminders) <CNContactPickerDelegate>
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
@end

