//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9Reminders49TTRRemindersListChangeItemAttributeEditorProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *reminderChangeItems;
    MISSING_TYPE *didEdit;
    MISSING_TYPE *undoManager;
}

@end

