//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

#import <VideosUI/UIPointerInteractionDelegate-Protocol.h>
#import <VideosUI/VUILabelBaselineProtocol-Protocol.h>

@class NSShadow, NSString, UIColor, UILargeContentViewerInteraction, UIView, VUIImageView, VUILabel;

__attribute__((visibility("hidden")))
@interface VUIButton : UIControl <UIPointerInteractionDelegate, VUILabelBaselineProtocol>
{
    _Bool _hasDisclaimerText;
    _Bool _imageTrailsTextContent;
    _Bool _isTintColorAndBackgroundColorSaturated;
    UIView *_backgroundImageView;
    NSString *_groupName;
    NSString *_accessibilityText;
    double _width;
    double _height;
    unsigned long long _buttonType;
    UIColor *__buttonBackgroundColor;
    UIColor *_highlightColor;
    double _cornerRadius;
    double _minWidth;
    double _minHeight;
    double _maxWidth;
    double _maxHeight;
    NSShadow *_shadow;
    VUILabel *_textContentView;
    VUIImageView *_imageView;
    double _imageMaxWidth;
    double _imageMaxHeight;
    UIColor *_imageTintColor;
    UIColor *_imageHighlightColor;
    CDUnknownBlockType _selectActionHandler;
    UIColor *_adjustmentModeNormalTintColor;
    UIView *_backdropView;
    UILargeContentViewerInteraction *_largeContentViewerInteraction;
    VUIImageView *_imagesViewDefaultState;
    VUIImageView *_imagesViewHighlightedState;
    VUIImageView *_backgroundImagesViewDefaultState;
    VUIImageView *_backgroundImagesViewHighlightedState;
    struct UIEdgeInsets _padding;
    struct UIEdgeInsets _imageMargin;
}

- (void).cxx_destruct;
@property(retain, nonatomic) VUIImageView *backgroundImagesViewHighlightedState; // @synthesize backgroundImagesViewHighlightedState=_backgroundImagesViewHighlightedState;
@property(retain, nonatomic) VUIImageView *backgroundImagesViewDefaultState; // @synthesize backgroundImagesViewDefaultState=_backgroundImagesViewDefaultState;
@property(retain, nonatomic) VUIImageView *imagesViewHighlightedState; // @synthesize imagesViewHighlightedState=_imagesViewHighlightedState;
@property(retain, nonatomic) VUIImageView *imagesViewDefaultState; // @synthesize imagesViewDefaultState=_imagesViewDefaultState;
@property(nonatomic) _Bool isTintColorAndBackgroundColorSaturated; // @synthesize isTintColorAndBackgroundColorSaturated=_isTintColorAndBackgroundColorSaturated;
@property(retain, nonatomic) UILargeContentViewerInteraction *largeContentViewerInteraction; // @synthesize largeContentViewerInteraction=_largeContentViewerInteraction;
@property(retain, nonatomic) UIView *backdropView; // @synthesize backdropView=_backdropView;
@property(retain, nonatomic) UIColor *adjustmentModeNormalTintColor; // @synthesize adjustmentModeNormalTintColor=_adjustmentModeNormalTintColor;
@property(copy, nonatomic) CDUnknownBlockType selectActionHandler; // @synthesize selectActionHandler=_selectActionHandler;
@property(nonatomic) _Bool imageTrailsTextContent; // @synthesize imageTrailsTextContent=_imageTrailsTextContent;
@property(nonatomic) struct UIEdgeInsets imageMargin; // @synthesize imageMargin=_imageMargin;
@property(retain, nonatomic) UIColor *imageHighlightColor; // @synthesize imageHighlightColor=_imageHighlightColor;
@property(retain, nonatomic) UIColor *imageTintColor; // @synthesize imageTintColor=_imageTintColor;
@property(nonatomic) double imageMaxHeight; // @synthesize imageMaxHeight=_imageMaxHeight;
@property(nonatomic) double imageMaxWidth; // @synthesize imageMaxWidth=_imageMaxWidth;
@property(retain, nonatomic) VUIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) VUILabel *textContentView; // @synthesize textContentView=_textContentView;
@property(retain, nonatomic) NSShadow *shadow; // @synthesize shadow=_shadow;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double minHeight; // @synthesize minHeight=_minHeight;
@property(nonatomic) double minWidth; // @synthesize minWidth=_minWidth;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(retain, nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(retain, nonatomic) UIColor *_buttonBackgroundColor; // @synthesize _buttonBackgroundColor=__buttonBackgroundColor;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(readonly, nonatomic) unsigned long long buttonType; // @synthesize buttonType=_buttonType;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *accessibilityText; // @synthesize accessibilityText=_accessibilityText;
@property(nonatomic) _Bool hasDisclaimerText; // @synthesize hasDisclaimerText=_hasDisclaimerText;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(retain, nonatomic) UIView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (_Bool)scalesLargeContentImage;
- (id)largeContentImage;
- (id)largeContentTitle;
- (id)pointerInteraction:(id)arg1 styleForRegion:(id)arg2;
- (id)pointerInteraction:(id)arg1 regionForRequest:(id)arg2 defaultRegion:(id)arg3;
- (struct CGRect)_pointerShapeRect;
- (void)_updateBackgroundColor;
- (void)traitCollectionDidChange:(id)arg1;
- (void)_setupPrimaryWithUberBackdropView;
- (struct CGPoint)_centerWithViewSize:(struct CGSize)arg1 withParentSize:(struct CGSize)arg2;
- (void)_updateLayout;
- (void)_buttonTapped:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_configure;
- (_Bool)_hasBackgroundImage;
- (_Bool)_hasImage;
- (_Bool)_hasTitle;
- (double)bottomMarginWithBaselineMargin:(double)arg1;
- (double)topMarginWithBaselineMargin:(double)arg1;
- (void)revertTintColor;
- (void)saturateTintColorAndBackgroundColor;
- (void)setTintColor:(id)arg1;
- (void)prepareForReuse;
- (void)configureWithLayoutProperties;
- (double)baselineOffsetFromBottom;
- (double)topMarginToLabel:(id)arg1 withBaselineMargin:(double)arg2;
- (void)layoutSubviews;
- (struct CGSize)_imageSizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setBackgroundImage:(id)arg1 state:(unsigned long long)arg2;
- (void)setImageView:(id)arg1 state:(unsigned long long)arg2;
- (void)tintColorDidChange;
- (id)initWithType:(unsigned long long)arg1 interfaceStyle:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

