//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VideosUI/VUICollectionConfiguration.h>

@class UICollectionViewCell;

__attribute__((visibility("hidden")))
@interface VUILibraryiOSMenuCollectionConfiguration : VUICollectionConfiguration
{
    _Bool _isDesignedForIpadEnabled;
    UICollectionViewCell *_menuItemSizingCell;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isDesignedForIpadEnabled; // @synthesize isDesignedForIpadEnabled=_isDesignedForIpadEnabled;
@property(retain, nonatomic) UICollectionViewCell *menuItemSizingCell; // @synthesize menuItemSizingCell=_menuItemSizingCell;
- (id)_layout;
- (Class)classForCollectionViewCell;
- (double)minimumLineSpacing;
- (id)configureSizingCellForItem:(id)arg1 AtIndexPath:(id)arg2;
- (id)configureCollectionViewCellForCollectionView:(id)arg1 ForItem:(id)arg2 AtIndexPath:(id)arg3;
- (id)generateCollectionView;
- (id)init;

@end

