//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <KnowledgeGraphKit/NSCopying-Protocol.h>
#import <KnowledgeGraphKit/NSMutableCopying-Protocol.h>

@class _TtC17KnowledgeGraphKit20MAFloatVectorWrapper;

@interface MAFloatVector : NSObject <NSCopying, NSMutableCopying>
{
    _TtC17KnowledgeGraphKit20MAFloatVectorWrapper *_wrapper;
}

+ (id)meanVectorWithFloatVectors:(id)arg1;
+ (id)vectorRepeatingFloat:(float)arg1 count:(long long)arg2;
+ (id)onesOfCount:(long long)arg1;
+ (id)zerosOfCount:(long long)arg1;
+ (Class)wrapperClass;
- (void).cxx_destruct;
@property(readonly, nonatomic) _TtC17KnowledgeGraphKit20MAFloatVectorWrapper *wrapper; // @synthesize wrapper=_wrapper;
- (_Bool)_isArrayOfFloats:(id)arg1;
- (id)debugDescription;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isApproximatelyEqualTo:(id)arg1 epsilon:(float)arg2;
- (_Bool)isApproximatelyEqualTo:(id)arg1;
- (id)sliceFromStart:(long long)arg1 toEnd:(long long)arg2;
- (id)vectorByAppendingArray:(id)arg1;
- (id)vectorByAppendingVector:(id)arg1;
- (id)vectorByAppendingDoubles:(const double *)arg1 count:(long long)arg2;
- (id)vectorByAppendingFloats:(const float *)arg1 count:(long long)arg2;
- (id)vectorByAppendingFloat:(float)arg1;
- (id)vectorByElementwiseNaturalLogarithmIfPositive;
- (id)vectorByElementwiseNaturalLogarithm;
- (id)vectorByElementwiseRaisingToExponent:(float)arg1;
- (float)dotProductWithVector:(id)arg1;
- (id)vectorByElementwiseMultiplyingByVector:(id)arg1;
- (id)vectorByDividingByScalar:(float)arg1;
- (id)vectorByMultiplyingByScalar:(float)arg1;
- (id)vectorByAddingScalar:(float)arg1;
- (id)vectorBySubtractingScalar:(float)arg1;
- (id)vectorByAddingVector:(id)arg1;
- (id)vectorBySubtractingVector:(id)arg1;
- (id)data;
- (id)array;
- (float)floatAtIndex:(long long)arg1;
- (float)standardDeviation;
- (float)mean;
- (float)sumOfSquares;
- (float)sum;
@property(readonly, nonatomic) long long count;
- (id)initWithData:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)initWithFloats:(const float *)arg1 count:(long long)arg2;
- (id)initWithWrapper:(id)arg1;
- (id)init;

@end

