//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class FCFlintResourceManager, FREmbedConfigurationOperation, FRFlintEmbedConfiguration, NFUnfairLock, NSString;
@protocol FCNewsAppConfigurationManager;

@interface FRFlintEmbedConfigurationManager : NSObject
{
    _Bool _hasLoaded;
    id <FCNewsAppConfigurationManager> _appConfigurationManager;
    FCFlintResourceManager *_resourceManager;
    FRFlintEmbedConfiguration *_loadedConfiguration;
    NFUnfairLock *_lock;
    FREmbedConfigurationOperation *_operation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FREmbedConfigurationOperation *operation; // @synthesize operation=_operation;
@property(readonly, nonatomic) NFUnfairLock *lock; // @synthesize lock=_lock;
@property(readonly, nonatomic) FRFlintEmbedConfiguration *loadedConfiguration; // @synthesize loadedConfiguration=_loadedConfiguration;
@property(readonly, nonatomic) FCFlintResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
@property(readonly, nonatomic) id <FCNewsAppConfigurationManager> appConfigurationManager; // @synthesize appConfigurationManager=_appConfigurationManager;
@property(readonly, nonatomic) _Bool hasLoaded; // @synthesize hasLoaded=_hasLoaded;
- (id)operationForConfigurationManager:(id)arg1 resourceManager:(id)arg2;
- (void)loadEmbedDataWithCompletion:(CDUnknownBlockType)arg1;
- (id)embedForType:(id)arg1;
- (void)fetchEmbedConfigurationWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithConfigurationManager:(id)arg1 resourceManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

