//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <StoreKitUI/SKUIViewElement.h>

@class NSDictionary;

@interface SKUIEntityProviderListViewElement : SKUIViewElement
{
    NSDictionary *_entityProviders;
}

- (void).cxx_destruct;
- (id)entityProviderWithIdentifier:(id)arg1;
- (id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3;

@end

