//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <StoreKitUI/SKUIProductPageTableSection.h>

@class NSArray, NSNumberFormatter, SKUIClientContext, SKUIColorScheme, SKUIProductPageTableExpandableHeaderView;

__attribute__((visibility("hidden")))
@interface SKUIProductPageTableInAppPurchasesSection : SKUIProductPageTableSection
{
    SKUIClientContext *_clientContext;
    SKUIColorScheme *_colorScheme;
    SKUIProductPageTableExpandableHeaderView *_headerView;
    NSArray *_inAppPurchases;
    NSNumberFormatter *_numberFormatter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SKUIColorScheme *colorScheme; // @synthesize colorScheme=_colorScheme;
- (void)_reloadHeaderView;
- (id)tableViewCellForTableView:(id)arg1 indexPath:(id)arg2;
- (void)setExpanded:(_Bool)arg1;
- (long long)numberOfRowsInSection;
- (double)heightForCellInTableView:(id)arg1 indexPath:(id)arg2;
- (id)headerViewForTableView:(id)arg1;
- (id)initWithInAppPurchases:(id)arg1 clientContext:(id)arg2;

@end

