//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class UIView;

__attribute__((visibility("hidden")))
@interface SKUIMenuBarNavigationBarController
{
    UIView *_titleView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
- (id)fallbackTitleView;

@end

