//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Intents/NSCopying-Protocol.h>
#import <Intents/NSSecureCoding-Protocol.h>
#import <Intents/_INPBAlarmSearch-Protocol.h>

@class NSString, _INPBDataString, _INPBDateTimeRangeValue;

@interface _INPBAlarmSearch : PBCodable <_INPBAlarmSearch, NSSecureCoding, NSCopying>
{
    struct {
        unsigned int alarmReferenceType:1;
        unsigned int alarmSearchStatus:1;
        unsigned int includeSleepAlarm:1;
        unsigned int isMeridianInferred:1;
        unsigned int period:1;
    } _has;
    _Bool _includeSleepAlarm;
    _Bool _isMeridianInferred;
    int _alarmReferenceType;
    int _alarmSearchStatus;
    int _period;
    NSString *_identifier;
    _INPBDataString *_label;
    _INPBDateTimeRangeValue *_time;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(retain, nonatomic) _INPBDateTimeRangeValue *time; // @synthesize time=_time;
@property(nonatomic) int period; // @synthesize period=_period;
@property(retain, nonatomic) _INPBDataString *label; // @synthesize label=_label;
@property(nonatomic) _Bool isMeridianInferred; // @synthesize isMeridianInferred=_isMeridianInferred;
@property(nonatomic) _Bool includeSleepAlarm; // @synthesize includeSleepAlarm=_includeSleepAlarm;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) int alarmSearchStatus; // @synthesize alarmSearchStatus=_alarmSearchStatus;
@property(nonatomic) int alarmReferenceType; // @synthesize alarmReferenceType=_alarmReferenceType;
- (id)dictionaryRepresentation;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
@property(readonly, nonatomic) _Bool hasTime;
- (int)StringAsPeriod:(id)arg1;
- (id)periodAsString:(int)arg1;
@property(nonatomic) _Bool hasPeriod;
@property(readonly, nonatomic) _Bool hasLabel;
@property(nonatomic) _Bool hasIsMeridianInferred;
@property(nonatomic) _Bool hasIncludeSleepAlarm;
@property(readonly, nonatomic) _Bool hasIdentifier;
- (int)StringAsAlarmSearchStatus:(id)arg1;
- (id)alarmSearchStatusAsString:(int)arg1;
@property(nonatomic) _Bool hasAlarmSearchStatus;
- (int)StringAsAlarmReferenceType:(id)arg1;
- (id)alarmReferenceTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasAlarmReferenceType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

