//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/JSExport-Protocol.h>
#import <Intents/NSObject-Protocol.h>

@class INDateComponentsRange, NSArray;

@protocol INSearchForMessagesIntentExport <NSObject, JSExport>
@property(copy, nonatomic) NSArray *conversationIdentifiers;
@property(copy, nonatomic) NSArray *speakableGroupNames;
@property(copy, nonatomic) NSArray *notificationIdentifiers;
@property(copy, nonatomic) NSArray *identifiers;
@property(copy, nonatomic) INDateComponentsRange *dateTimeRange;
@property(nonatomic) unsigned long long attributes;
@property(copy, nonatomic) NSArray *searchTerms;
@property(copy, nonatomic) NSArray *senders;
@property(copy, nonatomic) NSArray *recipients;
- (id)init;
@end

