//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@interface _TtC19appstorecomponentsd21CommerceDialogHandler : NSObject
{
}

- (void)handleDialogRequest:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (void)handleAuthenticateRequest:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

