//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol NSObject;

@interface ASCDescriber : NSObject
{
    id <NSObject> _object;
    NSMutableArray *_properties;
}

+ (id)nilObject;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *properties; // @synthesize properties=_properties;
@property(readonly, nonatomic) id <NSObject> object; // @synthesize object=_object;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)finalizeDescription;
- (id)describeProperties;
- (id)describeObject;
- (void)addObject:(id)arg1 withName:(id)arg2;
- (void)addSensitiveObject:(id)arg1 withName:(id)arg2;
- (void)addDouble:(double)arg1 withName:(id)arg2;
- (void)addUInt64:(unsigned long long)arg1 withName:(id)arg2;
- (void)addInt64:(long long)arg1 withName:(id)arg2;
- (void)addUnsignedInteger:(unsigned long long)arg1 withName:(id)arg2;
- (void)addInteger:(long long)arg1 withName:(id)arg2;
- (void)addBool:(_Bool)arg1 withName:(id)arg2;
- (id)initWithObject:(id)arg1;

@end

