//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BackBoardServices/NSObject-Protocol.h>

@class BKSSystemApplicationClient;

@protocol BKSSystemApplicationClientDelegate <NSObject>
- (_Bool)clientIsAliveForWatchdog:(BKSSystemApplicationClient *)arg1;
@end

