//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class PDFSelection;

__attribute__((visibility("hidden")))
@interface PDFSelectionLayer : CALayer
{
    PDFSelection *selection;
}

- (void).cxx_destruct;

@end

