//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PassKitUI/NSObject-Protocol.h>

@class NSError, PKPaymentPass, PKSubcredentialProvisioningController;

@protocol PKSubcredentialProvisioningControllerDelegate <NSObject>
- (void)subcredentialProvisioningController:(PKSubcredentialProvisioningController *)arg1 didFinishWithPass:(PKPaymentPass *)arg2;

@optional
- (void)subcredentialProvisioningController:(PKSubcredentialProvisioningController *)arg1 didEnterState:(long long)arg2;
- (void)subcredentialProvisioningController:(PKSubcredentialProvisioningController *)arg1 shouldFailAfterError:(NSError *)arg2 withCompletion:(void (^)(_Bool))arg3;
- (void)subcredentialProvisioningController:(PKSubcredentialProvisioningController *)arg1 didFinishWithError:(NSError *)arg2 inState:(long long)arg3;
- (void)subcredentialProvisioningController:(PKSubcredentialProvisioningController *)arg1 didFinishWithError:(NSError *)arg2;
@end

