//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeUI/NSObject-Protocol.h>

@class HUDownloadControl, HUExpandableTextView, HULockupView;

@protocol HULockupViewDelegate <NSObject>

@optional
- (void)lockupView:(HULockupView *)arg1 expandableTextViewDidExpand:(HUExpandableTextView *)arg2;
- (void)lockupView:(HULockupView *)arg1 expandableTextViewDidCollapse:(HUExpandableTextView *)arg2;
- (void)lockupView:(HULockupView *)arg1 downloadControlTapped:(HUDownloadControl *)arg2;
@end

