//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <UserAlerts/NSObject-Protocol.h>

@class URTAlert;

@protocol URTAlertClientToServerInterface <NSObject>
- (oneway void)dismissAlert:(URTAlert *)arg1;
- (oneway void)presentAlert:(URTAlert *)arg1;
@end

