//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NetworkExtension/NSObject-Protocol.h>

@class NEIKEv2Packet;

@protocol NEIKEv2TransportDelegate <NSObject>
- (void)receivePacket:(NEIKEv2Packet *)arg1;
- (void)reportError:(int)arg1;
@end

