//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class NSMutableDictionary, RSBayWindowFPRemoval, RSCurvedWallDetection, RSDeduplicateOpeningOpenDoor, RSDoorWindowOfflineDetector, RSDoorWindowPostProcessor, RSNonUniformHeightEstimation, RSOfflineGeometryCalculation, RSOfflineKeyframeAccumulation, RSOfflineProjection2DZNode, RSOnlineOfflineAssociation, RSOpeningHeightAlignment, RSOutsideObjectRemoval, RSStructurePostProcess, RSWallOpeningOfflineDetector;

@interface RSOfflineFloorPlanGenerator
{
    RSDoorWindowOfflineDetector *_doorWindowDetector;
    RSWallOpeningOfflineDetector *_wallOpeningDetector;
    RSOfflineKeyframeAccumulation *_accumulator;
    RSOfflineGeometryCalculation *_geometryEstimator;
    RSCurvedWallDetection *_curvedWallDetector;
    RSOfflineProjection2DZNode *_projector;
    RSBayWindowFPRemoval *_baywindowFPRemoval;
    RSStructurePostProcess *_structurePostprocess;
    RSDeduplicateOpeningOpenDoor *_deduplicateOpeningOpenDoor;
    RSOnlineOfflineAssociation *_onlineOfflineAssociation;
    RSNonUniformHeightEstimation *_heightEstimator;
    RSOpeningHeightAlignment *_openingHeightAlignment;
    RSOutsideObjectRemoval *_removeOutsideObject;
    RSDoorWindowPostProcessor *_doorWindowPostProcessor;
    _Bool _wallOpeningMergeEnabled;
    _Bool _openingReplaceOpendoorEnabled;
    _Bool _opendoorReplaceOpeningEnabled;
    NSMutableDictionary *_debugInfo;
    _Bool _enableLiveDump;
}

- (void).cxx_destruct;
- (void)setDoorWindowBeautificationEnable:(_Bool)arg1;
- (void)clear;
- (id)beautifyObjects:(id)arg1 withFloorPlan:(id)arg2;
- (id)generateFloorPlanWithKeyframes:(id)arg1 initialAsset:(id)arg2 error:(id *)arg3;
- (id)generateFloorPlanWithKeyframes:(id)arg1 initialAsset:(id)arg2;
- (void)setNonUniformHeightEnable:(_Bool)arg1;
- (void)setOpendoorReplaceOpeningEnable:(_Bool)arg1;
- (void)setOpeningReplaceOpendoorEnable:(_Bool)arg1;
- (void)setWallOpeningMergeEnable:(_Bool)arg1;
- (id)init;
- (id)getDebugInfo;
- (void)setLiveDumpEnable:(_Bool)arg1;
- (id)geometryMeta;
- (const void *)lmapOfWall;

@end

