//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <DoNotDisturb/DNDContactHandle.h>

@interface DNDContactHandle (DNDSEventBehaviorEvolver)
- (_Bool)isPopulated;
@end

