//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <AuthKit/NSObject-Protocol.h>

@class AKPrivateEmailContext;

@protocol AKPrivateEmailClientProtocol <NSObject>
- (void)presentPrivateEmailUIForContext:(AKPrivateEmailContext *)arg1 completion:(void (^)(AKPrivateEmail *, NSError *))arg2;
@end

