//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class NSArray, NSDictionary, NSString, NSXPCListenerEndpoint;

@protocol FontServicesProtocol
- (void)resetIssuedFontsFor:(NSString *)arg1 reply:(void (^)(void))arg2;
- (void)synchronizeFontAssets:(NSArray *)arg1 reply:(void (^)(_Bool, NSDictionary *))arg2;
- (void)scheduleFontFilesDeletion:(NSArray *)arg1;
- (void)updatingUserFonts:(void (^)(void))arg1;
- (void)resumeAndShowAlertForSuspendedFontProviders:(void (^)(void))arg1;
- (void)fontChanged:(NSDictionary *)arg1 reply:(void (^)(void))arg2;
- (void)requestFonts:(NSString *)arg1 forClient:(NSXPCListenerEndpoint *)arg2 reply:(void (^)(_Bool))arg3;
- (void)requestFonts:(NSArray *)arg1 reply:(void (^)(NSDictionary *))arg2;
- (void)checkinForFontPicker:(void (^)(NSDictionary *))arg1;
- (void)checkin:(void (^)(NSDictionary *))arg1;
@end

