//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SoundAnalysis/SNMLModel-Protocol.h>

@class MLModelDescription, NSString;
@protocol SNMLModel;

__attribute__((visibility("hidden")))
@interface SNMLLockedModel : NSObject <SNMLModel>
{
    id <SNMLModel> _model;
    struct mutex _lock;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)predictionFromFeatures:(id)arg1 options:(id)arg2 error:(id *)arg3;
@property(readonly) MLModelDescription *modelDescription;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

