//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DOCConcreteLocation, DOCDocumentSource, NSArray, UIViewController, _TtC5Files22DOCHierarchyController;

@protocol _TtP5Files30DOCHierarchyControllerDelegate_
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didPopLocations:(long long)arg2;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 prepareToPopLocations:(long long)arg2 animated:(_Bool)arg3 completion:(void (^)(void))arg4;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 prepareControllerFor:(DOCConcreteLocation *)arg2:(DOCDocumentSource *)arg3 isUserInteraction:(_Bool)arg4 completion:(void (^)(UIViewController *))arg5;

@optional
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didReveal:(NSArray *)arg2 source:(DOCDocumentSource *)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didPrepend:(DOCConcreteLocation *)arg2 source:(DOCDocumentSource *)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 willPrepend:(DOCConcreteLocation *)arg2 source:(DOCDocumentSource *)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didReplaceLastViewControllerWith:(UIViewController *)arg2 animated:(_Bool)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 willReplaceLastViewControllerWith:(UIViewController *)arg2 animated:(_Bool)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didAppend:(UIViewController *)arg2 animated:(_Bool)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 willAppend:(UIViewController *)arg2 animated:(_Bool)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 didSet:(NSArray *)arg2 animated:(_Bool)arg3;
- (void)hierarchyController:(_TtC5Files22DOCHierarchyController *)arg1 willSet:(NSArray *)arg2 animated:(_Bool)arg3;
@end

