//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSConditionLock, NSString, RBSTerminationAssertion;

@interface ProcessTerminator : NSObject
{
    NSConditionLock *_condition;
    RBSTerminationAssertion *_assertion;
}

- (void).cxx_destruct;
- (void)assertionTargetProcessDidExit:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

