//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@interface PurchaseHistoryService : NSObject
{
}

+ (id)defaultService;
- (id)_currentClient;
- (void)updateWithContext:(unsigned long long)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)updateForAccountID:(long long)arg1 withContext:(unsigned long long)arg2 withReplyHandler:(CDUnknownBlockType)arg3;
- (void)showAllWithReplyHandler:(CDUnknownBlockType)arg1;
- (void)setHidden:(_Bool)arg1 forStoreItemID:(long long)arg2 withReplyHandler:(CDUnknownBlockType)arg3;
- (void)executeQuery:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;

@end

