//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <UIKit/UINavigationController.h>

@class CNContactViewController, DDAction, NSString;
@protocol DDRemoteActionPresenter;

__attribute__((visibility("hidden")))
@interface DDAddToContactsViewController : UINavigationController
{
    id <DDRemoteActionPresenter> _proxy;
    DDAction *_action;
    CNContactViewController *_personViewController;
    _Bool _contactBeingAdded;
}

+ (id)alternateNameForContact:(id)arg1;
+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
- (void).cxx_destruct;
@property(retain) DDAction *action; // @synthesize action=_action;
- (void)contactViewControllerForUnknownContactDidEndAddingToContacts:(id)arg1;
- (void)contactViewControllerForUnknownContactDidBeginAddingToContacts:(id)arg1;
- (void)setCancellable:(_Bool)arg1;
- (void)cancelPressed:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)doneWithAddingContactShouldDismiss:(_Bool)arg1;
- (void)adaptForPresentationInPopover:(_Bool)arg1;
- (void)setCancelButtonVisible:(_Bool)arg1;
- (void)prepareForAction:(id)arg1;
- (struct CGSize)preferredContentSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

