//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC16HealthMobilityUI51WalkingSteadinessAnalyticsOnboardingEventDataSource : NSObject
{
    MISSING_TYPE *healthStore;
    MISSING_TYPE *presentation;
    MISSING_TYPE *onboardingStep;
    MISSING_TYPE *changedDetailItems;
    MISSING_TYPE *defaultDetailItems;
    MISSING_TYPE *acceptDefaults;
}

- (void).cxx_destruct;
- (id)init;
- (id)biologicalSexWithError:(id *)arg1;
- (id)ageWithError:(id *)arg1;
- (id)acceptDefaultNotificationsWithError:(id *)arg1;
- (id)acceptDefaultWeightWithError:(id *)arg1;
- (id)acceptDefaultHeightWithError:(id *)arg1;
- (id)hasDefaultWeightWithError:(id *)arg1;
- (id)hasDefaultHeightWithError:(id *)arg1;
- (id)activeWatchProductTypeWithError:(id *)arg1;
- (id)provenanceWithError:(id *)arg1;
- (id)featureVersionWithError:(id *)arg1;
- (id)stepWithError:(id *)arg1;

@end

