//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CPLCloudKitZoneManager-Protocol.h"

@class CKContainer, CKDatabase, CKRecordID, CPLCloudKitOperationsTracker, NSError;

@protocol CPLCloudKitTaskController <CPLCloudKitZoneManager>
@property(readonly, nonatomic) _Bool canBoostBackgroundOperations;
@property(readonly, nonatomic) _Bool canBoostOperations;
@property(readonly, nonatomic, getter=isForeground) _Bool foreground;
@property(readonly, nonatomic, getter=isNetworkConnected) _Bool networkConnected;
@property(readonly, nonatomic) CPLCloudKitOperationsTracker *operationTracker;
@property(readonly, nonatomic) CKContainer *container;
@property(readonly, nonatomic) CKDatabase *sharedDatabase;
@property(readonly, nonatomic) CKDatabase *database;
- (CKRecordID *)filteredUserRecordIDFromRealRecordID:(CKRecordID *)arg1;
- (void)processTaskErrorIfNeeded:(NSError *)arg1;
@end

