//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (AppleAccount)
- (_Bool)aa_isSubsetOfArray:(id)arg1;
- (id)aa_mapNullable:(CDUnknownBlockType)arg1;
- (id)aa_map:(CDUnknownBlockType)arg1;
- (id)aa_firstObjectPassingTest:(CDUnknownBlockType)arg1;
- (id)aa_filter:(CDUnknownBlockType)arg1;
- (id)aa_arrayByRemovingObject:(id)arg1;
@end

