//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface BCAlertActionItem : NSObject
{
    NSString *_title;
    NSString *_subTitle;
    unsigned long long _actionType;
    CDUnknownBlockType _handler;
    UIImage *_icon;
    NSString *_iconName;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(copy, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithTitle:(id)arg1 subTitle:(id)arg2 iconName:(id)arg3 actionType:(unsigned long long)arg4 handler:(CDUnknownBlockType)arg5;

@end

