//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DayNavigationWeekScrollView, NSDate;

@protocol DayNavigationWeekScrollViewDelegate <NSObject>
- (void)dayNavigationWeekScrollView:(DayNavigationWeekScrollView *)arg1 didChangeCellWidth:(double)arg2;
- (void)dayNavigationWeekScrollView:(DayNavigationWeekScrollView *)arg1 selectedDateChanged:(NSDate *)arg2;
- (void)dayNavigationWeekScrollViewFailedToSelectDate:(void (^)(void))arg1;
- (_Bool)dayNavigationWeekScrollViewAllowedToChangeSelectedDate;
@end

