//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <CoreCDP/CDPDevice.h>

@interface CDPDevice (Daemon)
- (id)initWithEscrowRecordMetadata:(id)arg1;
- (id)initWithSecureBackupMetadataInfo:(id)arg1;
- (id)initWithEscrowRecord:(id)arg1;
- (id)initWithSecureBackupRecordInfo:(id)arg1;
@end

