//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/NSObject-Protocol.h>

@class INIntentSlotDescription, INStringLocalizer, NSArray, NSString;

@protocol INIntentSlotComposing <NSObject>
- (NSString *)localizeValueOfSlotDescription:(INIntentSlotDescription *)arg1 withLocalizer:(INStringLocalizer *)arg2;
- (NSArray *)intentSlotDescriptions;
@end

