//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ContentKit/WFCalendarItemContentItem.h>

@class EKEvent;

@interface WFCalendarEventContentItem : WFCalendarItemContentItem
{
}

+ (id)defaultSourceForRepresentation:(id)arg1;
+ (id)pluralFilterDescription;
+ (id)filterDescription;
+ (id)countDescription;
+ (id)pluralTypeDescription;
+ (id)typeDescription;
+ (id)ownedTypes;
+ (id)datebyApplyingComponents:(id)arg1 toDateComponents:(id)arg2;
+ (_Bool)hasLibrary;
+ (void)runQuery:(id)arg1 withItems:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)propertyBuilders;
+ (id)itemWithEKEvent:(id)arg1 fromEventStore:(id)arg2;
- (_Bool)canGenerateRepresentationForType:(id)arg1;
- (void)generateObjectRepresentations:(CDUnknownBlockType)arg1 options:(id)arg2 forClass:(Class)arg3;
@property(readonly, nonatomic) EKEvent *event;
- (id)changeTransaction;
- (_Bool)getListAltText:(CDUnknownBlockType)arg1;
- (_Bool)getListSubtitle:(CDUnknownBlockType)arg1;

@end

