//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <FMCore/NSCopying-Protocol.h>

@interface FMWeakWrapper : NSObject <NSCopying>
{
    id _object;
    unsigned long long _objectHash;
}

@property(nonatomic) unsigned long long objectHash; // @synthesize objectHash=_objectHash;
@property(nonatomic) __weak id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithObject:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

