//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Foundation/NSURL.h>

@class NSArray, NSDictionary, NSString, NSUUID;

@interface NSURL (ChatKitAdditions)
+ (id)ckSMSURLFromBusinessChatURL:(id)arg1;
+ (id)ckURLForChatIdentifier:(id)arg1 entryBody:(id)arg2;
+ (id)ckURLForResource:(id)arg1 withExtension:(id)arg2;
+ (id)__ck_appleMapsURLForCoordinate:(struct CLLocationCoordinate2D)arg1 coordinateName:(id)arg2;
@property(readonly, nonatomic) NSString *ckLaunchURLPresentContentForMessageGUID;
@property(readonly, nonatomic) NSArray *ckSuggestedReplies;
@property(readonly, nonatomic) NSString *ckLaunchURLPostComposeDismissal;
@property(readonly, nonatomic) _Bool ckIsUnitTestingURL;
@property(readonly, nonatomic) _Bool ckIsLaunchAppURL;
@property(readonly, nonatomic) _Bool ckAllowRetargeting;
@property(readonly, nonatomic) NSDictionary *ckLaunchURLBalloonPluginPayload;
@property(readonly, nonatomic) NSString *ckLaunchURLBalloonPluginBundleID;
- (_Bool)ckIsSMSPrivateURLScheme;
@property(readonly, nonatomic) _Bool ckShouldShowDigitalTouchCanvas;
@property(readonly, nonatomic) NSUUID *ckFaceTimeConversationUUID;
@property(readonly, nonatomic) NSURL *ckURLByPercentEncodingFragment;
@property(readonly, nonatomic) NSString *ckCollaborationSceneIdentifier;
@property(readonly, nonatomic) _Bool ckShouldInitiateCollaborationWithSend;
@property(readonly, nonatomic) _Bool ckShouldSendImmediately;
@property(readonly, nonatomic) _Bool ckShouldShowComposeUI;
- (id)ckWillNotLaunchComposeUIURL;
@end

