//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BrowserController, NSString, NSURL, NSUUID, UIViewController, WBSCompletionQuery;
@protocol CompletionItem;

@protocol CompletionItemActionHandler <NSObject>
- (void)searchTextCompletionAccessoryButtonTappedForCompletionItem:(id <CompletionItem>)arg1;
- (void)switchToTabWithUUID:(NSUUID *)arg1 inWindowWithUUID:(NSUUID *)arg2;
- (BrowserController *)browserController;
- (void)resumeSearchWithQuery:(WBSCompletionQuery *)arg1;
- (void)presentDetail:(UIViewController *)arg1;
- (void)findOnPage;
- (void)openURLInExternalApplication:(NSURL *)arg1;
- (void)goToURL:(NSURL *)arg1;
- (void)goToURLString:(NSString *)arg1;
- (void)search:(NSString *)arg1;
@end

