//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleAccountUI/AAUISwitchTableViewCell.h>

@class NSString;

@interface _AAUIDataclassTableViewCell : AAUISwitchTableViewCell
{
    NSString *_dataclass;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *dataclass; // @synthesize dataclass=_dataclass;

@end

