//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <GameController/_GCIPCRemoteEndpointInterface-Protocol.h>

@class NSString;

@protocol GCSystemGestureXPCProxyRemoteServerEndpointInterface <_GCIPCRemoteEndpointInterface>
- (void)fetchSystemGesturesStateWithReply:(void (^)(GCSystemGesturesState *))arg1;
- (void)enableSystemGestureForInput:(NSString *)arg1;
- (void)disableSystemGestureForInput:(NSString *)arg1;
@end

