//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScreenTimeSettingsUI/STTableCell.h>

@class STNoUsageDataView, STUsageGraphViewController, STUsageSummaryTitleView;

__attribute__((visibility("hidden")))
@interface STOverallUsageSummaryCell : STTableCell
{
    STUsageSummaryTitleView *_titleView;
    STUsageGraphViewController *_weekGraphViewController;
    STNoUsageDataView *_noUsageDataView;
}

- (void).cxx_destruct;
@property(readonly) STNoUsageDataView *noUsageDataView; // @synthesize noUsageDataView=_noUsageDataView;
@property(readonly) STUsageGraphViewController *weekGraphViewController; // @synthesize weekGraphViewController=_weekGraphViewController;
@property(readonly) STUsageSummaryTitleView *titleView; // @synthesize titleView=_titleView;
- (void)_setNoUsageDataViewVisibility;
- (void)setValue:(id)arg1;
- (id)value;
- (void)_hasMulitlineLayoutDidChangeFrom:(_Bool)arg1 to:(_Bool)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

