//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Accounts/ACAccount.h>

@class NSString;

@interface ACAccount (ICDManageableAccount)
@property(readonly, nonatomic, getter=isManageable) _Bool manageable;
@property(readonly, copy, nonatomic) NSString *accountDSID;

// Remaining properties
@property(readonly, nonatomic, getter=isActive) _Bool active;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

