//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class NSNumber, NSString, NSURL;

@interface SagaUploadPlaylistArtworkOperation
{
    long long _playlistPersistentID;
    NSNumber *_dsid;
    NSString *_cuid;
    NSString *_troveID;
    NSString *_userArtworkToken;
    NSNumber *_containerCloudID;
    NSURL *_assetURL;
    unsigned long long _assetFileSize;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long assetFileSize; // @synthesize assetFileSize=_assetFileSize;
@property(retain, nonatomic) NSURL *assetURL; // @synthesize assetURL=_assetURL;
@property(retain, nonatomic) NSNumber *containerCloudID; // @synthesize containerCloudID=_containerCloudID;
@property(retain, nonatomic) NSString *userArtworkToken; // @synthesize userArtworkToken=_userArtworkToken;
@property(retain, nonatomic) NSString *troveID; // @synthesize troveID=_troveID;
@property(retain, nonatomic) NSString *cuid; // @synthesize cuid=_cuid;
@property(retain, nonatomic) NSNumber *dsid; // @synthesize dsid=_dsid;
@property(nonatomic) long long playlistPersistentID; // @synthesize playlistPersistentID=_playlistPersistentID;
- (id)_bodyDataWithAdditionalBodyFields:(id)arg1;
- (id)_requestWithURL:(id)arg1 URLBagKey:(id)arg2 timeoutInterval:(double)arg3 additionalBodyFields:(id)arg4;
- (id)_standardBodyDictionaryWithAdditionalFields:(id)arg1;
- (id)_responseBodyForRequest:(id)arg1 retryTimeout:(double)arg2 debugName:(id)arg3;
- (void)_uploadArtworkAssetWithInfo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_uploadArtworkAssetWithInfo:(id)arg1 uploadResponsesURL:(id)arg2 uploadResponseData:(id)arg3 postUploadBackOffDelay:(unsigned int)arg4 followupDownloadRequestsURL:(id)arg5;
- (void)_downloadRequestsFromURL:(id)arg1 uploadResponsesURL:(id)arg2;
- (void)_initiateArtworkUpload;
- (void)main;
- (_Bool)isPersistent;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithConfiguration:(id)arg1 clientIdentity:(id)arg2 playlistPersistentID:(long long)arg3;
- (id)initWithClientIdentity:(id)arg1 playlistPersistentID:(long long)arg2;

@end

