//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <SpringBoardHome/NSObject-Protocol.h>

@class SBIconLabelImageParameters, SBIconView, UIView, _UILegibilitySettings;
@protocol SBIconLabelView, SBIconLabelViewFactory;

@protocol SBIconLabelViewFactory <NSObject>
+ (id <SBIconLabelViewFactory>)sharedInstance;
- (_Bool)canUseIconLabelView:(UIView<SBIconLabelView> *)arg1 toDisplayLabelWithSettings:(_UILegibilitySettings *)arg2 imageParameters:(SBIconLabelImageParameters *)arg3 forIconView:(SBIconView *)arg4;
- (UIView<SBIconLabelView> *)iconLabelViewWithSettings:(_UILegibilitySettings *)arg1 imageParameters:(SBIconLabelImageParameters *)arg2 forIconView:(SBIconView *)arg3;
- (void)prewarmForSettings:(_UILegibilitySettings *)arg1 maxSize:(struct CGSize)arg2 minSize:(struct CGSize)arg3 scale:(double)arg4;
@end

