//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__NPLPeopleViewCellAccessibility_super.h"

@interface NPLPeopleViewCellAccessibility : __NPLPeopleViewCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)pageViewController:(id)arg1 didFinishAnimating:(_Bool)arg2 previousViewControllers:(id)arg3 transitionCompleted:(_Bool)arg4;
- (_Bool)_accessibilityShouldSortTableViewCellChildren;
- (_Bool)_accessibilityIgnoreInternalLabels;

@end

