//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_source;

@interface KNAnimationDelayedCallback : NSObject
{
    double _delay;
    double _startTime;
    id _target;
    SEL _selector;
    id _object;
    CDUnknownBlockType _block;
    NSObject<OS_dispatch_source> *_sourceTimer;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)cancel;
- (void)resume;
- (void)pause;
- (void)run;
- (void)p_performSelectorOnTarget;
- (id)initWithBlock:(CDUnknownBlockType)arg1 delay:(double)arg2;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3 delay:(double)arg4;

@end

