//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Silex/NSObject-Protocol.h>

@class TSWPSmartField, UIDragInteraction, UIDragItem;
@protocol UIDragSession;

@protocol SXTangierDragItemProvider <NSObject>
- (UIDragItem *)dragItemForSmartField:(TSWPSmartField *)arg1 interaction:(UIDragInteraction *)arg2 session:(id <UIDragSession>)arg3;
@end

