//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/_UIDatePickerCalendarDateComponent.h>

__attribute__((visibility("hidden")))
@interface _UIDatePickerCalendarMonth : _UIDatePickerCalendarDateComponent
{
    _UIDatePickerCalendarMonth *_previousMonth;
    _UIDatePickerCalendarMonth *_nextMonth;
}

+ (unsigned long long)representedCalendarUnits;
- (void).cxx_destruct;
@property(readonly, nonatomic) _UIDatePickerCalendarMonth *nextMonth;
@property(readonly, nonatomic) _UIDatePickerCalendarMonth *previousMonth;
- (id)_monthWithOffset:(long long)arg1;
- (id)dayMatchingOrdinalDay:(id)arg1;
- (id)dayWithDate:(id)arg1 assignedMonth:(id)arg2;

@end

