//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/UIIndexBarViewDelegate-Protocol.h>

@class UIIndexBarAccessoryView, UIIndexBarEntry;

@protocol UIIndexBarAccessoryViewDelegate <UIIndexBarViewDelegate>

@optional
- (struct CGPoint)indexBarAccessoryView:(UIIndexBarAccessoryView *)arg1 contentOffsetForEntry:(UIIndexBarEntry *)arg2 atIndex:(long long)arg3;
@end

