//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/UIAnimatablePropertyBase.h>

@class UIAnimatableProperty, _UIViewAnimatablePropertyTransformer;

@interface UIViewFloatAnimatableProperty : UIAnimatablePropertyBase
{
    _Bool _performingInterpolationBetweenTwoStates;
    UIAnimatableProperty *_animatableProperty;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool performingInterpolationBetweenTwoStates; // @synthesize performingInterpolationBetweenTwoStates=_performingInterpolationBetweenTwoStates;
@property(retain, nonatomic) UIAnimatableProperty *animatableProperty; // @synthesize animatableProperty=_animatableProperty;
@property(retain, nonatomic) _UIViewAnimatablePropertyTransformer *transformer;
- (void)dealloc;
@property(readonly, nonatomic) double presentationValue;
@property(readonly, nonatomic, getter=isInvalidated) _Bool invalidated;
- (void)invalidate;
@property(nonatomic) double velocity;
@property(nonatomic) double value;
- (id)init;

@end

