//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface _UIScrollViewFPSHUDGraphView : UIView
{
    unsigned int arr[150];
}

- (void)drawRect:(struct CGRect)arg1;
- (void)setColorForFramerate:(unsigned int)arg1 context:(struct CGContext *)arg2;
- (id)init;

@end

