//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "_UIStatusBarVisualProvider_FixedSplit.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIStatusBarVisualProvider_Split1284 : _UIStatusBarVisualProvider_FixedSplit
{
}

+ (double)trailingEdgeInsetLeadingAdjustment;
+ (double)pillCenteringOffset;
+ (struct CGSize)notchSize;
+ (double)nativeDisplayWidth;
- (double)bottomLeadingTopOffset;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

