//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class _UIDimmingKnockoutBackdropView;

__attribute__((visibility("hidden")))
@interface UIInterfaceActionConcreteVisualStyle_iOSInlineActionSheet
{
    _UIDimmingKnockoutBackdropView *_inlineBackgroundView;
}

- (void).cxx_destruct;
- (id)_preferredActionFont;
- (id)_regularActionFont;
- (double)_actionTitleFontSize;
- (id)newGroupBackgroundViewWithGroupViewState:(id)arg1;
- (id)newActionBackgroundViewForViewState:(id)arg1;
- (double)verticalImageContentSpacing;
- (double)horizontalImageContentSpacing;
- (struct UIEdgeInsets)contentMargin;
- (struct CGSize)minimumActionContentSize;

@end

