//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "UIPressesEvent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIPhysicalKeyboardEvent : UIPressesEvent
{
    _Bool _canPrivatize;
    _Bool _keyCommandHandlingBeforePublic;
    _Bool _keyEventForwardedFromInputUIHost;
    _Bool _shiftDown;
    _Bool __externalEvent;
    int _inputFlags;
    unsigned int _keyCommandCode;
    NSString *_modifiedInput;
    NSString *_unmodifiedInput;
    NSString *_shiftModifiedInput;
    NSString *_commandModifiedInput;
    NSString *_markedInput;
    long long _modifierFlags;
    NSString *_privateInput;
    long long _privateModifierFlags;
    NSString *_privateShiftModifiedInput;
    NSString *_privateCommandModifiedInput;
    NSString *_hint;
    long long __keyCode;
    long long _source;
}

+ (id)_eventWithInput:(id)arg1 inputFlags:(int)arg2;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic, getter=_isExternalEvent) _Bool _externalEvent; // @synthesize _externalEvent=__externalEvent;
@property(nonatomic) _Bool shiftDown; // @synthesize shiftDown=_shiftDown;
@property(nonatomic) _Bool keyEventForwardedFromInputUIHost; // @synthesize keyEventForwardedFromInputUIHost=_keyEventForwardedFromInputUIHost;
@property(nonatomic) _Bool keyCommandHandlingBeforePublic; // @synthesize keyCommandHandlingBeforePublic=_keyCommandHandlingBeforePublic;
@property(nonatomic) unsigned int keyCommandCode; // @synthesize keyCommandCode=_keyCommandCode;
@property(nonatomic) long long source; // @synthesize source=_source;
@property(nonatomic) long long _keyCode; // @synthesize _keyCode=__keyCode;
@property(retain, nonatomic) NSString *_hint; // @synthesize _hint;
@property(retain, nonatomic) NSString *_privateCommandModifiedInput; // @synthesize _privateCommandModifiedInput;
@property(retain, nonatomic) NSString *_privateShiftModifiedInput; // @synthesize _privateShiftModifiedInput;
@property(nonatomic) long long _privateModifierFlags; // @synthesize _privateModifierFlags;
@property(retain, nonatomic) NSString *_privateInput; // @synthesize _privateInput;
@property(nonatomic) int _inputFlags; // @synthesize _inputFlags;
@property(nonatomic) long long _modifierFlags; // @synthesize _modifierFlags;
@property(retain, nonatomic) NSString *_markedInput; // @synthesize _markedInput;
@property(retain, nonatomic) NSString *_commandModifiedInput; // @synthesize _commandModifiedInput;
@property(retain, nonatomic) NSString *_shiftModifiedInput; // @synthesize _shiftModifiedInput;
@property(retain, nonatomic) NSString *_unmodifiedInput; // @synthesize _unmodifiedInput;
@property(retain, nonatomic) NSString *_modifiedInput; // @synthesize _modifiedInput;
@property(readonly, nonatomic) long long _gsModifierFlags;
- (long long)modifierFlags;
- (void)_privatize;
- (id)_cloneEvent;
- (_Bool)isEqual:(id)arg1;
- (_Bool)_shouldAttemptSecurePasteAuthentication;
- (_Bool)_matchesKeyCommand:(id)arg1 usesPrivateShiftModifiedInput:(_Bool)arg2;
- (void)_setHIDEvent:(struct __IOHIDEvent *)arg1 keyboard:(struct __GSKeyboard *)arg2;
@property(readonly, nonatomic) _Bool _isARepeat;
@property(readonly, nonatomic) _Bool _isModifierKey;
- (_Bool)_isPhysicalKeyEvent;
@property(readonly, nonatomic) _Bool _isGlobeKey;
@property(readonly, nonatomic) _Bool _isEjectKey;
@property(readonly, nonatomic) _Bool _isKeyDown;
- (long long)type;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

