//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface _SFSafariDataSharingController : NSObject
{
    NSObject<OS_dispatch_queue> *_dataSharingQueue;
    NSMutableArray *_appBundlesWithSeparateData;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)clearAllWebsitesData;
- (void)checkInAppBundleIDIfNeeded:(id)arg1;
- (void)_loadAppBundlesWithSeparateDataIfNeeded;
- (id)systemDataContainerURLWithAppBundleID:(id)arg1;
- (id)init;

@end

