//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Navigation/NSObject-Protocol.h>

@class MNNavigationStateManager;

@protocol MNNavigationStateObserver <NSObject>

@optional
- (void)stateManager:(MNNavigationStateManager *)arg1 didChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
- (void)stateManager:(MNNavigationStateManager *)arg1 willChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
@end

