//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Foundation/NSDate.h>

@class NSString;

@interface NSDate (VK)
- (_Bool)vk_isLaterThanDate:(id)arg1;
- (_Bool)vk_isEarlierThanDate:(id)arg1;
- (id)vk_briefFormattedDate:(_Bool)arg1;
@property(readonly, nonatomic) NSString *vk_briefFormattedDateForAccessibility;
@property(readonly, nonatomic) NSString *vk_briefFormattedDate;
@property(readonly, nonatomic) NSString *vk_shortFormattedDate;
@property(readonly, nonatomic) NSString *vk_localDateWithSeconds;
@property(readonly, nonatomic) _Bool vk_isYesterday;
@property(readonly, nonatomic) _Bool vk_isToday;
@end

