//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreSpotlight/_MDExtensionManager.h>

@interface _MDIndexExtensionManager : _MDExtensionManager
{
}

+ (void)setMemoryPressureStatus:(unsigned long long)arg1;
+ (id)sharedManager;
- (id)init;

@end

