//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Silex/SXJSONAction.h>

#import <Silex/SXSubscribeAction-Protocol.h>

@class NSString;
@protocol SXAction;

@interface SXJSONSubscribeAction : SXJSONAction <SXSubscribeAction>
{
}

+ (Class)classForProtocolProperty:(id)arg1 withValue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) id <SXAction> postPurchaseAction; // @dynamic postPurchaseAction;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *type;

@end

