//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Silex/SXJSONObject.h>

@class NSString, NSURL;

@interface SXOEmbedResponse : SXJSONObject
{
}

+ (id)jsonPropertyNameForObjCPropertyName:(id)arg1;
- (id)objectForKey:(id)arg1;
@property(readonly, nonatomic) struct CGSize thumbnailSize;
- (double)cacheAgeWithValue:(id)arg1 withType:(int)arg2;

// Remaining properties
@property(readonly, nonatomic) NSString *authorName; // @dynamic authorName;
@property(readonly, nonatomic) NSURL *authorURL; // @dynamic authorURL;
@property(readonly, nonatomic) double cacheAge; // @dynamic cacheAge;
@property(readonly, nonatomic) NSString *providerName; // @dynamic providerName;
@property(readonly, nonatomic) NSURL *providerURL; // @dynamic providerURL;
@property(readonly, nonatomic) double thumbnailHeight; // @dynamic thumbnailHeight;
@property(readonly, nonatomic) NSURL *thumbnailURL; // @dynamic thumbnailURL;
@property(readonly, nonatomic) double thumbnailWidth; // @dynamic thumbnailWidth;
@property(readonly, nonatomic) NSString *title; // @dynamic title;
@property(readonly, nonatomic) NSString *version; // @dynamic version;

@end

