//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VCPFaceCropGenerator : NSObject
{
}

+ (id)generateFaceCropsFromSourceDescriptors:(id)arg1 withProgressBlock:(CDUnknownBlockType)arg2 andFailureBlock:(CDUnknownBlockType)arg3 andCancelBlock:(id)arg4;
+ (id)_generateFaceCropWithDescriptor:(id)arg1 andCancelBlock:(id)arg2 error:(id *)arg3;
+ (id)_faceCropDataForImage:(id)arg1 andNormalizedFaceRect:(struct CGRect)arg2 error:(id *)arg3;
+ (void)_reportCancellationOfRemainingFaceCropSourceDescriptors:(id)arg1 withStartingIndex:(unsigned long long)arg2 andFailureBlock:(CDUnknownBlockType)arg3;

@end

