//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VCPTimeMeasurement : NSObject
{
    struct mach_timebase_info _timebase;
    unsigned long long _start;
    _Bool _started;
    double _elapsedTimeSeconds;
}

@property(readonly) _Bool started; // @synthesize started=_started;
@property(readonly) double elapsedTimeSeconds; // @synthesize elapsedTimeSeconds=_elapsedTimeSeconds;
- (void)reset;
- (int)stop;
- (int)start;
- (id)init;

@end

