//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/INObject.h>

@class NSNumber, NSString;

@interface LanguageOption : INObject
{
}

@property(nonatomic, readonly) NSString *description;

// Remaining properties
@property(copy, nonatomic) NSNumber *isActive; // @dynamic isActive;
@property(copy, nonatomic) NSString *languageIdentifier; // @dynamic languageIdentifier;
@property(copy, nonatomic) NSString *languageTag; // @dynamic languageTag;
@property(copy, nonatomic) NSString *name; // @dynamic name;

@end

