//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <WallpaperKit/WKWallpaper-Protocol.h>

@class NSString;

@interface WKAbstractWallpaper : NSObject <WKWallpaper>
{
    unsigned long long _identifier;
    NSString *_name;
    unsigned long long _type;
}

+ (id)new;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) unsigned long long identifier; // @synthesize identifier=_identifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIdentifier:(unsigned long long)arg1 name:(id)arg2;
- (id)init;

@end

