//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <PassKitCore/NSCopying-Protocol.h>
#import <PassKitCore/NSSecureCoding-Protocol.h>

@class NSString, NSUUID;

@interface PKPeerPaymentRequestToken : NSObject <NSSecureCoding, NSCopying>
{
    NSString *_requestToken;
    NSUUID *_deviceScoreIdentifier;
}

+ (_Bool)supportsSecureCoding;
+ (id)informalRequestToken;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSUUID *deviceScoreIdentifier; // @synthesize deviceScoreIdentifier=_deviceScoreIdentifier;
@property(readonly, copy, nonatomic) NSString *requestToken; // @synthesize requestToken=_requestToken;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isInformalRequestToken;
- (_Bool)isEqualToPeerPaymentRequestToken:(id)arg1;
- (id)initWithRequestToken:(id)arg1 deviceScoreIdentifier:(id)arg2;

@end

