//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TipsCore/TPSAnalyticsEvent.h>

@class NSNumber, NSString;

@interface TPSAnalyticsEventAppLaunched : TPSAnalyticsEvent
{
    _Bool _needsSessionReset;
    _Bool _landingPage;
    NSString *_contentID;
    NSString *_collectionID;
    NSNumber *_launchNumber;
    NSString *_userType;
    NSString *_launchType;
}

+ (id)lastRecordedLaunchType;
+ (void)appSessionEndedWithType:(id)arg1;
+ (id)_latestSessionEvent;
+ (id)_initialSessionEvent;
+ (id)_currentSessionEvents;
+ (id)firstLaunchEvent;
+ (id)eventWithContentID:(id)arg1 collectionID:(id)arg2 launchType:(id)arg3;
+ (void)resetLaunchNumber;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *launchType; // @synthesize launchType=_launchType;
@property(readonly, nonatomic) NSString *userType; // @synthesize userType=_userType;
@property(readonly, nonatomic) NSNumber *launchNumber; // @synthesize launchNumber=_launchNumber;
@property(retain, nonatomic) NSString *collectionID; // @synthesize collectionID=_collectionID;
@property(retain, nonatomic) NSString *contentID; // @synthesize contentID=_contentID;
@property(readonly, nonatomic) _Bool landingPage; // @synthesize landingPage=_landingPage;
- (void)_aggregateLog;
- (void)log;
- (void)persistKeys;
- (id)mutableAnalyticsEventRepresentation;
- (id)eventName;
- (void)encodeWithCoder:(id)arg1;
- (void)_updateLaunchCount;
- (id)_initFirstLaunchEvent;
- (id)_initWithContentID:(id)arg1 collectionID:(id)arg2 launchType:(id)arg3;
- (id)userTypeString;
- (id)initWithCoder:(id)arg1;

@end

