//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSSet;

@interface GTXPCDispatcher : NSObject
{
    NSSet *_protocolMethods;
}

- (void).cxx_destruct;
- (void)dispatchMessage:(id)arg1 replyConnection:(id)arg2;
- (id)initWithProtocolMethods:(id)arg1;

@end

