//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface SKUIOverlayFlipTransition : NSObject
{
    UIView *_flipSourceView;
}

@property(retain, nonatomic) UIView *flipSourceView; // @synthesize flipSourceView=_flipSourceView;
- (void).cxx_destruct;

@end

