//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Silex/NSCopying-Protocol.h>

@interface SXComponentLayoutRules : NSObject <NSCopying>
{
    _Bool _allowsIntersection;
    _Bool _shouldSpanAllColumns;
    _Bool _allowsSiblingBasedResizing;
    _Bool _shouldIgnoreDocumentMargin;
    unsigned long long _minimumColumnSpan;
}

+ (id)bodyComponentLayoutRules;
+ (id)twoColumnLayoutRules;
+ (id)fullWidthLayoutRules;
+ (id)defaultLayoutRules;
@property(nonatomic) _Bool shouldIgnoreDocumentMargin; // @synthesize shouldIgnoreDocumentMargin=_shouldIgnoreDocumentMargin;
@property(nonatomic) _Bool allowsSiblingBasedResizing; // @synthesize allowsSiblingBasedResizing=_allowsSiblingBasedResizing;
@property(nonatomic) _Bool shouldSpanAllColumns; // @synthesize shouldSpanAllColumns=_shouldSpanAllColumns;
@property(nonatomic) _Bool allowsIntersection; // @synthesize allowsIntersection=_allowsIntersection;
@property(nonatomic) unsigned long long minimumColumnSpan; // @synthesize minimumColumnSpan=_minimumColumnSpan;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

