//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC20SiriAppLaunchIntents26CloseAppNeedsValueStrategy : _TtCs12_SwiftObject
{
    MISSING_TYPE *appLaunchFeatureFlags;
    MISSING_TYPE *deviceState;
    MISSING_TYPE *dialogProvider;
    MISSING_TYPE *dialogResponseUtil;
    MISSING_TYPE *referenceResolver;
    MISSING_TYPE *responseGenerator;
}

@end

