//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface SecExperimentConfig : NSObject
{
    unsigned int _fleetSampleRate;
    unsigned int _deviceSampleRate;
    NSString *_identifier;
    NSDictionary *_configurationData;
    NSDictionary *_config;
}

- (void).cxx_destruct;
@property(retain) NSDictionary *config; // @synthesize config=_config;
@property(retain) NSDictionary *configurationData; // @synthesize configurationData=_configurationData;
@property unsigned int deviceSampleRate; // @synthesize deviceSampleRate=_deviceSampleRate;
@property unsigned int fleetSampleRate; // @synthesize fleetSampleRate=_fleetSampleRate;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly) _Bool isSampled;
- (_Bool)shouldRunWithSamplingRate:(id)arg1;
- (unsigned int)hostHash;
- (id)initWithConfiguration:(id)arg1;

@end

