//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VideosUI/VUIProductShowcaseViewController.h>

__attribute__((visibility("hidden")))
@interface VUICanvasBrowserViewController : VUIProductShowcaseViewController
{
    _Bool _hasBanner;
}

@property(nonatomic) _Bool hasBanner; // @synthesize hasBanner=_hasBanner;
- (long long)_overrideLargeTitleDisplayMode;
- (void)updateWithViewElement:(id)arg1;

@end

