//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUI/PUPhotosAlbumViewController.h>

@class NSString, PHFetchResult, PHPhotosHighlight;

__attribute__((visibility("hidden")))
@interface PUCurationTripKeyAssetBrowserDebugViewController : PUPhotosAlbumViewController
{
    NSString *_tripKeyAssetUUID;
    PHFetchResult *_childHighlights;
    PHPhotosHighlight *_tripHighlight;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PHPhotosHighlight *tripHighlight; // @synthesize tripHighlight=_tripHighlight;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)_update;
- (_Bool)updateSpec;
- (void)viewDidLoad;

@end

