//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppSupportUI/NSObject-Protocol.h>

@class NSArray;

@protocol NUIGridDimension <NSObject>
@property(nonatomic) long long alignment;
@property(nonatomic) double spacingAfter;
@property(nonatomic) double length;
@property(nonatomic, getter=isHidden) _Bool hidden;
@property(copy, nonatomic) NSArray *arrangedSubviews;
@end

