//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MetalPerformanceShadersGraph/MPSGraphOptimizer.h>

@class MPSGraphTensor, MPSGraphVariableOp;

@interface MPSGraphAdamOptimizer : MPSGraphOptimizer
{
    MPSGraphTensor *_beta1Tensor;
    MPSGraphTensor *_beta2Tensor;
    MPSGraphTensor *_epsilonTensor;
    MPSGraphVariableOp *_iterationsVariable;
}

- (void).cxx_destruct;
- (id)initWithGraph:(id)arg1 lossTensor:(id)arg2 learningRateTensor:(id)arg3 trainableVariables:(id)arg4 name:(id)arg5;
- (id)initWithGraph:(id)arg1 learningRateTensor:(id)arg2 trainableVariables:(id)arg3 variablesToGradientTensorMap:(id)arg4 name:(id)arg5;
- (id)initWithGraph:(id)arg1 lossTensor:(id)arg2 learningRateTensor:(id)arg3 beta1:(float)arg4 beta2:(float)arg5 epsilon:(float)arg6 iterations:(unsigned long long)arg7 trainableVariables:(id)arg8 name:(id)arg9;
- (id)initWithGraph:(id)arg1 learningRateTensor:(id)arg2 beta1:(float)arg3 beta2:(float)arg4 epsilon:(float)arg5 iterations:(unsigned long long)arg6 trainableVariables:(id)arg7 variablesToGradientTensorMap:(id)arg8 name:(id)arg9;

@end

