//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SiriOntology/NSSecureCoding-Protocol.h>

@class USOSerializedGraph;

@interface SIRINLUTask : NSObject <NSSecureCoding>
{
    USOSerializedGraph *_task;
    double _score;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) double score; // @synthesize score=_score;
@property(retain, nonatomic) USOSerializedGraph *task; // @synthesize task=_task;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithTask:(id)arg1 score:(double)arg2;

@end

