//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (CAColorMatrixAdditions)
+ (id)valueWithCAColorMatrix:(struct CAColorMatrix)arg1;
- (struct CAColorMatrix)CAColorMatrixValue;
@end

