//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;

@protocol UIKBCacheableView <NSObject>
@property(readonly, nonatomic) _Bool keepNonPersistent;
@property(readonly, nonatomic) double cachedWidth;
@property(readonly, nonatomic) _Bool cacheDeferable;
@property(readonly, nonatomic) NSString *cacheKey;
- (NSDictionary *)cacheKeysForRenderFlags:(NSArray *)arg1;

@optional
@property(readonly, nonatomic) long long cacheDeferPriority;
- (void)drawContentsOfRenderers:(NSArray *)arg1;
@end

