//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <AvatarUI/NSObject-Protocol.h>

@protocol AVTDiscardableContent <NSObject>
@property(copy, nonatomic) CDUnknownBlockType discardableContentHandler;
- (void)discardContent;
@end

