//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDate.h>

#import <AppAnalytics/AADataType-Protocol.h>

@interface NSDate (AppAnalytics) <AADataType>
- (id)toJsonValueAndReturnError:(id *)arg1;
@end

