//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <StoreKitUI/NSObject-Protocol.h>

@class SKUIMediaPlayer, SKUIMediaPlayerItemStatus;

@protocol SKUIMediaPlayerObserver <NSObject>

@optional
- (void)mediaPlayer:(SKUIMediaPlayer *)arg1 itemStateChanged:(SKUIMediaPlayerItemStatus *)arg2;
@end

