//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FPSandboxingURLWrapper, NSString;

@protocol DLDocumentDownloadsProtocol
- (void)importItemAtURLToDownloads:(FPSandboxingURLWrapper *)arg1 completionHandler:(void (^)(FPSandboxingURLWrapper *, NSError *))arg2;
- (void)upperCaseString:(NSString *)arg1 withReply:(void (^)(NSString *))arg2;
- (void)replacePlaceholder:(FPSandboxingURLWrapper *)arg1 withFinalFileURL:(FPSandboxingURLWrapper *)arg2 completionHandler:(void (^)(FPSandboxingURLWrapper *, NSError *))arg3;
- (void)importPlaceholderAtURLToDownloadsDirectory:(FPSandboxingURLWrapper *)arg1 completionHandler:(void (^)(FPSandboxingURLWrapper *, NSError *))arg2;
@end

