//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol PXVideoOverlayButton
@property(nonatomic) _Bool showAsPause;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (long long)style;
@end

