//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosGraph/PGGraphChange.h>

@class NSSet, NSString, PGGraphPersonNode;

@interface PGGraphPersonChange : PGGraphChange
{
    NSString *_personLocalIdentifier;
    PGGraphPersonNode *_personNode;
    NSSet *_propertyNames;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSSet *propertyNames; // @synthesize propertyNames=_propertyNames;
@property(retain, nonatomic) PGGraphPersonNode *personNode; // @synthesize personNode=_personNode;
@property(readonly, nonatomic) NSString *personLocalIdentifier; // @synthesize personLocalIdentifier=_personLocalIdentifier;
- (id)description;
- (void)mergeChange:(id)arg1;
- (unsigned long long)type;
- (id)initWithPersonLocalIdentifier:(id)arg1 propertyNames:(id)arg2;

@end

