//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class FCFeedDescriptor, NSString, UIColor;

@interface FRFeedImageGenerationOptions : NSObject <NSCopying>
{
    _Bool _punchThroughEffect;
    double _scale;
    FCFeedDescriptor *_feed;
    NSString *_sizeCategory;
    double _cornerRadius;
    NSString *_cachedImagePath;
    UIColor *_feedBackgroundColor;
    struct CGColor *_parentBackgroundColor;
    struct CGSize _size;
}

+ (id)keyForIdentifier:(id)arg1 size:(struct CGSize)arg2 cornerRadius:(double)arg3 punchThroughBanner:(_Bool)arg4 scale:(double)arg5 sizeCategory:(id)arg6 parentBackgroundColor:(struct CGColor *)arg7;
+ (id)pathForIdentifier:(id)arg1 size:(struct CGSize)arg2 cornerRadius:(double)arg3 punchThroughBanner:(_Bool)arg4 scale:(double)arg5 sizeCategory:(id)arg6 parentBackgroundColor:(struct CGColor *)arg7;
+ (id)imageCacheDirectory;
+ (id)imageCacheName;
+ (id)imageCachePrefix;
+ (id)_topicGradientColorsFromHashedIdentifier:(id)arg1;
+ (id)backgroundColorForFeed:(id)arg1;
+ (id)topicColorsMapping;
+ (void)prewarm;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGColor *parentBackgroundColor; // @synthesize parentBackgroundColor=_parentBackgroundColor;
@property(readonly, nonatomic) UIColor *feedBackgroundColor; // @synthesize feedBackgroundColor=_feedBackgroundColor;
@property(readonly, nonatomic) NSString *cachedImagePath; // @synthesize cachedImagePath=_cachedImagePath;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) NSString *sizeCategory; // @synthesize sizeCategory=_sizeCategory;
@property(readonly, nonatomic) _Bool punchThroughEffect; // @synthesize punchThroughEffect=_punchThroughEffect;
@property(readonly, nonatomic) FCFeedDescriptor *feed; // @synthesize feed=_feed;
@property(readonly, nonatomic) double scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFeed:(id)arg1 size:(struct CGSize)arg2 punchThroughEffect:(_Bool)arg3 cornerRadius:(double)arg4 scale:(double)arg5 sizeCategory:(id)arg6 parentBackgroundColor:(struct CGColor *)arg7;

@end

