//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NFLFeedSettings, NSObject, NSSet, NSString;
@protocol OS_dispatch_queue;

@protocol FRFeedLayoutStorage <NSObject>
- (void)pruneBatchesNotTouchedForTimeInterval:(double)arg1 callbackQueue:(NSObject<OS_dispatch_queue> *)arg2 completion:(void (^)(void))arg3;
- (void)saveLaidOutRegions:(NSSet *)arg1 forFeedViewportID:(NSString *)arg2 feedSettings:(NFLFeedSettings *)arg3 callbackQueue:(NSObject<OS_dispatch_queue> *)arg4 completion:(void (^)(void))arg5;
- (void)fetchBatchesForTileInfosWithIDs:(NSSet *)arg1 feedViewportID:(NSString *)arg2 feedSettings:(NFLFeedSettings *)arg3 completion:(void (^)(NSDictionary *))arg4;
@end

