//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUUID;

@interface MRMediaSuggestionRequest : NSObject
{
    _Bool _includeArtwork;
    unsigned long long _maxResults;
    NSUUID *_requestIdentifier;
}

+ (id)defaultRequestWithArtwork;
+ (id)defaultRequest;
- (void).cxx_destruct;
@property(copy, nonatomic) NSUUID *requestIdentifier; // @synthesize requestIdentifier=_requestIdentifier;
@property(nonatomic) _Bool includeArtwork; // @synthesize includeArtwork=_includeArtwork;
@property(nonatomic) unsigned long long maxResults; // @synthesize maxResults=_maxResults;
- (id)_proactiveSuggestion;
- (void)_artworkForIntent:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)_bundleIdentifierIsSystemMediaApplication:(id)arg1;
- (_Bool)_intentIsValidSuggestion:(id)arg1 sourceBundleID:(id)arg2;
- (id)_queryEventsWithPredicate:(id)arg1 offset:(unsigned long long)arg2 error:(id *)arg3;
- (void)performWithPreferences:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)performWithCompletion:(CDUnknownBlockType)arg1;
- (id)description;

@end

