//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "___MKNanoPillTableViewLabelCellAccessibility_super.h"

@interface _MKNanoPillTableViewLabelCellAccessibility : ___MKNanoPillTableViewLabelCellAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityUserTestingChildren;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;

@end

