//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AvatarUI/NSObject-Protocol.h>

@class NSString;

@protocol AVTAvatarAttributeEditorSectionItemPrefetching <NSObject>
@property(readonly, copy, nonatomic) CDUnknownBlockType presetResourcesProvider;
@property(readonly, copy, nonatomic) CDUnknownBlockType thumbnailProvider;
@property(readonly, copy, nonatomic) NSString *prefetchingIdentifier;
@end

