//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class PDFPage, PDFPageView, PDFRenderingProperties, PDFTextInputView, PDFView, UIImage, UIScrollView;

__attribute__((visibility("hidden")))
@interface PDFPageViewControllerPrivate : NSObject
{
    PDFRenderingProperties *renderingProperties;
    PDFView *pdfView;
    struct UIEdgeInsets pageMargins;
    PDFPage *page;
    UIScrollView *scrollView;
    PDFTextInputView *pageViewContainerView;
    PDFPageView *pageView;
    double minScale;
    double maxScale;
    UIImage *backgroundImage;
    int backgroundQuality;
}

- (void).cxx_destruct;

@end

