//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUICore/PXCuratedLibraryActionPerformer.h>

@class PXAssetCollectionReference;

@interface PXCuratedLibraryAssetCollectionActionPerformer : PXCuratedLibraryActionPerformer
{
    PXAssetCollectionReference *_assetCollectionReference;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) PXAssetCollectionReference *assetCollectionReference; // @synthesize assetCollectionReference=_assetCollectionReference;
- (void)performActionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)localizedTitleForUseCase:(unsigned long long)arg1;
- (id)initWithActionType:(id)arg1 viewModel:(id)arg2 assetCollectionReference:(id)arg3;
- (id)initWithActionType:(id)arg1 viewModel:(id)arg2;

@end

