//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface SBRootFolderDockAnimationViewController : UIViewController
{
    long long _forcedInterfaceOrientation;
}

@property(nonatomic) long long forcedInterfaceOrientation; // @synthesize forcedInterfaceOrientation=_forcedInterfaceOrientation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

@end

