//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class OS_dispatch_queue, _TtC8MapsSync19MapsSyncDataSession;

@protocol _TtP8MapsSync21MapsSyncQueryProtocol_
@property(nonatomic, readonly) _Bool isReady;
- (_TtC8MapsSync19MapsSyncDataSession *)getSession;
- (void)sendNotification;
- (void)deleteAllObjectsWithCompletion:(void (^)(NSError *))arg1;
- (void)reloadContentsWithCompletion:(void (^)(NSArray *, NSError *))arg1 queue:(OS_dispatch_queue *)arg2;
@end

