//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TeaUI/TSPlugin.h>

#import <TeaUI/TUPluggableDelegate-Protocol.h>

@interface TSPlugin (TeaUI) <TUPluggableDelegate>
- (void)pluggableViewController:(id)arg1 didChangeSizeTo:(struct CGSize)arg2;
@end

