//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class MISSING_TYPE, _TtC4Maps28PlaceSummaryOutlineCellModel;

@interface _TtC4Maps23PlaceSummaryOutlineCell
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *hostingView;
    MISSING_TYPE *swiftUIView;
}

- (void).cxx_destruct;
- (void)updateDisclosureIndicator;
@property(nonatomic) _Bool hovering;
- (_Bool)isHovering;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, retain) _TtC4Maps28PlaceSummaryOutlineCellModel *viewModel; // @synthesize viewModel;

@end

