//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class AppCoordinator, NSString, PlatformController;

@interface AppStateManager : NSObject
{
    unsigned long long _defaultZoomLevel;
    AppCoordinator *_appCoordinator;
    PlatformController *_platformController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PlatformController *platformController; // @synthesize platformController=_platformController;
@property(nonatomic) __weak AppCoordinator *appCoordinator; // @synthesize appCoordinator=_appCoordinator;
- (id);
- (void)setPPTTestDirectionsPlan:(id)arg1;
- (_Bool)tryMovingStepModeToStepAtIndex:(unsigned long long)arg1 forRouteWithHandle:(id)arg2;
- (void)setDirectionsPlan:(id)arg1 source:(long long)arg2;
- (void)setMapsActivity:(id)arg1 assumedSourceFidelity:(unsigned long long)arg2 source:(long long)arg3;
- (void)resetNonActivityStateForMapView:(id)arg1;
- (id)directionsPlanWithFidelity:(unsigned long long)arg1;
- (id)mapsActivityWithFidelity:(unsigned long long)arg1;
- (void)openCommuteEntry:(id)arg1;
- (void)openTransitIncidents:(id)arg1;
- (void)openMapsSuggestion:(id)arg1;
- (void)openSearchWithQuery:(id)arg1;
- (id)iosChrome;
- (id)initWithPlatformController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

