//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@interface MapsAppTestTileData
{
    double _latitude;
    double _longitude;
    float _zoom;
    int _mapType;
    _Bool _hasRequiredOptions;
}

- (_Bool)runTest;
- (id)initWithApplication:(id)arg1 testName:(id)arg2 options:(id)arg3;

@end

