//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "NSObject-Protocol.h"

@class NavJunctionViewInfo, UIViewController;

@protocol NavContainerLayoutDelegate <NSObject>
- (void)hideJunctionViewIfNeeded;
- (void)showJunctionViewIfNeeded;
- (void)willHideJunctionView;
- (void)willDisplayJunctionViewInfo:(NavJunctionViewInfo *)arg1;
- (_Bool)canDisplayJunctionViewInfo;
- (void)suppressTransitionsOfContainee:(UIViewController *)arg1;
- (void)layoutNavContainer;
@end

