//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class MapsSuggestionsEntry, MapsSuggestionsShortcut, NSArray, NSString;

@interface ShortcutEditSession : NSObject
{
    _Bool _modified;
    _Bool _removing;
    NSArray *_cachedShortcuts;
    _Bool _alreadySaved;
    _Bool _didResignTitleFocus;
    _Bool _saveToFrontOfFavorites;
    MapsSuggestionsShortcut *_shortcut;
    long long _editingModeType;
    CDUnknownBlockType _completionHandler;
    NSArray *_contacts;
    MapsSuggestionsEntry *_originalSuggestionsEntry;
    MapsSuggestionsShortcut *_originalShortcut;
}

+ (void)captureCreateFavoriteAction;
+ (id)editSessionWithShortcut:(id)arg1;
+ (id)addSessionWithShortcut:(id)arg1;
+ (id)editSessionWithSuggestion:(id)arg1;
+ (id)addSessionWithType:(long long)arg1 mapItem:(id)arg2;
+ (id)addSession;
- (void).cxx_destruct;
@property(retain, nonatomic) MapsSuggestionsShortcut *originalShortcut; // @synthesize originalShortcut=_originalShortcut;
@property(retain, nonatomic) MapsSuggestionsEntry *originalSuggestionsEntry; // @synthesize originalSuggestionsEntry=_originalSuggestionsEntry;
@property(retain, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) long long editingModeType; // @synthesize editingModeType=_editingModeType;
@property(nonatomic) _Bool saveToFrontOfFavorites; // @synthesize saveToFrontOfFavorites=_saveToFrontOfFavorites;
@property(nonatomic) _Bool didResignTitleFocus; // @synthesize didResignTitleFocus=_didResignTitleFocus;
@property(nonatomic) _Bool alreadySaved; // @synthesize alreadySaved=_alreadySaved;
@property(retain, nonatomic) MapsSuggestionsShortcut *shortcut; // @synthesize shortcut=_shortcut;
@property(readonly, nonatomic) _Bool editOnlyLocation;
@property(readonly, nonatomic) _Bool editOnlyAddress;
- (void)_touchMapsSuggestionsEngine;
- (id)shortcutManager;
- (void)removeFromShortcutsWithCompletion:(CDUnknownBlockType)arg1;
- (void)saveWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)shortcutsContainItem:(id)arg1;
- (void)removeSharing:(id)arg1;
- (void)addSharing:(id)arg1;
- (void)setAdjustedCoordinate:(struct CLLocationCoordinate2D)arg1;
- (void)setType:(long long)arg1;
- (void)setMapItem:(id)arg1;
- (void)setName:(id)arg1;
@property(readonly, nonatomic) _Bool canChangeType;
@property(readonly, nonatomic) _Bool canBeSaved;
@property(readonly, nonatomic) _Bool isSetupPlaceholder;
@property(readonly, nonatomic) NSString *titleForAddressPicker;
- (id)init;

@end

