//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class FeatureDiscoveryModel, GEOObserverHashTable, NSString, PaymentPolygonCache, TransitPassManager, TransitPayFeatureDiscoveryMetadataStore, TransitPayModelData;
@protocol MapsLocationUpdater, MapsSuggestionsInsights, OS_dispatch_queue, PaymentPolygonFetcher, TransitPayActionDelegate;

@interface TransitPayFeatureDiscoverySource : NSObject
{
    id <MapsSuggestionsInsights> _msgInsights;
    id <PaymentPolygonFetcher> _paymentPolygonFetcher;
    id <MapsLocationUpdater> _locationUpdater;
    TransitPayFeatureDiscoveryMetadataStore *_dataStore;
    TransitPassManager *_passManager;
    TransitPayModelData *_modelData;
    unsigned long long _currentMarketMUID;
    PaymentPolygonCache *_polygonCache;
    FeatureDiscoveryModel *_model;
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _active;
    _Bool hasInitialData;
    _Bool _showFeature;
    GEOObserverHashTable *_observers;
    id <TransitPayActionDelegate> _transitPayActionDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <TransitPayActionDelegate> transitPayActionDelegate; // @synthesize transitPayActionDelegate=_transitPayActionDelegate;
@property(nonatomic) _Bool showFeature; // @synthesize showFeature=_showFeature;
@property(readonly, nonatomic) _Bool hasInitialData; // @synthesize hasInitialData;
@property(nonatomic) _Bool active; // @synthesize active=_active;
- (void)paymentSetupViewController:(id)arg1 didFinishAddingPaymentPasses:(id)arg2 error:(id)arg3;
- (void)fetchTransitMessageFromPassManagerUsingPolygon:(id)arg1;
- (void)transitPayTipDismissedInRoutePlanning:(id)arg1;
- (void)didUpdateLocation:(id)arg1;
- (_Bool)_hasPaymentAndSuggestionsData:(id)arg1 error:(id)arg2;
- (void)_notifyObservers;
- (void)_fetchInsightsWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateFeatureEligibility;
- (void)transitPassManagerDidChange:(id)arg1;
@property(readonly, nonatomic) GEOObserverHashTable *observers; // @synthesize observers=_observers;
- (id)transitPayDiscoveryModel;
- (void)dealloc;
- (id)initWithInsights:(id)arg1 paymentPolygonFetcher:(id)arg2 locationUpdater:(id)arg3 isActive:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

