//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@interface TSTStarRatingRenderer : NSObject
{
}

+ (void)renderRating:(double)arg1 intoContext:(struct CGContext *)arg2 rect:(struct CGRect)arg3 showDots:(_Bool)arg4 color:(struct CGColor *)arg5 useMinimalSpace:(_Bool)arg6;
+ (void)renderRating:(double)arg1 intoContext:(struct CGContext *)arg2 rect:(struct CGRect)arg3 showDots:(_Bool)arg4 color:(struct CGColor *)arg5;
+ (struct CGPath *)p_newStarPath:(double)arg1;

@end

