//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _SWCPatternMatchingResult : NSObject
{
    _Bool _excluded;
    unsigned long long _index;
}

+ (id)new;
@property(readonly, nonatomic, getter=isExcluded) _Bool excluded; // @synthesize excluded=_excluded;
@property(readonly, nonatomic) unsigned long long index; // @synthesize index=_index;
- (id)_initWithIndex:(unsigned long long)arg1 excluded:(_Bool)arg2;
- (id)init;

@end

