//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OfficeImport/CMMapper.h>

@class WDSection;

__attribute__((visibility("hidden")))
@interface WMSectionMapper : CMMapper
{
    WDSection *wdSection;
    float mTopMargin;
    float mLeftMargin;
    _Bool mBreakAtStart;
    _Bool mBreakAtEnd;
    _Bool mIsTitlePage;
}

+ (_Bool)isContentEmpty:(id)arg1;
- (void).cxx_destruct;
- (float)leftMargin;
- (void)setLeftMargin:(float)arg1;
- (float)topMargin;
- (void)setTopMargin:(float)arg1;
- (void)mapAt:(id)arg1 withState:(id)arg2;
- (void)MapSectionStyleAt:(id)arg1;
- (id)initWithWDSection:(id)arg1 breakAtStart:(_Bool)arg2 breakAtEnd:(_Bool)arg3 parent:(id)arg4;
- (void)mapFooterAt:(id)arg1 withState:(id)arg2;
- (void)mapHeaderAt:(id)arg1 withState:(id)arg2;

@end

