//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <VirtualGarage/NSObject-Protocol.h>
#import <VirtualGarage/VGVehicleStateProviding-Protocol.h>

@class NSString, VGVehicle;

@protocol VGExternalAccessory <NSObject, VGVehicleStateProviding>
- (_Bool)isConnectedToAccessoryWithIdentifier:(NSString *)arg1;
- (_Bool)isConnectedToVehicle:(VGVehicle *)arg1;
@end

