//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MediaRemote/MRProtocolMessage.h>

@class MRUpdateActiveSystemEndpointRequest;

@interface MRUpdateActiveSystemEndpointMessage : MRProtocolMessage
{
    MRUpdateActiveSystemEndpointRequest *_request;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) MRUpdateActiveSystemEndpointRequest *request; // @synthesize request=_request;
- (unsigned long long)type;
- (id)initWithRequest:(id)arg1;
- (id)initWithUnderlyingCodableMessage:(id)arg1 error:(id)arg2;

@end

