//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CloudKit/CKRecord.h>

@interface CKRecord (BRCWorkAround)
+ (id)brc_fakeRecordWithErrorMarkerFor20716676;
- (_Bool)brc_isfakeRecordWithErrorMarkerFor20716676;
@end

