//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVMLKit/NSObject-Protocol.h>

@class Protocol, TVTemplateFeaturesManager;

@protocol TVTemplateFeaturesManagerDelegate <NSObject>
- (void)featuresManager:(TVTemplateFeaturesManager *)arg1 currentContextDidChangeForFeature:(Protocol *)arg2;
@end

