//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DirectUploadDatabaseSchema : NSObject
{
}

+ (id)databasePath;
- (void)createSchemaInDatabase:(id)arg1;

@end

