//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSXPCConnection;

@interface DRSystemConnection : NSObject
{
    NSXPCConnection *_connection;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) int systemProcessIdentifier;
- (void)notifySessionDidEnd:(id)arg1;
- (void)notifySessionWillBegin:(id)arg1;
- (id)initWithQueue:(id)arg1;

@end

