//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EventKitUI/EKUIInviteesViewTimeSlotCell.h>

@interface EKUIInviteesViewSomeInviteesCanAttendCell : EKUIInviteesViewTimeSlotCell
{
}

- (id)participantsTextColor;
- (id)timeTextColor;

@end

