//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _MPMediaLibraryEntityPropertyTranslator : NSObject
{
    CDUnknownBlockType _sortTransformer;
    CDUnknownBlockType _valueTransformer;
    shared_ptr_0a0a634d _propertiesToFetchMap;
    shared_ptr_0a0a634d _propertiesToSortMap;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType valueTransformer; // @synthesize valueTransformer=_valueTransformer;
@property(copy, nonatomic) CDUnknownBlockType sortTransformer; // @synthesize sortTransformer=_sortTransformer;
@property(nonatomic) shared_ptr_0a0a634d propertiesToSortMap; // @synthesize propertiesToSortMap=_propertiesToSortMap;
@property(nonatomic) shared_ptr_0a0a634d propertiesToFetchMap; // @synthesize propertiesToFetchMap=_propertiesToFetchMap;

@end

