//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MusicLibrary/ML3StoreItemTrackData.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface MPStoreItemImportTrackData : ML3StoreItemTrackData
{
    NSArray *_importElements;
}

+ (id)_importPropertiesDictFromImportMetadataDict:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *importElements; // @synthesize importElements=_importElements;
- (id)_associatedElementForPropertyDict:(id)arg1;
- (id)parsedStoreItemsImportProperties;
- (id)initWithImportElements:(id)arg1;

@end

