//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppSSOCore/NSObject-Protocol.h>

@class NSData, NSDictionary, NSError, NSHTTPURLResponse, SOAuthorizationCore;

@protocol SOAuthorizationCoreDelegate <NSObject>

@optional
- (void)authorization:(SOAuthorizationCore *)arg1 didCompleteWithError:(NSError *)arg2;
- (void)authorization:(SOAuthorizationCore *)arg1 didCompleteWithHTTPResponse:(NSHTTPURLResponse *)arg2 httpBody:(NSData *)arg3;
- (void)authorization:(SOAuthorizationCore *)arg1 didCompleteWithHTTPAuthorizationHeaders:(NSDictionary *)arg2;
- (void)authorizationDidComplete:(SOAuthorizationCore *)arg1;
- (void)authorizationDidCancel:(SOAuthorizationCore *)arg1;
- (void)authorizationDidNotHandle:(SOAuthorizationCore *)arg1;
@end

