//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDSFoundation/NSSecureCoding-Protocol.h>

@interface IDSEndpointCapabilities : NSObject <NSSecureCoding>
{
    BOOL _supportsKeySharing;
    BOOL _supportsHarmony;
    BOOL _supportsFMDV2;
    BOOL _supportsFMFenceV1;
    BOOL _supportsLocationSharing;
    BOOL _supportsScreenTimeV2;
    BOOL _supportsIncomingFindMyV1;
    BOOL _ecVersion;
    BOOL _isC2KEquipment;
    BOOL _showPeerErrors;
    BOOL _nicknamesVersion;
    BOOL _optionallyReceiveTypingIndicator;
    BOOL _supportsInlineAttachments;
    BOOL _supportsKeepReceipts;
    BOOL _supportsStickersV1;
    BOOL _supportsChatAppsV1;
    BOOL _supportsBubbleEditingV1;
    BOOL _supportsAcknowledgementsV1;
    BOOL _supportsFullScreenMomentsV1;
    BOOL _supportsFullScreenMomentsV2;
    BOOL _supportsFullScreenMomentsV3;
    BOOL _supportsInvisibleInkV1;
    BOOL _supportsImpactEffectsV1;
    BOOL _supportsUpdateAttachmentsV1;
    BOOL _supportsAutoloopVideoV1;
    BOOL _supportsMediaV2;
    BOOL _supportsPhotosExtensionV1;
    BOOL _supportsAudioMessagingV2;
    BOOL _supportsAnimojiV2;
    BOOL _supportsCertifiedDeliveryV1;
    BOOL _supportsOriginalTimestampOrderingV1;
    BOOL _supportsProtobufPayloadDataV2;
    BOOL _supportsHEIFEncoding;
    BOOL _supportsHDRVideo;
    BOOL _prefersSDRVideo;
}

+ (_Bool)supportsSecureCoding;
+ (id)allowedCapabilities;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqualToEndpointCapabilites:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)debugDescription;
- (id)description;
- (long long)valueForCapability:(id)arg1;
- (id)initWithCapabilitiesMap:(id)arg1;

@end

