//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iWorkImport/GQDTCell.h>

@class GQDTComputedFormatSpec;

__attribute__((visibility("hidden")))
@interface GQDTDateCell : GQDTCell
{
    struct __CFDate *mDate;
    GQDTComputedFormatSpec *mComputedFormat;
}

- (struct __CFString *)createStringValue;
- (struct __CFString *)getDateFormat;
- (struct __CFDate *)date;
- (void)dealloc;
- (int)readAttributesForDateCell:(struct _xmlTextReader *)arg1 processor:(id)arg2;

@end

