//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Sharing/NSCopying-Protocol.h>
#import <Sharing/NSSecureCoding-Protocol.h>

@class NSString;

@interface SFNotificationError : NSObject <NSSecureCoding, NSCopying>
{
    NSString *_errorDescription;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

