//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <WorkflowUI/UINavigationControllerDelegate-Protocol.h>
#import <WorkflowUI/WFColorPickerDelegate-Protocol.h>
#import <WorkflowUI/WFGlyphPickerDelegate-Protocol.h>

@class NSString, UIView, WFColorPicker, WFGlyphPicker, WFIconComposePreviewView, WFWorkflow;

@interface WFIconComposeViewController : UIViewController <WFColorPickerDelegate, WFGlyphPickerDelegate, UINavigationControllerDelegate>
{
    WFWorkflow *_workflow;
    WFIconComposePreviewView *_iconView;
    WFColorPicker *_colorPicker;
    WFGlyphPicker *_glyphPicker;
    UIView *_topSeperator;
    UIView *_bottomSeparator;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(nonatomic) __weak UIView *topSeperator; // @synthesize topSeperator=_topSeperator;
@property(nonatomic) __weak WFGlyphPicker *glyphPicker; // @synthesize glyphPicker=_glyphPicker;
@property(nonatomic) __weak WFColorPicker *colorPicker; // @synthesize colorPicker=_colorPicker;
@property(nonatomic) __weak WFIconComposePreviewView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) WFWorkflow *workflow; // @synthesize workflow=_workflow;
- (void)colorPicker:(id)arg1 didSelectColor:(id)arg2;
- (void)glyphPicker:(id)arg1 didSelectGlyphWithCharacter:(unsigned short)arg2;
- (void)updateAccessibilityValue;
- (void)saveIcon:(id)arg1;
- (void)pickedSegment:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

