//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowUI/WFCompactDialogViewController.h>

#import <WorkflowUI/UITextFieldDelegate-Protocol.h>
#import <WorkflowUI/UITextViewDelegate-Protocol.h>

@class NSDateFormatter, NSLayoutConstraint, NSString, UIButton, UILabel, UITextField, UITextView;

@interface WFInputTextDialogViewController : WFCompactDialogViewController <UITextFieldDelegate, UITextViewDelegate>
{
    _Bool _focusImmediatelyOnAppear;
    UITextField *_textField;
    UITextView *_textView;
    UIButton *_clearButton;
    NSString *_placeholder;
    long long _initialInsertionIndex;
    UILabel *_hintLabel;
    NSDateFormatter *_dateFormatter;
    NSString *_localizedIncompleteHintString;
    NSLayoutConstraint *_hintLabelBottomConstraint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *hintLabelBottomConstraint; // @synthesize hintLabelBottomConstraint=_hintLabelBottomConstraint;
@property(copy, nonatomic) NSString *localizedIncompleteHintString; // @synthesize localizedIncompleteHintString=_localizedIncompleteHintString;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) __weak UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(nonatomic) long long initialInsertionIndex; // @synthesize initialInsertionIndex=_initialInsertionIndex;
@property(nonatomic) _Bool focusImmediatelyOnAppear; // @synthesize focusImmediatelyOnAppear=_focusImmediatelyOnAppear;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(nonatomic) __weak UIButton *clearButton; // @synthesize clearButton=_clearButton;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UITextField *textField; // @synthesize textField=_textField;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)updateDateFormattingHint;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateTextViewPlaceholder;
- (void)updateClearButtonVisibility;
- (void)clearText;
- (void)negateText;
- (_Bool)allowsDecimalNumbers;
- (_Bool)useNumberValidation;
- (_Bool)actingAsNumberField;
- (void)viewWillAppear:(_Bool)arg1;
- (void)finishWithInputtedText;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

