//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <WebKit/WKWebView.h>

@interface WKWebView (AdPlatformsCommonUI)
- (_Bool)_webView:(id)arg1 focusShouldStartInputSession:(id)arg2;
- (void)setupInternalProperties;
- (id)remoteObjectProxyWithInterface;
- (void)setRemoteInspectionNameOverride:(id)arg1;
- (void)unregisterExportedObject:(id)arg1 interface:(id)arg2;
- (id)registerExportedObjectInterface:(id)arg1;
@end

