//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface CKConversationListTableView : UITableView
{
}

- (void)setScrollIndicatorInsets:(struct UIEdgeInsets)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1;

@end

