//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OfficeImport/ESDObject.h>

@class CHDChart, NSData;

__attribute__((visibility("hidden")))
@interface EBEscherShape : ESDObject
{
    NSData *mChartData;
    _Bool mShowLegend;
    CHDChart *mChart;
}

- (void)setChart:(id)arg1;
- (id)chart;
- (void)setShowLegend:(_Bool)arg1;
- (_Bool)showLegend;
- (void)setChartData:(id)arg1;
- (id)chartData;
- (void)dealloc;

@end

