//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WebCDMSessionAVContentKeySessionDelegate : NSObject
{
    void *m_parent;
}

- (void)contentKeySessionContentProtectionSessionIdentifierDidChange:(id)arg1;
- (void)contentKeySession:(id)arg1 didProvideContentKeyRequest:(id)arg2;
- (void)invalidate;
- (id)initWithParent:(void *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

