//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SiriUI/SiriUIVideoPlayerViewController.h>

@class SAVCSPlayContent;

@interface SRPlayContentViewController : SiriUIVideoPlayerViewController
{
    SAVCSPlayContent *_playContent;
}

- (void).cxx_destruct;
- (id)initWithPlayContent:(id)arg1;

@end

