//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SANPDecreasePlaybackSpeed.h>

@interface SANPDecreasePlaybackSpeed (AnalyticsContextVending)
- (void)af_addEntriesToAnalyticsContext:(id)arg1;
@end

