//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Metal/NSObject-Protocol.h>

@class MTLComputePipelineDescriptor, MTLRenderPipelineDescriptor, MTLTileRenderPipelineDescriptor, NSString, NSURL;
@protocol MTLDevice;

@protocol MTLBinaryArchive <NSObject>
@property(readonly) id <MTLDevice> device;
@property(copy) NSString *label;
- (_Bool)serializeToURL:(NSURL *)arg1 error:(id *)arg2;
- (_Bool)addTileRenderPipelineFunctionsWithDescriptor:(MTLTileRenderPipelineDescriptor *)arg1 error:(id *)arg2;
- (_Bool)addRenderPipelineFunctionsWithDescriptor:(MTLRenderPipelineDescriptor *)arg1 error:(id *)arg2;
- (_Bool)addComputePipelineFunctionsWithDescriptor:(MTLComputePipelineDescriptor *)arg1 error:(id *)arg2;
@end

