//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Foundation/NSCoder.h>

@interface NSCoder (FTUtils)
- (struct CGRect)fusionTracker_decodeCGRectForKey:(id)arg1;
- (void)fusionTracker_encodeCGRect:(struct CGRect)arg1 forKey:(id)arg2;
- (CDStruct_198678f7)fusionTracker_decodeCMTimeForKey:(id)arg1;
- (void)fusionTracker_encodeCMTime:(CDStruct_198678f7)arg1 forKey:(id)arg2;
@end

