//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__SBUILegibilityLabelAccessibility_super.h"

@interface SBUILegibilityLabelAccessibility : __SBUILegibilityLabelAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (unsigned int)_accessibilityMediaAnalysisOption;
- (unsigned long long)accessibilityTraits;
- (_Bool)isAccessibilityElement;
- (_Bool)_accessibilityViewIsVisible;
- (_Bool)_accessibilityOverridesInvisibility;
- (id)accessibilityLabel;

@end

