//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpriteKit/SKNode.h>

@class NSDictionary, SKAction, SKKeyframeSequence, SKShader, SKTexture, UIColor;

@interface SKEmitterNode : SKNode
{
    SKTexture *_particleTexture;
    struct SKCEmitterNode *_skcEmitterNode;
    SKNode *_target;
    SKKeyframeSequence *_colorSequence;
    SKKeyframeSequence *_colorBlendSequence;
    SKKeyframeSequence *_alphaSequence;
    SKKeyframeSequence *_scaleSequence;
    SKKeyframeSequence *_rotationSequence;
    SKKeyframeSequence *_fieldInfluenceSequence;
    SKKeyframeSequence *_particleSpeedSequence;
    unsigned long long _particleRenderOrder;
}

+ (id)debugHierarchyValueForPropertyWithName:(id)arg1 onObject:(id)arg2 outOptions:(id *)arg3 outError:(id *)arg4;
+ (id)debugHierarchyPropertyDescriptions;
+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long particleRenderOrder; // @synthesize particleRenderOrder=_particleRenderOrder;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forAttributeNamed:(id)arg2;
- (id)valueForAttributeNamed:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) SKShader *shader;
- (void)advanceSimulationTime:(double)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyParticlePropertiesToNode:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMinimumParticleCapacity:(unsigned long long)arg1 minimumPositionBufferCapacity:(unsigned long long)arg2;
- (id)initWithMinimumParticleCapacity:(unsigned long long)arg1;
- (id)init;
- (void)commonInit;
@property(nonatomic) unsigned int fieldBitMask;
- (void)resetSimulation;
@property(nonatomic) unsigned long long numParticlesToEmit;
@property(copy, nonatomic) SKAction *particleAction;
@property(nonatomic) long long particleBlendMode;
@property(retain, nonatomic) SKTexture *particleTexture;
@property(nonatomic) double emissionAngleRange;
@property(nonatomic) double emissionAngle;
@property(nonatomic) double particleSpeedRange;
@property(nonatomic) double particleSpeed;
@property(nonatomic) double particleAlphaSpeed;
@property(nonatomic) double particleAlphaRange;
@property(nonatomic) double particleAlpha;
@property(nonatomic) double particleScaleSpeed;
@property(nonatomic) double particleScaleRange;
@property(nonatomic) double particleScale;
@property(nonatomic) double particleRotationSpeed;
@property(nonatomic) double particleRotationRange;
@property(nonatomic) double particleRotation;
@property(nonatomic) double particleLifetimeRange;
@property(nonatomic) double particleLifetime;
@property(nonatomic) double particleColorBlendFactorSpeed;
@property(nonatomic) double particleColorBlendFactorRange;
@property(nonatomic) double particleColorBlendFactor;
@property(nonatomic) double particleBirthRate;
@property(nonatomic) double yAcceleration;
@property(nonatomic) double xAcceleration;
@property(nonatomic) struct CGVector particlePositionRange;
@property(nonatomic) struct CGPoint particlePosition;
@property(nonatomic) double particleColorAlphaSpeed;
@property(nonatomic) double particleColorBlueSpeed;
@property(nonatomic) double particleColorGreenSpeed;
@property(nonatomic) double particleColorRedSpeed;
@property(nonatomic) double particleColorAlphaRange;
@property(nonatomic) double particleColorBlueRange;
@property(nonatomic) double particleColorGreenRange;
@property(nonatomic) double particleColorRedRange;
@property(retain, nonatomic) UIColor *particleColor;
@property(nonatomic) double particleZPositionRange;
@property(nonatomic) double particleZPosition;
- (void)setZPosition:(double)arg1;
@property(nonatomic) struct CGSize particleSize;
@property(nonatomic) double particleZPositionSpeed;
@property(nonatomic) __weak SKNode *targetNode;
- (double)particleDensity;
- (void)setParticleDensity:(double)arg1;
- (_Bool)usesPointSprites;
- (void)setUsesPointSprites:(_Bool)arg1;
- (_Bool)densityBased;
- (void)setDensityBased:(_Bool)arg1;
- (_Bool)wantsNewParticles;
- (void)setWantsNewParticles:(_Bool)arg1;
- (double)emissionDistanceRange;
- (void)setEmissionDistanceRange:(double)arg1;
- (double)emissionDistance;
- (void)setEmissionDistance:(double)arg1;
- (id)particleRotationSequence;
- (unsigned int)activeParticleCount;
- (void)setParticleRotationSequence:(id)arg1;
@property(retain, nonatomic) SKKeyframeSequence *particleScaleSequence;
@property(retain, nonatomic) SKKeyframeSequence *particleColorSequence;
@property(retain, nonatomic) SKKeyframeSequence *particleColorBlendFactorSequence;
@property(retain, nonatomic) SKKeyframeSequence *particleAlphaSequence;
- (id)description;
- (void)setPhysicsWorld:(id)arg1;
- (id)physicsWorld;
- (_Bool)isEqualToNode:(id)arg1;
- (void)setParticleSpeedSequence:(id)arg1;
- (id)particleSpeedSequence;
- (void)setFieldInfluenceSequence:(id)arg1;
- (id)fieldInfluenceSequence;
- (id)subEmitterNode;
- (void)addSubEmitterNode:(id)arg1;
- (void)_didMakeBackingNode;
- (struct SKCNode *)_makeBackingNode;

// Remaining properties
@property(copy, nonatomic) NSDictionary *attributeValues; // @dynamic attributeValues;

@end

