//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class _TtC3VFX11VFXRenderer;
@protocol MTLDevice;

__attribute__((visibility("hidden")))
@interface ARUICelebrationsRenderer : NSObject
{
    id <MTLDevice> _device;
    _TtC3VFX11VFXRenderer *_renderer;
}

- (void).cxx_destruct;
- (_Bool)_needsCelebrationRenderPassOn:(id)arg1;
- (void)renderCelebrationsForRings:(id)arg1 withCommandBuffer:(id)arg2 intoTexture:(id)arg3 withContext:(id)arg4;
- (id)initWithDevice:(id)arg1 commandQueue:(id)arg2;

@end

