//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ICDocCamImageCache, NSArray;

@interface ICDocCamScanCacheItem : NSObject
{
    ICDocCamImageCache *_imageCache;
    NSArray *_docInfos;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *docInfos; // @synthesize docInfos=_docInfos;
@property(retain, nonatomic) ICDocCamImageCache *imageCache; // @synthesize imageCache=_imageCache;
- (void)doneBuildingCache;
- (void)deleteCacheImages;
- (id)imageForScanDataDelegateIdentifier:(id)arg1;
- (id)docInfoForScanDataDelegate:(id)arg1;
- (id)initWithImageCache:(id)arg1 docInfos:(id)arg2;
- (id)init;

@end

