//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CABackdropLayer, NSString, UIFont, UILabel, UIView;

@interface SBUIPasscodePillButton : UIControl
{
    UILabel *_titleLabel;
    UIView *_pillView;
    UIView *_backdropView;
    CABackdropLayer *_backdropLayer;
    double _unhighlightedAlpha;
    double _highlightedAlpha;
}

- (void).cxx_destruct;
@property(nonatomic) double highlightedAlpha; // @synthesize highlightedAlpha=_highlightedAlpha;
@property(nonatomic) double unhighlightedAlpha; // @synthesize unhighlightedAlpha=_unhighlightedAlpha;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
@property(copy, nonatomic) UIFont *font;
@property(copy, nonatomic) NSString *title;
- (id)initWithFrame:(struct CGRect)arg1;

@end

