//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (CalClassAdditions)
+ (id)nonRetainingArray;
- (void)CalFilterUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeAllObjectsWithClass:(Class)arg1;
@end

