//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppStoreDaemon/NSCopying-Protocol.h>
#import <AppStoreDaemon/NSSecureCoding-Protocol.h>

@class NSString;

@interface ASDProgress : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_bundleID;
    long long _completedUnitCount;
    long long _totalUnitCount;
}

+ (_Bool)supportsSecureCoding;
@property long long totalUnitCount; // @synthesize totalUnitCount=_totalUnitCount;
@property long long completedUnitCount; // @synthesize completedUnitCount=_completedUnitCount;
@property(retain) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

