//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IdleTimerServices/NSObject-Protocol.h>

@class BSProcessHandle, ITIdleTimerConfiguration, NSString;

@protocol ITIdleTimerStateServerDelegate <NSObject>
- (void)clientDidDisconnect:(BSProcessHandle *)arg1;
- (void)removeIdleTimerConfigurationFromProcess:(BSProcessHandle *)arg1 forReason:(NSString *)arg2;
- (_Bool)addIdleTimerConfiguration:(ITIdleTimerConfiguration *)arg1 fromProcess:(BSProcessHandle *)arg2 forReason:(NSString *)arg3;
- (_Bool)isIdleTimerServiceAvailable;
@end

