//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ContentKit/DCMapsURLGenerator.h>

__attribute__((visibility("hidden")))
@interface DCBaiduMapsURLGenerator : DCMapsURLGenerator
{
}

- (id)directionsMode;
- (void)populateQueryDictionary;
- (id)path;
- (id)host;
- (id)scheme;

@end

