//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableIndexSet;
@protocol MTLBuffer;

__attribute__((visibility("hidden")))
@interface SCNFixedSizePage : NSObject
{
    id <MTLBuffer> _buffer;
    unsigned long long _elementSize;
    NSMutableIndexSet *_freeIndices;
}

@property(readonly, nonatomic) id <MTLBuffer> buffer; // @synthesize buffer=_buffer;
- (id)newSubBuffer;
- (void)deallocateElementAtOffset:(unsigned long long)arg1;
- (unsigned long long)_allocateElement;
- (_Bool)hasFreeElementsLeft;
- (_Bool)isFull;
- (void)dealloc;
- (id)initWithBuffer:(id)arg1 elementSize:(unsigned long long)arg2;

@end

