//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSUUID;
@protocol CATCancelable;

__attribute__((visibility("hidden")))
@interface CATIDSServiceConnectionInvitationRequest : NSObject
{
    NSUUID *_invitationIdentifier;
    NSString *_appleID;
    id <CATCancelable> _networkPowerAssertion;
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(readonly, nonatomic) id <CATCancelable> networkPowerAssertion; // @synthesize networkPowerAssertion=_networkPowerAssertion;
@property(readonly, copy, nonatomic) NSString *appleID; // @synthesize appleID=_appleID;
@property(readonly, nonatomic) NSUUID *invitationIdentifier; // @synthesize invitationIdentifier=_invitationIdentifier;
- (id)initWithInvitationIdentifier:(id)arg1 appleID:(id)arg2 networkPowerAssertion:(id)arg3 userInfo:(id)arg4;

@end

