//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <PersonalizationPortrait/MLFeatureProvider-Protocol.h>
#import <PersonalizationPortrait/NSCopying-Protocol.h>
#import <PersonalizationPortrait/NSMutableCopying-Protocol.h>
#import <PersonalizationPortrait/NSSecureCoding-Protocol.h>
#import <PersonalizationPortrait/PPRecord-Protocol.h>

@class NSArray, NSSet, NSString, NSUUID, PPLocation, PPSource;

@interface PPLocationRecord : NSObject <PPRecord, NSCopying, NSMutableCopying, NSSecureCoding, MLFeatureProvider>
{
    NSUUID *_uuid;
    PPLocation *_location;
    PPSource *_source;
    unsigned char _algorithm;
    float _initialScore;
    float _decayRate;
    NSArray *_contextualNamedEntities;
    NSString *_extractionOsBuild;
    unsigned int _extractionAssetVersion;
    BOOL _bucketizedSentimentScore;
    _Bool _isAmbiguous;
}

+ (id)algorithmForName:(id)arg1;
+ (id)describeAlgorithm:(unsigned short)arg1;
+ (_Bool)supportsSecureCoding;
+ (id)sharedAmbiguousRecord;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isAmbiguous; // @synthesize isAmbiguous=_isAmbiguous;
@property(readonly, nonatomic) NSString *extractionOsBuild; // @synthesize extractionOsBuild=_extractionOsBuild;
@property(readonly, nonatomic) NSArray *contextualNamedEntities; // @synthesize contextualNamedEntities=_contextualNamedEntities;
- (id)featureValueForName:(id)arg1;
@property(readonly, nonatomic) NSSet *featureNames;
@property(readonly, nonatomic) unsigned int extractionAssetVersion;
@property(readonly, nonatomic) double sentimentScore;
@property(readonly, nonatomic) double decayRate;
@property(readonly, nonatomic) double initialScore;
@property(readonly, nonatomic) unsigned short algorithm;
@property(readonly, nonatomic) PPSource *source;
@property(readonly, nonatomic) PPLocation *location;
@property(readonly, nonatomic) NSUUID *uuid;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToLocationRecord:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)supplementFieldsWithClusterID:(id)arg1 locationWithLatLong:(id)arg2;
- (id)initAmbiguousRecord;
- (id)init;
- (id)init_;

@end

