//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PhotosUI/PUValueFilter.h>

@interface PUThresholdCrossingCountValueFilter : PUValueFilter
{
    long long _crossingCount;
    double _thresholdValue;
    long long _maximumCrossingCount;
}

@property(nonatomic) long long maximumCrossingCount; // @synthesize maximumCrossingCount=_maximumCrossingCount;
@property(nonatomic) double thresholdValue; // @synthesize thresholdValue=_thresholdValue;
- (double)updatedValue:(double)arg1 withTargetValue:(double)arg2;

@end

