//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/NSCopying-Protocol.h>
#import <HealthDaemon/NSSecureCoding-Protocol.h>

@class NSNumber, NSUUID;

@interface HDContributorReference : NSObject <NSSecureCoding, NSCopying>
{
    long long _contributorType;
    NSNumber *_persistentID;
    NSUUID *_UUID;
}

+ (_Bool)supportsSecureCoding;
+ (id)contributorReferenceForOtherUserWithUUID:(id)arg1;
+ (id)contributorReferenceForPrimaryUser;
+ (id)contributorReferenceForNoContributor;
+ (id)contributorReferenceForPersistentID:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSUUID *UUID; // @synthesize UUID=_UUID;
@property(readonly, copy, nonatomic) NSNumber *persistentID; // @synthesize persistentID=_persistentID;
@property(readonly, nonatomic) long long contributorType; // @synthesize contributorType=_contributorType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)_initWithContributorType:(long long)arg1 persistentID:(id)arg2 uuid:(id)arg3;

@end

