//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <PhotosUICore/NSObject-Protocol.h>

@class PXGItemsLayout;

@protocol PXGItemsLayoutDelegate <NSObject>

@optional
- (CDStruct_c2259bfa)itemsLayout:(PXGItemsLayout *)arg1 cornerRadiusForItem:(long long)arg2;
- (struct CGSize)itemsLayout:(PXGItemsLayout *)arg1 insetForItem:(long long)arg2;
- (struct CGSize)itemsLayout:(PXGItemsLayout *)arg1 marginForItem:(long long)arg2;
- (double)itemsLayout:(PXGItemsLayout *)arg1 rotationAngleForItem:(long long)arg2;
- (void)itemsLayout:(PXGItemsLayout *)arg1 updateTagsInSpriteInfos:(CDStruct_9d1ebe49 *)arg2 forItemsInRange:(struct _NSRange)arg3;
- (unsigned int)itemsLayout:(PXGItemsLayout *)arg1 effectIdForItem:(long long)arg2;
- (struct CGRect)itemsLayout:(PXGItemsLayout *)arg1 bestCropRectForItem:(long long)arg2 withAspectRatio:(double)arg3;
- (double)itemsLayout:(PXGItemsLayout *)arg1 aspectRatioForItem:(long long)arg2;
- (id)itemsLayout:(PXGItemsLayout *)arg1 objectReferenceForAccessoryItem:(long long)arg2;
- (id)itemsLayout:(PXGItemsLayout *)arg1 objectReferenceForItem:(long long)arg2;
- (long long)itemsLayout:(PXGItemsLayout *)arg1 itemForObjectReference:(id)arg2 options:(unsigned long long)arg3;
@end

