//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <PhotosUICore/NSObject-Protocol.h>

@class NSArray, NSDate, NSError, NSProgress, PHPickerConfiguration, PXAssetsDataSourceManager;
@protocol PXPresentationEnvironment;

@protocol PXSharedLibrarySourceLibraryInfo <NSObject>
@property(readonly, nonatomic) _Bool isCloudPhotoLibraryInitialSyncCompleted;
@property(readonly, nonatomic) _Bool isCloudPhotoLibraryEnabled;
@property(readonly, nonatomic) _Bool isSystemPhotoLibrary;
- (_Bool)isFailedToURLFetchOwnedSharedLibraryError:(NSError *)arg1;
- (_Bool)isSharedLibraryNotFoundError:(NSError *)arg1;
- (_Bool)presentCustomInformationForError:(NSError *)arg1 customTitle:(id *)arg2 customMessage:(id *)arg3;
- (void)createPreviewWithEmailAddresses:(NSArray *)arg1 phoneNumbers:(NSArray *)arg2 autoSharePolicy:(long long)arg3 startDate:(NSDate *)arg4 personUUIDs:(NSArray *)arg5 progress:(NSProgress *)arg6 presentationEnvironment:(id <PXPresentationEnvironment>)arg7 withCompletionHandler:(void (^)(id <PXSharedLibrary>, NSError *))arg8;
- (void)createSharedLibraryWithEmailAddresses:(NSArray *)arg1 phoneNumbers:(NSArray *)arg2 autoSharePolicy:(long long)arg3 startDate:(NSDate *)arg4 personUUIDs:(NSArray *)arg5 progress:(NSProgress *)arg6 presentationEnvironment:(id <PXPresentationEnvironment>)arg7 withCompletionHandler:(void (^)(id <PXSharedLibrary>, NSError *))arg8;
- (CDStruct_14f26992)assetsCountsForAssetLocalIdentifiers:(NSArray *)arg1;
- (PHPickerConfiguration *)pickerConfiguration;
- (PXAssetsDataSourceManager *)createDataSourceManager;
- (void)fetchEstimatedAssetsCountsForExit:(_Bool)arg1 imageCount:(unsigned long long *)arg2 videoCount:(unsigned long long *)arg3 audioCount:(unsigned long long *)arg4 itemCount:(unsigned long long *)arg5;
- (void)fetchEstimatedAssetsCountsShareEverythingPolicyWithCompletion:(void (^)(struct))arg1;
- (void)fetchEstimatedAssetsCountsForStartDate:(NSDate *)arg1 personUUIDs:(NSArray *)arg2 completion:(void (^)(struct))arg3;
- (void)fetchSuggestedStartDateForPersonUUIDs:(NSArray *)arg1 completion:(void (^)(NSDate *))arg2;
@end

