//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SQLiteMemoryEntity.h"

@class NSArray, NSDictionary, NSNumber, NSString, NSURL;

@interface ODRAssetPack : SQLiteMemoryEntity
{
}

+ (id)defaultProperties;
+ (Class)databaseEntityClass;
+ (id)_metadataFromURL:(id)arg1;
+ (id)_metadataURLForURL:(id)arg1;
+ (_Bool)writeMetadata:(id)arg1 forAssetPackAtURL:(id)arg2;
+ (id)legacyPathPrefixForApplication:(id)arg1;
+ (_Bool)isOnDeviceAtURL:(id)arg1 withValidMetadata:(id)arg2;
+ (_Bool)deleteAssetPackOnDiskAtURL:(id)arg1;
- (void)removeDownloadRequestUUID:(id)arg1;
- (_Bool)isOnDevice;
- (id)integrityHashingDictionary;
- (id)description;
- (void)addDownloadRequestUUID:(id)arg1;
@property(copy, nonatomic) NSURL *URL;
@property(nonatomic) long long purgeReason;
@property(nonatomic) _Bool purgeable;
@property(nonatomic) long long pinCount;
@property(retain, nonatomic) NSURL *localURL;
- (void)setLastUsedDate:(id)arg1;
@property(nonatomic) double effectivePreservationPriority;
@property(nonatomic) _Bool effectiveAlwaysPreserve;
@property(copy, nonatomic) NSArray *downloadRequestUUIDs;
@property(copy, nonatomic) NSNumber *downloadIdentifier;
@property(readonly, nonatomic) NSNumber *uncompressedSize;
@property(readonly, nonatomic) NSString *SHA;
@property(readonly, nonatomic) NSDictionary *primaryContentHash;
@property(readonly, nonatomic) NSString *MD5;
@property(readonly, nonatomic, getter=isStreamable) NSNumber *streamable;
@property(readonly, nonatomic) NSArray *knownContentHashes;
@property(readonly, nonatomic) NSArray *hashes;
@property(readonly, nonatomic) NSNumber *fileSize;
@property(readonly, nonatomic) NSNumber *downloadPriority;
@property(readonly, nonatomic) NSNumber *chunkSize;
@property(readonly, nonatomic) NSString *bundleKey;
@property(readonly, nonatomic) NSString *applicationBundleID;
- (id)initWithDictionary:(id)arg1 andBundleID:(id)arg2;
- (unsigned long long)tagStatus;
- (id)humanReadablePurgeReason;
- (double)downloadPercentageComplete;
- (id)_suggestedLocalFilename;
- (_Bool)writeMetadata;
- (id)suggestedDestinationPathWithStorageID:(id)arg1;
- (_Bool)purgeWithReason:(long long)arg1;
- (id)contentHash;

@end

