//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NetworkExtension/NEExtensionProviderProtocol-Protocol.h>

@protocol NEExtensionTunnelProviderProtocol <NEExtensionProviderProtocol>
- (void)establishIPCWithCompletionHandler:(void (^)(NSXPCListenerEndpoint *))arg1;
@end

