//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView;

@interface AVTAvatarLibraryCollectionViewCell : UICollectionViewCell
{
    UIImageView *_imageView;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)updateAvatarImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

