//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MPAVController, MPAVItem, SKUIMediaPlayerItemStatus;

__attribute__((visibility("hidden")))
@interface SKUIMediaPlayer : NSObject
{
    _Bool _playing;
    float _rate;
    SKUIMediaPlayerItemStatus *_playerItem;
    MPAVController *_player;
    MPAVItem *_currentItem;
    id _periodicTimeObserver;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool playing; // @synthesize playing=_playing;
@property(retain, nonatomic) id periodicTimeObserver; // @synthesize periodicTimeObserver=_periodicTimeObserver;
@property(nonatomic) float rate; // @synthesize rate=_rate;
@property(nonatomic) __weak MPAVItem *currentItem; // @synthesize currentItem=_currentItem;
@property(nonatomic) __weak MPAVController *player; // @synthesize player=_player;
@property(retain, nonatomic) SKUIMediaPlayerItemStatus *playerItem; // @synthesize playerItem=_playerItem;

@end

