//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "NSObject-Protocol.h"

@class BSAction, NSString, NSURL, UIColor, UIView;
@protocol SBUISystemApertureAccessoryView, UIViewControllerTransitionCoordinator;

@protocol SBUISystemApertureElement <NSObject>
@property(nonatomic, readonly) long long maximumLayoutMode;
@property(nonatomic, readonly) long long preferredLayoutMode;
@property(nonatomic, readonly) long long contentRole;
@property(nonatomic) long long activeLayoutMode;

@optional
@property(nonatomic) _Bool canRequestAlertingAssertion;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *detachedMinimalView;
@property(nonatomic) unsigned long long minimalViewLayoutAxis;
@property(nonatomic, readonly) UIColor *keyColor;
@property(nonatomic, readonly) unsigned long long presentationBehaviors;
@property(nonatomic, readonly) long long preferredCustomLayout;
@property(nonatomic, readonly) struct CGSize preferredCustomAspectRatio;
@property(nonatomic, readonly) unsigned long long statusBarStyleOverridesToSuppress;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *minimalView;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *trailingView;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *leadingView;
@property(nonatomic, readonly) long long minimumLayoutMode;
@property(nonatomic, readonly) _Bool preventsAutomaticDismissal;
@property(nonatomic, readonly) _Bool preventsInteractiveDismissal;
@property(nonatomic, readonly) BSAction *launchAction;
@property(nonatomic, readonly) NSURL *launchURL;
@property(nonatomic, readonly) NSString *associatedScenePersistenceIdentifier;
@property(nonatomic, readonly) NSString *associatedAppBundleIdentifier;
@property(nonatomic, readonly) NSString *elementIdentifier;
@property(nonatomic, readonly) double preferredHeightForBottomSafeArea;
- (void)viewWillLayoutSubviewsWithTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)arg1;
@end

