//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface SBHomeScreenMaterialView : UIView
{
    UIView *_backgroundView;
    UIView *_whiteTintView;
    UIImageView *_xColorBurnView;
    UIImageView *_xPlusDView;
    UIView *_highlightView;
    struct CGPoint _wallpaperRelativeCenter;
    _Bool _highlighted;
    struct UIEdgeInsets _backgroundInsets;
}

+ (id)colorBurnContentImageForImage:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets backgroundInsets; // @synthesize backgroundInsets=_backgroundInsets;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @synthesize highlighted=_highlighted;
- (void)_addHighlightViewIfNecessary;
- (void)layoutSubviews;
@property(nonatomic) double brightness;
- (void)setLegibilityStyle:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 backgroundView:(id)arg2 foregroundImage:(id)arg3;

@end

