//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <HomeKitDaemon/MKFModel-Protocol.h>
#import <HomeKitDaemon/MKFRoomPublicExtensions-Protocol.h>

@class MKFRoomDatabaseID, NSArray, NSDate, NSString, NSUUID;
@protocol MKFApplicationData, MKFHome;

@protocol MKFRoom <MKFModel, MKFRoomPublicExtensions>
@property(readonly, copy, nonatomic) MKFRoomDatabaseID *databaseID;
@property(readonly, retain, nonatomic) NSArray *zones;
@property(readonly, retain, nonatomic) id <MKFHome> homeDefault;
@property(readonly, retain, nonatomic) id <MKFHome> home;
@property(retain, nonatomic) id <MKFApplicationData> applicationData;
@property(readonly, retain, nonatomic) NSArray *accessories;
@property(copy, nonatomic) NSDate *writerTimestamp;
@property(copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSUUID *modelID;
- (id <MKFApplicationData>)materializeOrCreateApplicationDataRelation:(_Bool *)arg1;
@end

