//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/___UIDatePickerCalendarTimeViewAccessibility_super.h>

@interface _UIDatePickerCalendarTimeViewAccessibility : ___UIDatePickerCalendarTimeViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_axHideTimeLabel;
- (void)_setupViewHierarchy;
- (void)_accessibilityLoadAccessibilityInformation;
- (_Bool)accessibilityPerformEscape;
- (id)accessibilityLabel;
- (long long)accessibilityContainerType;

@end

