//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariServices/NSObject-Protocol.h>

@protocol _WKErrorRecoveryAttempting <NSObject>
- (_Bool)attemptRecovery;
@end

