//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__AVButtonAccessibility_super.h"

@interface AVButtonAccessibility : __AVButtonAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_axSetLabelForPlayPauseButton;
- (void)setHasAlternateAppearance:(_Bool)arg1;
- (void)_accessibilityLoadAccessibilityInformation;

@end

