//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NewsUI/NSObject-Protocol.h>

@class NSString, NSURL;

@protocol SXEmbedType <NSObject>
@property(readonly, nonatomic) unsigned long long autoPlayMedia;
@property(readonly, nonatomic) NSString *javaScript;
@property(readonly, nonatomic) NSString *enclosingHTML;
@property(readonly, nonatomic) NSURL *baseURL;
@property(readonly, nonatomic) double maximumWidth;
@property(readonly, nonatomic) double minimumWidth;
@end

