//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HMFoundation/HMFObject.h>

@class HMFNetAddressInternal, NSString;

@interface HMFNetAddress : HMFObject
{
    HMFNetAddressInternal *_internal;
}

+ (id)localAddress;
- (void).cxx_destruct;
@property(readonly, nonatomic) HMFNetAddressInternal *internal; // @synthesize internal=_internal;
- (id)dataUsingEncoding:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *addressString;
@property(readonly, nonatomic) unsigned long long addressFamily;
- (id)attributeDescriptions;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithHostname:(id)arg1;
- (id)initWithSocketAddress:(const struct sockaddr *)arg1;
- (id)init;

@end

