//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <ActionKit/NSCoding-Protocol.h>
#import <ActionKit/NSCopying-Protocol.h>
#import <ActionKit/WFSerializableContent-Protocol.h>

@class ENLinkedNotebookRef, NSString;

@interface ENNoteRef : NSObject <WFSerializableContent, NSCoding, NSCopying>
{
    long long _type;
    NSString *_guid;
    ENLinkedNotebookRef *_linkedNotebook;
}

+ (id)noteRefFromData:(id)arg1;
+ (id)objectWithWFSerializedRepresentation:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) ENLinkedNotebookRef *linkedNotebook; // @synthesize linkedNotebook=_linkedNotebook;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)asData;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)wfSerializedRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

