//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "NSSetChange.h"

__attribute__((visibility("hidden")))
@interface NSConcreteSetChange : NSSetChange
{
    unsigned long long _changeType;
    id _value;
}

- (id)value;
- (unsigned long long)changeType;
- (void)dealloc;
- (id)initWithType:(unsigned long long)arg1 object:(id)arg2;

@end

