//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <HomeKitDaemonLegacy/NSObject-Protocol.h>

@class NSData, NSString;
@protocol HMDDataStreamSocketDelegate;

@protocol HMDDataStreamSocket <NSObject>
@property unsigned long long trafficClass;
@property(readonly) NSString *applicationProtocolName;
@property(readonly, getter=isClosed) _Bool closed;
@property(readonly, getter=isClosing) _Bool closing;
@property __weak id <HMDDataStreamSocketDelegate> delegate;
- (NSData *)readData;
- (void)writeData:(NSData *)arg1 completion:(void (^)(NSError *))arg2;
- (_Bool)writeData:(NSData *)arg1 error:(id *)arg2;
- (void)close;
@end

