//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SRCompactViewControllerContentTesterState.h"

@interface SRCompactViewControllerMutableContentTesterState : SRCompactViewControllerContentTesterState
{
}

@property(nonatomic) _Bool keyboardHasContent; // @dynamic keyboardHasContent;
@property(nonatomic) _Bool siriViewControllerIsEditing; // @dynamic siriViewControllerIsEditing;
@property(nonatomic) _Bool compactViewHasContent; // @dynamic compactViewHasContent;
@property(nonatomic) _Bool editableUtteranceViewHasContent; // @dynamic editableUtteranceViewHasContent;
@property(nonatomic) _Bool multiLevelViewHasContent; // @dynamic multiLevelViewHasContent;
@property(nonatomic) _Bool navigationBarHasContent; // @dynamic navigationBarHasContent;
@property(nonatomic) long long navigationStackSize; // @dynamic navigationStackSize;
@property(nonatomic) _Bool navigationStackIsPopping; // @dynamic navigationStackIsPopping;
@property(nonatomic) _Bool deviceIsPad; // @dynamic deviceIsPad;
- (id)init;

@end

