//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKitLegacy/___UICompatibilityTextViewAccessibility_super.h>

@interface _UICompatibilityTextViewAccessibility : ___UICompatibilityTextViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (unsigned long long)accessibilityTraits;
- (void)_accessibilitySetSelectedTextRange:(struct _NSRange)arg1;
- (id)_accessibilityAttributedValueForRange:(struct _NSRange *)arg1;
- (id)_accessibilityDataDetectorScheme:(struct CGPoint)arg1;

@end

