//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Preferences/PSSliderTableCell.h>

@class UILabel;

@interface AXUISettingsLeftRightSliderCell : PSSliderTableCell
{
    UILabel *_leftLabel;
    UILabel *_rightLabel;
}

- (void).cxx_destruct;
- (id)newControl;
- (id)labelColor;
- (void)setAccessibilityLabel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (_Bool)_accessibilityIgnoreInternalLabels;

@end

