//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FCCardStyleProviding, FCHeadlineProviding, FRFeedHeadlineViewStyleType;

@protocol FRFeedHeadlineViewStyleFactoryType <NSObject>
- (id <FRFeedHeadlineViewStyleType>)styleForHeadline:(id <FCHeadlineProviding>)arg1 userInterfaceStyle:(long long)arg2;

@optional
- (id <FRFeedHeadlineViewStyleType>)styleForHeadline:(id <FCHeadlineProviding>)arg1 userInterfaceStyle:(long long)arg2 cardStyle:(id <FCCardStyleProviding>)arg3 darkCardStyle:(id <FCCardStyleProviding>)arg4;
@end

