//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FCPurchase, NSString;

@interface FRPrefetchedPurchase : NSObject
{
    unsigned long long _prefetchPurchaseStatus;
    FCPurchase *_purchase;
    NSString *_title;
    NSString *_subtitle;
    NSString *_tagID;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *tagID; // @synthesize tagID=_tagID;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) FCPurchase *purchase; // @synthesize purchase=_purchase;
@property(nonatomic) unsigned long long prefetchPurchaseStatus; // @synthesize prefetchPurchaseStatus=_prefetchPurchaseStatus;

@end

