//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface VCPCompactResult : NSObject
{
    float _score;
    CDStruct_e83c9415 _timerange;
}

@property float score; // @synthesize score=_score;
@property CDStruct_e83c9415 timerange; // @synthesize timerange=_timerange;
- (id)initWithTimerange:(CDStruct_e83c9415)arg1 andScore:(float)arg2;

@end

