//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AVKit/NSObject-Protocol.h>

@class AVPlaybackContentContainerView, AVPlaybackContentTransitioningView;

@protocol AVPlaybackContentTransitioningViewDelegate <NSObject>
- (void)contentTransitioningViewDidChangeTransitionStatus:(AVPlaybackContentTransitioningView *)arg1 oldState:(long long)arg2 oldTransitionDirection:(long long)arg3 oldProgress:(double)arg4;
- (AVPlaybackContentContainerView *)contentTransitioningPlayerContentViewForTransition:(AVPlaybackContentTransitioningView *)arg1;
- (_Bool)contentTransitioningView:(AVPlaybackContentTransitioningView *)arg1 shouldBeginTransitionWithDirection:(long long)arg2;
- (_Bool)contentTransitioningViewShouldBeginDragging:(AVPlaybackContentTransitioningView *)arg1 locationInView:(struct CGPoint)arg2;
@end

