//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ITMLKit/IKViewElement.h>

@class NSSet, VUIViewElementDataSource;

@interface IKViewElement (VideosUI)
+ (id)_vui_updateEventDescriptorWithType:(unsigned long long)arg1;
- (void)_parseElementIfNecessary;
- (id)vui_imageURL;
- (id)vui_description;
- (id)vui_title;
@property(readonly, copy, nonatomic) NSSet *vui_updateEventDescriptors;
@property(readonly, nonatomic) VUIViewElementDataSource *vui_DataSource;
- (id)_backgroundImageProxyFromImageElement:(id)arg1;
- (id)mediaInfoForEvent:(id)arg1 playbackContext:(unsigned long long)arg2 includingVideo:(_Bool)arg3;
@end

