//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDSFoundation/IDSMPIdentity.h>

@class IDSMPPublicAccountIdentity;

@interface IDSMPPublicAccountIdentityCluster : IDSMPIdentity
{
}

- (_Bool)isParentOfCluster:(id)arg1;
- (id)dataRepresentationWithError:(id *)arg1;
@property(readonly, nonatomic) IDSMPPublicAccountIdentity *publicAccountIdentity;

@end

