//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariShared/NSObject-Protocol.h>

@class NSArray, NSCountedSet;
@protocol WBSHistoryLoader;

@protocol WBSHistoryLoaderDelegate <NSObject>
- (void)historyLoaderDidFinishLoading:(id <WBSHistoryLoader>)arg1;
- (void)historyLoader:(id <WBSHistoryLoader>)arg1 didLoadItems:(NSArray *)arg2 discardedItems:(NSArray *)arg3 stringsForUserTypeDomainExpansion:(NSCountedSet *)arg4;
@end

