//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Intents/JSExport-Protocol.h>
#import <Intents/NSObject-Protocol.h>

@class NSString;

@protocol INSetBinarySettingIntentResponseExport <NSObject, JSExport>
@property(copy, nonatomic) NSString *errorDetail;
@property(nonatomic) long long updatedValue;
@property(nonatomic) long long oldValue;
@property(readonly, nonatomic) long long code;
@end

