//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOPDDatasetABStatus, GEOTransitRouteUpdateConfiguration, NSData, NSMutableArray, NSString, PBDataReader, PBUnknownFields;

@interface GEOTransitRouteUpdateResponse : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    struct GEOTimepoint _timepointUsed;
    GEOPDDatasetABStatus *_datasetAbStatus;
    NSData *_responseId;
    GEOTransitRouteUpdateConfiguration *_routeUpdateConfiguration;
    NSMutableArray *_routeUpdates;
    NSString *_transitDataVersion;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    struct os_unfair_lock_s _readerLock;
    int _status;
    struct {
        unsigned int has_timepointUsed:1;
        unsigned int has_status:1;
        unsigned int read_unknownFields:1;
        unsigned int read_datasetAbStatus:1;
        unsigned int read_responseId:1;
        unsigned int read_routeUpdateConfiguration:1;
        unsigned int read_routeUpdates:1;
        unsigned int read_transitDataVersion:1;
        unsigned int wrote_anyField:1;
    } _flags;
}

+ (_Bool)isValid:(id)arg1;
+ (Class)routeUpdateType;
- (void).cxx_destruct;
- (void)clearUnknownFields:(_Bool)arg1;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (void)readAll:(_Bool)arg1;
- (id)initWithJSON:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)jsonRepresentation;
- (id)dictionaryRepresentation;
- (id)description;
@property(retain, nonatomic) NSString *transitDataVersion;
@property(readonly, nonatomic) _Bool hasTransitDataVersion;
@property(nonatomic) _Bool hasTimepointUsed;
@property(nonatomic) struct GEOTimepoint timepointUsed;
@property(retain, nonatomic) GEOTransitRouteUpdateConfiguration *routeUpdateConfiguration;
@property(readonly, nonatomic) _Bool hasRouteUpdateConfiguration;
@property(retain, nonatomic) GEOPDDatasetABStatus *datasetAbStatus;
@property(readonly, nonatomic) _Bool hasDatasetAbStatus;
- (int)StringAsStatus:(id)arg1;
- (id)statusAsString:(int)arg1;
@property(nonatomic) _Bool hasStatus;
@property(nonatomic) int status;
@property(retain, nonatomic) NSData *responseId;
@property(readonly, nonatomic) _Bool hasResponseId;
- (id)routeUpdateAtIndex:(unsigned long long)arg1;
- (unsigned long long)routeUpdatesCount;
- (void)addRouteUpdate:(id)arg1;
- (void)clearRouteUpdates;
@property(retain, nonatomic) NSMutableArray *routeUpdates;
- (id)initWithData:(id)arg1;
- (id)init;

@end

