//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ActionKit/BOXRequestWithSharedLinkHeader.h>

@class NSArray;

@interface BOXItemArrayRequest : BOXRequestWithSharedLinkHeader
{
    _Bool _requestAllItemFields;
    NSArray *_fieldsToExclude;
}

@property(retain, nonatomic) NSArray *fieldsToExclude; // @synthesize fieldsToExclude=_fieldsToExclude;
@property(nonatomic) _Bool requestAllItemFields; // @synthesize requestAllItemFields=_requestAllItemFields;
- (void).cxx_destruct;
- (struct NSString *)itemTypeForSharedLink;
- (id)itemIDForSharedLink;
- (void)performRequestWithCached:(CDUnknownBlockType)arg1 refreshed:(CDUnknownBlockType)arg2;
- (void)performRequestWithCompletion:(CDUnknownBlockType)arg1;

@end

