//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGAffineTransform {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
};

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct UIEdgeInsets {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    double _field1;
    double _field2;
    double _field3;
} CDStruct_39925896;

typedef struct {
    long long _field1;
    int _field2;
    unsigned int _field3;
    long long _field4;
} CDStruct_198678f7;

typedef struct {
    CDStruct_39925896 _field1;
    CDStruct_39925896 _field2;
    CDStruct_39925896 _field3;
    CDStruct_39925896 _field4;
} CDStruct_3ea48505;

typedef struct {
    CDStruct_198678f7 _field1;
    CDStruct_198678f7 _field2;
} CDStruct_3c1748cc;

typedef struct {
    struct CGAffineTransform _field1;
} CDStruct_e7d4c00a;

typedef struct {
    long long _field1;
    long long _field2;
    struct CGSize _field3;
    unsigned long long _field4;
    struct {
        CDStruct_198678f7 _field1;
        CDStruct_198678f7 _field2;
        CDStruct_198678f7 _field3;
        struct {
            CDStruct_198678f7 _field1;
            long long _field2;
        } _field4;
        char _field5;
    } _field5;
    long long _field6;
    struct {
        struct CGSize _field1;
        struct CGRect _field2;
        struct CGRect _field3;
        struct CGRect _field4;
        struct CGRect _field5;
    } _field7;
    struct UIEdgeInsets _field8;
    struct {
        CDStruct_3ea48505 _field1;
        CDStruct_3ea48505 _field2;
        CDStruct_198678f7 _field3;
    } _field9;
    struct {
        CDStruct_e7d4c00a _field1;
        CDStruct_e7d4c00a _field2;
        CDStruct_198678f7 _field3;
    } _field10;
    struct {
        char _field1;
        unsigned char _field2;
        CDStruct_198678f7 _field3;
        char _field4;
        union {
            char _field1;
            char _field2;
            char _field3;
            char _field4;
        } _field5;
        union {
            double _field1;
            double _field2;
            char _field3;
        } _field6;
    } _field11;
    struct {
        long long _field1;
        long long _field2;
        float _field3;
        double _field4;
        double _field5;
        double _field6;
        double _field7;
    } _field12;
} CDStruct_60782414;

