//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <ProxCardKit/PRXFeatureListViewController.h>

@class HSProxCardCoordinator, HSSetupStateMachineConfiguration, NSString, UIViewController;

@interface HSPCPersonalRequestsViewController : PRXFeatureListViewController
{
    HSSetupStateMachineConfiguration *_config;
    HSProxCardCoordinator *_coordinator;
}

- (void).cxx_destruct;
@property(retain) HSProxCardCoordinator *coordinator; // @synthesize coordinator=_coordinator;
@property(retain) HSSetupStateMachineConfiguration *config; // @synthesize config=_config;
- (id)_enablePersonalRequests;
- (id)_bulletImageWithSystemName:(id)arg1 color:(id)arg2;
- (id)commitConfiguration;
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;

// Remaining properties
@property(retain, nonatomic) UIViewController *contentVC;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

