//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NewsAnalytics/_TtC13NewsAnalytics15TrackerAssembly.h>

@interface _TtC13NewsAnalytics15TrackerAssembly (NewsAnalytics)
- (void)loadInRegistry:(id)arg1;
@end

