//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SearchFoundation/NSCopying-Protocol.h>
#import <SearchFoundation/NSSecureCoding-Protocol.h>

@interface SFFeedback : NSObject <NSSecureCoding, NSCopying>
{
    unsigned long long _timestamp;
    unsigned long long _queryId;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long queryId; // @synthesize queryId=_queryId;
@property(readonly) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;

@end

