//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ConversationKit/NSObject-Protocol.h>

@class TUAudioFrequencyController;

@protocol TUAudioFrequencyControllerDelegate <NSObject>

@optional
- (void)frequencyController:(TUAudioFrequencyController *)arg1 audioPowerChanged:(float)arg2 forParticipantWithStreamToken:(unsigned long long)arg3;
@end

