//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreServices/LSApplicationProxy.h>

@interface LSApplicationProxy (IconServicesAdditions)
+ (id)__IS_appClipIconDataWithUnmaskedIconData:(id)arg1 variant:(int)arg2;
+ (_Bool)appClipMetadataAvailableForBundleIdentifier:(id)arg1;
+ (_Bool)clipTreatmentIsWhitelisted;
- (id)__IS_iconDataForVariant:(int)arg1 preferredIconName:(id)arg2 withOptions:(int)arg3;
- (id)__IS_iconDataForVariant:(int)arg1 withOptions:(int)arg2;
@end

