//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__SBHAddWidgetDetailSheetViewControllerAccessibility_super.h"

@interface SBHAddWidgetDetailSheetViewControllerAccessibility : __SBHAddWidgetDetailSheetViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_addPage:(id)arg1;
- (void)_createViews;

@end

