//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSAttributedString;

__attribute__((visibility("hidden")))
@interface _NSLineMetrics : NSObject
{
    NSAttributedString *_attributedString;
    struct _NSRange _lineRange;
    struct __CTLine *_line;
    double *_positions;
    struct __CFArray *_runsBuf;
    struct CGSize *_advancesBuf;
    long long *_stringIndicesBuf;
    unsigned long long _glyphCapacity;
}

- (void).cxx_destruct;
- (unsigned long long)suggestedLineBreakAfterIndex:(unsigned long long)arg1 withWidth:(double)arg2;
- (double)widthOfSubstringToIndex:(unsigned long long)arg1;
- (double)widthOfSubstringWithRange:(struct _NSRange)arg1;
- (void)_ensureGlyphCapacity:(unsigned long long)arg1;
- (void)dealloc;
- (void)setAttributedString:(id)arg1 range:(struct _NSRange)arg2 line:(const struct __CTLine *)arg3;
- (id)initWithAttributedString:(id)arg1 range:(struct _NSRange)arg2 line:(const struct __CTLine *)arg3;
- (id)initWithAttributedString:(id)arg1 range:(struct _NSRange)arg2;
- (void)_calculatePositions;

@end

