//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBHomeScreenBackdropViewBase.h>

@class MTMaterialView, UIImage, UIImageView, UIViewFloatAnimatableProperty;

@interface SBHomeScreenBackdropView : SBHomeScreenBackdropViewBase
{
    MTMaterialView *_materialView;
    UIImage *_blurredContentSnapshotImage;
    UIImageView *_blurredContentSnapshotImageView;
    unsigned long long _materialViewAnimationCount;
    _Bool _waitingForBackdropViewToRender;
    UIViewFloatAnimatableProperty *_backdropFloatAnimatableProperty;
}

- (void).cxx_destruct;
- (void)_updateBackdropViewIfNeededInvalidatingSnapshot:(_Bool)arg1;
- (void)_invalidateBackdropSnapshot;
- (void)_updateBackdropViewIfNeeded;
- (void)_resetHomeScreenBlurredContentSnapshotImage;
- (id)homeScreenBlurredContentSnapshotImage;
- (void)cancelInProcessAnimations;
- (_Bool)isOpaque;
- (void)setBlurProgress:(double)arg1 behaviorMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)endRequiringLiveBackdropViewForReason:(id)arg1;
- (void)endRequiringBackdropViewForReason:(id)arg1;
- (void)beginRequiringLiveBackdropViewForReason:(id)arg1;
- (void)beginRequiringBackdropViewForReason:(id)arg1;
- (void)_configureBackdropAnimatableProperty;
- (void)_setupBackdropViewWithRecipe:(long long)arg1 scaleAdjustment:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 materialRecipe:(long long)arg2 scaleAdjustment:(CDUnknownBlockType)arg3;

@end

