//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBMainWorkspaceTransaction.h>

@interface SBTransientOverlayDismissAllWorkspaceTransaction : SBMainWorkspaceTransaction
{
    long long _animatedOverride;
}

+ (_Bool)isValidForTransitionRequest:(id)arg1;
@property(nonatomic, getter=isAnimatedOverride) long long animatedOverride; // @synthesize animatedOverride=_animatedOverride;
- (_Bool)_canBeInterrupted;
- (void)_begin;
- (id)initWithTransitionRequest:(id)arg1;

@end

