//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DAChangeHistoryClerk : NSObject
{
}

+ (id)clerkWithAddressBook:(void *)arg1;
+ (id)clerkWithContactStore:(id)arg1;
- (id)identifiersOfAllRegisterdClients;
- (void)registerClientWithIdentifier:(id)arg1 forContainer:(id)arg2;
- (void)unregisterClientWithIdentifier:(id)arg1 forContainer:(id)arg2;

@end

