//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppPredictionUIWidget/NSObject-Protocol.h>

@class APUISuggestionView, ATXProactiveSuggestion;

@protocol APUISuggestionsWidgetViewDelegate <NSObject>
- (void)view:(APUISuggestionView *)arg1 didFailExecutingSuggestion:(ATXProactiveSuggestion *)arg2;
- (void)view:(APUISuggestionView *)arg1 didFinishExecutingSuggestion:(ATXProactiveSuggestion *)arg2;
- (void)view:(APUISuggestionView *)arg1 didTapSuggestion:(ATXProactiveSuggestion *)arg2;
@end

