//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface EXDrawing : NSObject
{
}

+ (struct EDCellAnchorMarker)readAnchorMarkerFromNode:(struct _xmlNode *)arg1 state:(id)arg2;
+ (void)readFromPart:(id)arg1 state:(id)arg2;
+ (id)readAnchorNode:(struct _xmlNode *)arg1 state:(id)arg2;
+ (void)initialize;
+ (id)readDrawableNode:(struct _xmlNode *)arg1 anchor:(id)arg2 state:(id)arg3;
+ (id)readAbsoluteAnchorNode:(struct _xmlNode *)arg1 state:(id)arg2;
+ (id)readOneCellAnchorNode:(struct _xmlNode *)arg1 state:(id)arg2;
+ (id)readTwoCellAnchorNode:(struct _xmlNode *)arg1 state:(id)arg2;

@end

