//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CalendarNotification/CALNNotificationManager-Protocol.h>

@class NSString;
@protocol CALNNotificationManager;

@interface CALNFilteredNotificationManager : NSObject <CALNNotificationManager>
{
    id <CALNNotificationManager> _wrappedNotificationManager;
    CDUnknownBlockType _predicate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CDUnknownBlockType predicate; // @synthesize predicate=_predicate;
@property(readonly, nonatomic) id <CALNNotificationManager> wrappedNotificationManager; // @synthesize wrappedNotificationManager=_wrappedNotificationManager;
- (void)updateRecord:(id)arg1;
- (void)removeRecordWithSourceIdentifier:(id)arg1 sourceClientIdentifier:(id)arg2;
- (id)fetchRecordsWithSourceIdentifier:(id)arg1;
- (void)addRecord:(id)arg1;
@property(readonly, nonatomic) _Bool isProtectedDataAvailable;
- (id)initWithWrappedNotificationManager:(id)arg1 predicate:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

