//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <FitnessCoachingHealthServices/NSObject-Protocol.h>

@class FCCMoveModeContent, FCMoveModeCoordinator;

@protocol FCMoveModeCoordinatorDelegate <NSObject>
- (void)coordinator:(FCMoveModeCoordinator *)arg1 postMoveModeNotification:(FCCMoveModeContent *)arg2;
@end

