//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFluidDismissalState;

@protocol SBFluidGestureDismissable <NSObject>
@property(retain, nonatomic) SBFluidDismissalState *fluidDismissalState;
@end

