//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFAudio/AVAudioUnitEffect.h>

@interface AVAudioUnitDistortion : AVAudioUnitEffect
{
}

@property(nonatomic) float wetDryMix;
@property(nonatomic) float preGain;
- (void)loadFactoryPreset:(long long)arg1;
- (struct AUPreset)FillOutAUPreset:(long long)arg1;
- (id)init;

@end

