//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class LPQuotedTextViewStyle, LPTextView, NSAttributedString, NSRegularExpression, UIImageView, UITextView, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface LPQuoteView
{
    UITextView *_textView;
    _Bool _didLimitNumberOfCharacters;
    struct UIEdgeInsets _contentInset;
    LPQuotedTextViewStyle *_style;
    NSAttributedString *_attributedString;
    LPTextView *_characterLimitIndicatorView;
    UIImageView *_quoteIndicatorView;
    UIVisualEffectView *_effectView;
    UITextView *_coloredGlyphsView;
    double _ascender;
    double _descender;
    long long _overrideMaximumNumberOfLines;
    NSRegularExpression *_emphasizedTextExpression;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSRegularExpression *emphasizedTextExpression; // @synthesize emphasizedTextExpression=_emphasizedTextExpression;
@property(nonatomic) long long overrideMaximumNumberOfLines; // @synthesize overrideMaximumNumberOfLines=_overrideMaximumNumberOfLines;
- (id)lastBaselineAnchor;
- (id)firstBaselineAnchor;
- (void)applyAttributedString:(id)arg1;
- (id)_createTextView;
- (void)tintColorDidChange;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateEffectiveFontForSize:(struct CGSize)arg1;
- (void)setFont:(id)arg1;
- (void)updateExclusionRects;
- (void)layoutComponentView;
- (long long)effectiveMaximumNumberOfLines;
- (struct UIEdgeInsets)effectiveInsets;
- (struct UIEdgeInsets)effectiveInsetsWithoutQuoteIndicator;
- (long long)computedNumberOfLines;
- (long long)computedNumberOfLinesWithFont:(id)arg1 forSize:(struct CGSize)arg2;
- (double)descender;
- (double)ascender;
- (double)lastLineDescent;
- (double)firstLineLeading;
@property(readonly, retain, nonatomic) LPQuotedTextViewStyle *style;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
@property(readonly, retain, nonatomic) NSAttributedString *attributedString;
- (id)effectiveAttributedString;
- (_Bool)_lp_isLTR;
- (void)_buildSubviewsIfNeeded;
- (id)initWithHost:(id)arg1 text:(id)arg2 style:(id)arg3;
- (id)initWithHost:(id)arg1;

@end

