//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/NSCopying-Protocol.h>
#import <Contacts/NSObject-Protocol.h>
#import <Contacts/NSSecureCoding-Protocol.h>

@protocol CNKeyDescriptor <NSObject, NSSecureCoding, NSCopying>
@end

