//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransientOverlayPresentationRequest.h>

@class SBTransientOverlayViewController;

@interface SBMutableTransientOverlayPresentationRequest : SBTransientOverlayPresentationRequest
{
}

@property(retain, nonatomic) SBTransientOverlayViewController *viewController; // @dynamic viewController;
@property(nonatomic) _Bool shouldDismissSiri; // @dynamic shouldDismissSiri;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @dynamic completionHandler;
@property(nonatomic, getter=isAnimated) _Bool animated; // @dynamic animated;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

