//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

@class CPLPrequeliteVariable;

@interface _CPLPrequeliteScopeBase
{
    CPLPrequeliteVariable *_scopeIdentifierVar;
    CPLPrequeliteVariable *_scopeTypeVar;
    CPLPrequeliteVariable *_localIndexVar;
    CPLPrequeliteVariable *_cloudIndexVar;
    CPLPrequeliteVariable *_stableIndexVar;
    CPLPrequeliteVariable *_creationDateVar;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CPLPrequeliteVariable *creationDateVar; // @synthesize creationDateVar=_creationDateVar;
@property(readonly, nonatomic) CPLPrequeliteVariable *stableIndexVar; // @synthesize stableIndexVar=_stableIndexVar;
@property(readonly, nonatomic) CPLPrequeliteVariable *cloudIndexVar; // @synthesize cloudIndexVar=_cloudIndexVar;
@property(readonly, nonatomic) CPLPrequeliteVariable *localIndexVar; // @synthesize localIndexVar=_localIndexVar;
@property(readonly, nonatomic) CPLPrequeliteVariable *scopeTypeVar; // @synthesize scopeTypeVar=_scopeTypeVar;
@property(readonly, nonatomic) CPLPrequeliteVariable *scopeIdentifierVar; // @synthesize scopeIdentifierVar=_scopeIdentifierVar;
- (id)init;

@end

