//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSProgress, NSURL;

@protocol NSFileCoordinatorUploadFilePreparing
- (NSProgress *)prepareFileForUploadingAtURL:(NSURL *)arg1 originalURLExtension:(NSData *)arg2 inDirectory:(NSURL *)arg3 destinationSandboxExtension:(NSData *)arg4 completionHandler:(void (^)(NSURL *, NSError *))arg5;
@end

