//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <FeedbackCore/NSObject-Protocol.h>

@class DEDDevice, FBKGroupedDevice, NSDictionary, NSSet, NSString;

@protocol DEDDeviceLike <NSObject>
- (_Bool)isLikeDEDDevice:(DEDDevice *)arg1;
- (void)addDevice:(DEDDevice *)arg1;
- (NSString *)hashingKey;
- (NSString *)shortDescription;
- (_Bool)isEqualToDevice:(FBKGroupedDevice *)arg1;
- (_Bool)hasCapabilities:(NSSet *)arg1;
- (NSDictionary *)serialize;
- (NSString *)productType;
- (NSString *)name;
- (NSString *)deviceClass;
- (NSString *)color;
- (NSString *)build;
- (NSString *)publicLogDescription;
- (_Bool)isCurrentDevice;
- (NSString *)platform;
- (NSString *)identifier;
@end

