//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

__attribute__((visibility("hidden")))
@interface RCEntityRevision : NSManagedObject
{
}

- (void)setRecordingID:(long long)arg1;
@property(readonly, nonatomic) long long recordingID;
- (void)setRevisionID:(long long)arg1;
@property(readonly, nonatomic) long long revisionID;
- (void)setRevisionType:(long long)arg1;
@property(readonly, nonatomic) long long revisionType;

@end

