//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASStartSpeech.h>

@interface SASStartSpeech (SiriCoreSessionObject)
- (_Bool)siriCore_isRestartable;
@end

