//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <GameCenterFoundation/SSDownloadManagerObserver-Protocol.h>

@class NSString, SSDownloadManager;

@interface GKDownloadObserver : NSObject <SSDownloadManagerObserver>
{
    SSDownloadManager *_downloadManager;
}

+ (id)sharedObserver;
@property(retain) SSDownloadManager *downloadManager; // @synthesize downloadManager=_downloadManager;
- (void)downloadManager:(id)arg1 downloadStatesDidChange:(id)arg2;
- (_Bool)isDownloadingGame:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

