//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSString;

@interface SARadarSetDetails : SABaseClientBoundCommand
{
}

+ (id)setDetailsWithDictionary:(id)arg1 context:(id)arg2;
+ (id)setDetails;
- (_Bool)requiresResponse;
@property(copy, nonatomic) NSString *title;
@property(copy, nonatomic) NSString *description;
@property(copy, nonatomic) NSString *classification;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

