//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <Preferences/PSTableCell.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface PSUIDanglingPlanTableCell : PSTableCell
{
    UILabel *_nameLabel;
    UILabel *_numberLabel;
    UILabel *_statusLabel;
}

+ (long long)cellStyle;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (id)detailTextLabel;
- (id)textLabel;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (void)_setLabel:(id)arg1 andPhoneNumber:(id)arg2;
- (_Bool)canBeChecked;
- (_Bool)canReload;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

