//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BRAccountTokenWillChangeObserver : NSObject
{
    NSString *_personaID;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *personaID; // @synthesize personaID=_personaID;
- (void)_accountWillChange;
- (id)initWithPersonaID:(id)arg1;

@end

