//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ACAccount, NSArray, NSDictionary, NSMutableArray;

@interface RestoreBatchContext : NSObject
{
    ACAccount *_account;
    NSMutableArray *_hardFailures;
    NSDictionary *_itemMap;
    NSMutableArray *_remainingItemIDs;
    NSMutableArray *_softFailures;
    NSMutableArray *_successfulItems;
    NSArray *_targetItems;
}

- (void).cxx_destruct;
@property(readonly) NSArray *targetItems; // @synthesize targetItems=_targetItems;
@property(readonly, nonatomic) NSMutableArray *successfulItems; // @synthesize successfulItems=_successfulItems;
@property(readonly, nonatomic) NSMutableArray *softFailures; // @synthesize softFailures=_softFailures;
@property(readonly, nonatomic) NSMutableArray *remainingItemIDs; // @synthesize remainingItemIDs=_remainingItemIDs;
@property(readonly) NSDictionary *itemMap; // @synthesize itemMap=_itemMap;
@property(readonly, nonatomic) NSMutableArray *hardFailures; // @synthesize hardFailures=_hardFailures;
- (void)softFailItem:(id)arg1 withError:(id)arg2;
- (void)itemSucceeded:(id)arg1 storeItem:(id)arg2;
- (void)hardFailItem:(id)arg1 withError:(id)arg2;
- (id)initWithItems:(id)arg1 account:(id)arg2;

@end

