//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AXSpringBoardServerInstance/__AXSBServerHelperBulletinWindowController_super.h>

@interface AXSBServerHelperBulletinWindowController : __AXSBServerHelperBulletinWindowController_super
{
}

+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)_allowsShowNotificationsGestureFromBanner:(_Bool)arg1;

@end

