//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <PassKitUI/PKIdentifiable-Protocol.h>

@class UICollectionViewListCell;

@protocol PKApplyCollectionViewRow <PKIdentifiable>
- (void)configureCell:(UICollectionViewListCell *)arg1;
- (Class)cellClass;

@optional
- (_Bool)shouldHighlightItem;
- (void)handleCellSelection;
@end

