//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IPAMetadata, NSMutableArray;
@protocol OS_dispatch_queue;

@interface IPAMetadataStateHandler : NSObject
{
    IPAMetadata *_metadata;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned long long _stateHandle;
    NSMutableArray *_breadcrumbs;
}

+ (id)redactedDescriptionForPath:(id)arg1;
+ (id)redactedDescriptionForFileURL:(id)arg1;
- (void).cxx_destruct;
- (void)_addBreadcrumbWithTimeInterval:(double)arg1 message:(id)arg2;
- (void)addBreadcrumb:(id)arg1;
- (struct os_state_data_s *)stateDataWithHints:(struct os_state_hints_s *)arg1;
- (id)_stateInformation;
- (void)dealloc;
- (id)initWithMetadata:(id)arg1;

@end

