//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <ScoreBoard/SCRTaskSchedulerDelegate-Protocol.h>

@class NSMutableDictionary, NSString, SCRApprovalCoordinator, SCRTaskScheduler;
@protocol OS_dispatch_queue;

@interface SCRTaskAdministrator : NSObject <SCRTaskSchedulerDelegate>
{
    struct os_unfair_lock_s _lock;
    NSObject<OS_dispatch_queue> *_workQueue;
    SCRTaskScheduler *_scheduler;
    SCRApprovalCoordinator *_approvalCoordinator;
    NSMutableDictionary *_taskForIdentifier;
}

- (void).cxx_destruct;
- (void)scheduler:(id)arg1 beginSchedulingWindowOnBehalfOfTasks:(id)arg2;
- (void)unregisterGovernor:(id)arg1;
- (void)registerGovernor:(id)arg1;
- (void)cancelTaskWithIdentifier:(id)arg1;
- (void)submitTask:(id)arg1;
- (id)initWithTargetQueue:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

