//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__SBUIControllerAccessibility_super.h"

@interface SBUIControllerAccessibility : __SBUIControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)updateBatteryState:(id)arg1;
- (_Bool)_accessibilityIsAppSwitcherVisible;

@end

