//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC9SeymourUI25MarketingHeaderBannerCell : UICollectionViewCell
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *itemInfo;
    MISSING_TYPE *layout;
    MISSING_TYPE *labelGuide;
    MISSING_TYPE *artworkView;
    MISSING_TYPE *artworkBackgroundView;
    MISSING_TYPE *bannerMessageBackgroundView;
    MISSING_TYPE *bannerMessageImageView;
    MISSING_TYPE *playButton;
    MISSING_TYPE *subtitleLabel;
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *labelFontUpdater;
    MISSING_TYPE *oldSize;
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

