//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9SeymourUI30RangedCoachingEventNodeBuilder : _TtCs12_SwiftObject
{
    MISSING_TYPE *parent;
    MISSING_TYPE *containerBuilder;
    MISSING_TYPE *plusAsset;
    MISSING_TYPE *valueNode;
    MISSING_TYPE *unitNode;
    MISSING_TYPE *plusNode;
    MISSING_TYPE *valueString;
    MISSING_TYPE *unitString;
    MISSING_TYPE *showPlus;
}

@end

