//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Photos/NSObject-Protocol.h>

@class NSString;

@protocol PLUniformTypeIdentifierIdentity <NSObject>
@property(readonly, nonatomic, getter=isPrimaryFormat) _Bool primaryFormat;
@property(readonly, nonatomic) _Bool conformsToMovie;
@property(readonly, nonatomic) _Bool conformsToImage;
@property(readonly, copy, nonatomic) NSString *identifier;
@end

