//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CNAvatarImageRenderer, NSMutableDictionary;
@protocol MKInfoCardTheme, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MKPlaceReviewAvatarGenerator : NSObject
{
    NSObject<OS_dispatch_queue> *_workQueue;
    NSMutableDictionary *_cachedMaskedImages;
    id <MKInfoCardTheme> _theme;
    CNAvatarImageRenderer *_monogrammer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CNAvatarImageRenderer *monogrammer; // @synthesize monogrammer=_monogrammer;
@property(nonatomic) __weak id <MKInfoCardTheme> theme; // @synthesize theme=_theme;
- (void)avatarForReview:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)monogramForReviewerName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

