//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IKArray;

@interface IKCSSParseStylesheet : NSObject
{
    IKArray *_cssValue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IKArray *cssValue; // @synthesize cssValue=_cssValue;
- (id)description;

@end

