//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "__PKReaderModeHeaderViewAccessibility_super.h"

@interface PKReaderModeHeaderViewAccessibility : __PKReaderModeHeaderViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)_configureForCurrentState;
- (void)_setAXCurrentLabelText:(id)arg1;
- (id)_axCurrentLabelText;

@end

