//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreML/NSSecureCoding-Protocol.h>

@interface MLImageSize : NSObject <NSSecureCoding>
{
    long long _pixelsWide;
    long long _pixelsHigh;
}

+ (_Bool)supportsSecureCoding;
@property(readonly) long long pixelsHigh; // @synthesize pixelsHigh=_pixelsHigh;
@property(readonly) long long pixelsWide; // @synthesize pixelsWide=_pixelsWide;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToImageSize:(id)arg1;
- (unsigned long long)hash;
- (id)initWithPixelsWide:(long long)arg1 pixelsHigh:(long long)arg2;

@end

