//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class _PASCFBurstTrie;

@interface PPTopicBlacklistGuardedData : NSObject
{
    _PASCFBurstTrie *_blacklistTrie;
}

- (void).cxx_destruct;

@end

