//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <HomeKitDaemon/NSObject-Protocol.h>

@class HMDCameraSnapshotIDSStreamInitiator, NSError;

@protocol HMDCameraSnapshotIDSStreamInitiatorDelegate <NSObject>
- (void)streamInitiator:(HMDCameraSnapshotIDSStreamInitiator *)arg1 didFailToSendFile:(NSError *)arg2;
@end

