//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface HDHealthOntologyConfiguration : NSObject
{
    NSDictionary *_countryConfigurations;
}

+ (id)bundledHealthOntologyConfiguration;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *countryConfigurations; // @synthesize countryConfigurations=_countryConfigurations;
@property(readonly, copy, nonatomic) NSArray *allCountryConfigurations;
- (id)configurationForCountryCode:(id)arg1;
- (id)initWithCountryConfigurations:(id)arg1;
- (id)init;

@end

