//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/_UIFocusRegionContainer-Protocol.h>

@class _UIFocusRegionContentAttributes;
@protocol UICoordinateSpace;

@protocol _UIFocusRegionContainerInternal <_UIFocusRegionContainer>

@optional
- (_UIFocusRegionContentAttributes *)_attributesForFocusRegionContentInCoordinateSpace:(id <UICoordinateSpace>)arg1;
@end

