//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class FTRecognitionResult, NSArray, NSData, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface FTKeywordFinderRequest : NSObject
{
    NSMutableDictionary *_storage;
    NSData *_data;
    const struct KeywordFinderRequest *_root;
}

- (void).cxx_destruct;
- (id)flatbuffData;
- (Offset_002dc819)addObjectToBuffer:(void *)arg1;
@property(readonly, nonatomic) _Bool enable_sanitization;
@property(readonly, nonatomic) FTRecognitionResult *recognition_result;
- (void)keywords_enumerateObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (unsigned long long)keywords_count;
- (id)keywords_objectAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) NSArray *keywords;
@property(readonly, nonatomic) NSString *language;
@property(readonly, nonatomic) NSString *session_id;
@property(readonly, nonatomic) NSString *speech_id;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct KeywordFinderRequest *)arg2 verify:(_Bool)arg3;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct KeywordFinderRequest *)arg2;
- (id)initAndVerifyWithFlatbuffData:(id)arg1;
- (id)initWithFlatbuffData:(id)arg1;

@end

