//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <VideosUI/VUIImageInfoManagedObject.h>

@class VUITVSeriesManagedObject;

__attribute__((visibility("hidden")))
@interface VUITVSeriesImageInfoManagedObject : VUIImageInfoManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) VUITVSeriesManagedObject *series; // @dynamic series;

@end

