//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CLSCurationSession : NSObject
{
    NSMutableDictionary *_curationModelBySpecification;
}

+ (void)enumerateSignalsFromAsset:(id)arg1 fullHierarchyName:(_Bool)arg2 usingBlock:(CDUnknownBlockType)arg3;
+ (short)audioClassificationsToEmphasizeWithAudioClassificationCounts:(id)arg1 threshold:(double)arg2;
+ (void)addAudioClassifications:(short)arg1 toAudioClassificationCounts:(id)arg2;
+ (id)scoringContextWithAssets:(id)arg1;
+ (double)legacyAestheticScoreThresholdToNotBeJunk;
+ (double)legacyAestheticScoreThresholdToBeAestheticallyPrettyGood;
+ (double)legacyAestheticScoreThresholdToBeAwesome;
- (void).cxx_destruct;
- (void)prepareAssets:(id)arg1;
- (id)curationModelWithCurationModelVersion:(unsigned long long)arg1 forAsset:(id)arg2;
- (id)latestCurationModelForTesting;
- (id)curationModelForItemInfo:(id)arg1 options:(id)arg2;
- (id)curationModelForAsset:(id)arg1;
- (id)curationModelWithSpecification:(id)arg1;
- (id)_curationModelWithSpecification:(id)arg1;
- (unsigned long long)_latestCurationModelVersionApplicableForCurationModelSpecification:(id)arg1;
- (id)init;

@end

