//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ControlContaineeViewController.h"

#import "DataSourceDelegate-Protocol.h"
#import "HeaderViewDelegate-Protocol.h"
#import "PPTTestChromeScrollable-Protocol.h"

@class ContainerHeaderView, MapsThemeTableView, MyRecentsDataSource, NSString, UIScrollView;

__attribute__((visibility("hidden")))
@interface MyRecentsViewController : ControlContaineeViewController <HeaderViewDelegate, DataSourceDelegate, PPTTestChromeScrollable>
{
    ContainerHeaderView *_titleHeaderView;
    MapsThemeTableView *_tableView;
    MyRecentsDataSource *_recentsDataSource;
    _Bool _includeRecentSearches;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIScrollView *pptTestScrollView;
- (void)dataSource:(id)arg1 itemTapped:(id)arg2;
- (void)dataSourceUpdated:(id)arg1;
- (void)headerViewButtonTapped:(id)arg1;
- (void)loadDataSource;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_updateHeaderHairline;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initIncludingRecentSearches:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

