//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NavigationRouteDetouring-Protocol.h"

@class MNNavigationService, NSString;
@protocol NavigationRouteHistoryInfoProviding, NavigationRouteInterrupting;

__attribute__((visibility("hidden")))
@interface NavigationRouteDetourer : NSObject <NavigationRouteDetouring>
{
    MNNavigationService *_navigationService;
    id <NavigationRouteHistoryInfoProviding> _routeInfoProvider;
    id <NavigationRouteInterrupting> _routeInterrupter;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <NavigationRouteInterrupting> routeInterrupter; // @synthesize routeInterrupter=_routeInterrupter;
@property(readonly, nonatomic) id <NavigationRouteHistoryInfoProviding> routeInfoProvider; // @synthesize routeInfoProvider=_routeInfoProvider;
@property(readonly, nonatomic) MNNavigationService *navigationService; // @synthesize navigationService=_navigationService;
- (void)detourRouteToMapItem:(id)arg1;
- (id)initWithNavigationService:(id)arg1 routeInfoProvider:(id)arg2 routeInterrupter:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

