//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RAPHeaderFooterView.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface RAPCollapsableHeaderFooterView : RAPHeaderFooterView
{
    UIButton *_showAllButton;
}

+ (void)toggleCollapseForTableView:(id)arg1 AtSection:(long long)arg2 withSelectedValue:(id)arg3 withSelectedIndex:(long long)arg4 withAllValues:(id)arg5;
- (void).cxx_destruct;
- (void)setShowAllButtonVisible:(_Bool)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (void)layoutSubviews;
- (id)_initialConstraints;
- (void)_createSubviews;

@end

