//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MKMapItem, MacRAPTokenTableViewCell, NSArray, NSString, RAPCancellableTableViewCell, RAPStoreHour, UIView;

@protocol RAPCorrectionQuestionUpdateDelegate <NSObject>
@property(readonly, nonatomic) UIView *photoPickerSourceView;
- (void)deleteTokenCell:(MacRAPTokenTableViewCell *)arg1;
- (void)deleteCell:(RAPCancellableTableViewCell *)arg1;
- (void)didUpdateClosureInformationOfKind:(long long)arg1 isEnabled:(_Bool)arg2;
- (void)addContainmentInformationOfKind:(long long)arg1 withMapItem:(MKMapItem *)arg2;
- (void)addHours:(RAPStoreHour *)arg1;
- (void)replaceCategories:(NSArray *)arg1;
- (void)didUpdateAddress:(NSString *)arg1;
- (void)didUpdateCoordinate:(struct CLLocationCoordinate2D)arg1;
@end

