//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UGCPhotoCarouselController;

@protocol UGCPhotoCarouselRequestDelegate <NSObject>
- (void)photoCarouselController:(UGCPhotoCarouselController *)arg1 requestsRemovingImageForIdentifier:(NSString *)arg2 completion:(void (^)(_Bool))arg3;
- (void)photoCarouselControllerRequestsAddingNewPhoto:(UGCPhotoCarouselController *)arg1;

@optional
- (void)photoCarouselController:(UGCPhotoCarouselController *)arg1 didSelectImageWithIdentifier:(NSString *)arg2;
@end

