//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UISearchController.h>

@class PSKeyboardNavigationSearchBar, UIViewController;
@protocol PSKeyboardNavigationSearchResultsController;

@interface PSKeyboardNavigationSearchController : UISearchController
{
    UIViewController<PSKeyboardNavigationSearchResultsController> *searchResultsController;
    PSKeyboardNavigationSearchBar *searchBar;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PSKeyboardNavigationSearchBar *searchBar; // @synthesize searchBar;
@property(retain, nonatomic) UIViewController<PSKeyboardNavigationSearchResultsController> *searchResultsController; // @synthesize searchResultsController;
- (void)_upArrowKeyPressed;
- (void)_downArrowKeyPressed;
- (void)_escapeKeyPressed;
- (id)initWithSearchResultsController:(id)arg1;

@end

