//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FRRoutable-Protocol.h"

@class FRAnalyticsReferral, NSString, NSUserActivity;

@protocol FRUserActivityRoutable <FRRoutable>
- (_Bool)continueUserActivity:(NSUserActivity *)arg1 withAnalyticsReferral:(FRAnalyticsReferral *)arg2;
- (FRAnalyticsReferral *)analyticsReferralForUserActivity:(NSUserActivity *)arg1;
- (_Bool)canContinueUserActivityWithType:(NSString *)arg1;
@end

