//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PencilKit/NSObject-Protocol.h>

@protocol _PKColorPickerImplementation;

@protocol _PKColorPickerImplementationDelegate <NSObject>
- (void)colorPickerImplementationDidChangeSelectedColor:(id <_PKColorPickerImplementation>)arg1;

@optional
- (void)colorPickerImplementationUserDidTouchUpInside:(id <_PKColorPickerImplementation>)arg1;
@end

