//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FCFetchedValueManager;

@interface FCAlternateUniversalLinksMappingManager : NSObject
{
    FCFetchedValueManager *_updateValueManager;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) FCFetchedValueManager *updateValueManager; // @synthesize updateValueManager=_updateValueManager;
- (void)installMappingFilesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithMappingDirectoryFileURL:(id)arg1 contentContext:(id)arg2;
- (id)init;

@end

