//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OfficeImport/MFPhoneBrush.h>

__attribute__((visibility("hidden")))
@interface MFPhoneNullBrush : MFPhoneBrush
{
}

+ (id)nullBrush;
- (void)fillPath:(id)arg1 in_path:(id)arg2;

@end

