//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <ActivityRingsUI/NSCopying-Protocol.h>

@class ARUISpriteTexture, NSArray;

@interface ARUISpriteSheet : NSObject <NSCopying>
{
    NSArray *_sprites;
    ARUISpriteTexture *_texture;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) ARUISpriteTexture *texture; // @synthesize texture=_texture;
@property(readonly, nonatomic) NSArray *sprites; // @synthesize sprites=_sprites;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithSpriteSheet:(id)arg1;
- (id)initWithTexture:(id)arg1 sprites:(id)arg2;

@end

