//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class PKTableHeaderView, UIButton, UIScrollView;

@interface PKCameraCaptureInstructionView : UIView
{
    long long _context;
    UIScrollView *_scrollView;
    UIButton *_primaryButton;
    UIButton *_secondaryButton;
    PKTableHeaderView *_headerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PKTableHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIButton *secondaryButton; // @synthesize secondaryButton=_secondaryButton;
@property(retain, nonatomic) UIButton *primaryButton; // @synthesize primaryButton=_primaryButton;
- (_Bool)isBuddyiPad;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 context:(long long)arg2;

@end

