//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UILabel;

@interface SULinkControl : UIControl
{
    UILabel *_label;
    _Bool _shouldDrawUnderline;
    unsigned int _sizeIsDirty:1;
    long long _style;
}

@property(nonatomic) _Bool shouldDrawUnderline; // @synthesize shouldDrawUnderline=_shouldDrawUnderline;
- (void)_updateLabel;
- (id)_label;
- (void)sizeToFit;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)setText:(id)arg1;
- (void)setStyle:(long long)arg1;
- (void)dealloc;

@end

