//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AccessibilityPhysicalInteraction/NSObject-Protocol.h>

@class UIColor;

@protocol AXPIFingerAppearanceDelegate <NSObject>
- (double)fingerDiameter;
- (double)fingerInnerCircleInnerRadius;
- (double)fingerInnerRadius;
- (double)fingerOuterRadius;
- (double)strokeOutlineWidth;
- (double)strokeWidth;
- (UIColor *)circularProgressFillColor;
- (UIColor *)strokeOutlineColor;
- (UIColor *)deselectedStrokeColor;
- (UIColor *)selectedStrokeColor;
- (UIColor *)deselectedFillColor;
- (UIColor *)selectedFillColor;
@end

