//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <NotesEditor/NSObject-Protocol.h>

@class ICHashtagViewController, NSString;

@protocol ICHashtagViewControllerDelegate <NSObject>

@optional
- (void)hashtagViewController:(ICHashtagViewController *)arg1 insertFutureHashtagWithText:(NSString *)arg2;
- (void)hashtagViewController:(ICHashtagViewController *)arg1 insertUnknownInlineAttachmentWithText:(NSString *)arg2;
- (void)hashtagViewController:(ICHashtagViewController *)arg1 insertHashtagWithText:(NSString *)arg2 viaAutoComplete:(_Bool)arg3;
@end

