//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <UIKitServices/FBSServiceFacilityClientContext-Protocol.h>

@class NSString;
@protocol FBSServiceFacilityClientHandle;

@interface _UISApplicationStateClientContext : NSObject <FBSServiceFacilityClientContext>
{
    id <FBSServiceFacilityClientHandle> _clientHandle;
    NSString *_bundleIdentifier;
}

@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(nonatomic) __weak id <FBSServiceFacilityClientHandle> clientHandle; // @synthesize clientHandle=_clientHandle;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

