//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SXDragManager, UIView;
@protocol SXDraggable;

@protocol SXDragManagerDataSource
- (id <SXDraggable>)dragManager:(SXDragManager *)arg1 dragableAtLocation:(struct CGPoint)arg2;
- (UIView *)viewForDragManager:(SXDragManager *)arg1;
@end

