//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SYDDaemonProtocol-Protocol.h"

@class NSMutableSet, NSXPCConnection;
@protocol OS_dispatch_queue, SYDDaemonToClientConnectionDelegate;

@interface SYDDaemonToClientConnection : NSObject <SYDDaemonProtocol>
{
    NSXPCConnection *_xpcConnection;
    id <SYDDaemonToClientConnectionDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableSet *_registeredStoreIDs;
    NSMutableSet *_entitledStoreIDs;
}

+ (id)changeDictionaryWithChangedKeys:(id)arg1 reason:(long long)arg2 changeToken:(id)arg3;
+ (id)errorNotEntitledForStoreIdentifier:(id)arg1;
+ (_Bool)isXPCConnection:(id)arg1 entitledForStoreID:(id)arg2;
@property(retain, nonatomic) NSMutableSet *entitledStoreIDs; // @synthesize entitledStoreIDs=_entitledStoreIDs;
@property(retain, nonatomic) NSMutableSet *registeredStoreIDs; // @synthesize registeredStoreIDs=_registeredStoreIDs;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(nonatomic) __weak id <SYDDaemonToClientConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (void).cxx_destruct;
- (id)client;
- (id)asyncClientWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)notifyAccountDidChangeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)syncManagerDidChangeNotification:(id)arg1;
- (void)processAccountChangesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)changeDictionarySinceChangeToken:(id)arg1 inStoreWithIdentifier:(id)arg2 type:(long long)arg3 reply:(CDUnknownBlockType)arg4;
- (void)registerForChangeNotificationsForStoreWithIdentifier:(id)arg1 type:(long long)arg2 reply:(CDUnknownBlockType)arg3;
- (void)deleteDataFromDiskForStoreIdentifier:(id)arg1 type:(long long)arg2 reply:(CDUnknownBlockType)arg3;
- (void)dictionaryRepresentationForStoreWithIdentifier:(id)arg1 type:(long long)arg2 reply:(CDUnknownBlockType)arg3;
- (void)synchronizeStoreWithIdentifier:(id)arg1 type:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)removeObjectForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 type:(long long)arg3 reply:(CDUnknownBlockType)arg4;
- (void)objectForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 type:(long long)arg3 reply:(CDUnknownBlockType)arg4;
- (void)setObject:(id)arg1 forKey:(id)arg2 inStoreWithIdentifier:(id)arg3 type:(long long)arg4 reply:(CDUnknownBlockType)arg5;
- (_Bool)isEntitledForStoreIdentifier:(id)arg1 type:(long long)arg2;
- (void)resume;
- (id)description;
- (id)initWithXPCConnection:(id)arg1 delegate:(id)arg2;

@end

