//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameCenterUI/GKLoadResourceOperation.h>

@class NSObject, NSURLSessionDataTask;
@protocol GKResourceDataConsumer, OS_dispatch_queue;

@interface GKLoadImageResourceOperation : GKLoadResourceOperation
{
    NSURLSessionDataTask *_task;
    id <GKResourceDataConsumer> _dataConsumer;
    NSObject<OS_dispatch_queue> *_dataConsumerQueue;
}

+ (id)keyPathsForValuesAffectingIsFinished;
+ (id)keyPathsForValuesAffectingIsExecuting;
+ (id)dataConsumerQueue;
+ (id)URLSession;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dataConsumerQueue; // @synthesize dataConsumerQueue=_dataConsumerQueue;
@property(readonly, nonatomic) id <GKResourceDataConsumer> dataConsumer; // @synthesize dataConsumer=_dataConsumer;
@property(readonly, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
- (void)cancel;
- (void)start;
- (void)setQueuePriority:(long long)arg1;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)isAsynchronous;
- (void)didFinishTaskWithData:(id)arg1 response:(id)arg2 error:(id)arg3;
- (id)initWithURLRequest:(id)arg1 dataConsumer:(id)arg2;
- (id)initWithURLRequest:(id)arg1 URLSession:(id)arg2 dataConsumer:(id)arg3 dataConsumerQueue:(id)arg4;

@end

