//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMapTable;

@interface _NTKSharedJetsamInfo : NSObject
{
    NSMapTable *_fetchers;
    NSLock *_fetchersLock;
    int _pid;
}

+ (id)sharedJetsamInfo;
- (void).cxx_destruct;
- (void)unregister:(id)arg1;
- (_Bool)resetIntervalFor:(id)arg1;
- (_Bool)getInfoFor:(id)arg1 into:(struct jetsam_info *)arg2;
- (id)init;

@end

