//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CarPlay/CPBannerDelegate-Protocol.h>

@class NSString, NSUUID;

@protocol CPTemplateServiceClientInterface <CPBannerDelegate>
- (void)clientPushNowPlayingTemplateAnimated:(_Bool)arg1;
- (void)updateInterestingLayoutGuideWithInsets:(struct UIEdgeInsets)arg1;
- (void)templateIdentifierDidDismiss:(NSUUID *)arg1;
- (void)templateIdentifierDidPop:(NSUUID *)arg1;
- (void)clientExceededAudioMetadataThrottleLimit;
- (void)clientExceededTabBarTabLimit;
- (void)clientPushedIllegalTemplateOfClass:(NSString *)arg1;
- (void)clientExceededHierarchyDepthLimit;
@end

