//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSArray, TSPFinalizeHandlerQueue;
@protocol TSPReadCoordinator;

@interface TSPReadCompletionInfo : NSObject
{
    NSArray *_objects;
    id <TSPReadCoordinator> _readCoordinator;
    TSPFinalizeHandlerQueue *_finalizeHandlerQueue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) TSPFinalizeHandlerQueue *finalizeHandlerQueue; // @synthesize finalizeHandlerQueue=_finalizeHandlerQueue;
@property(readonly, nonatomic) id <TSPReadCoordinator> readCoordinator; // @synthesize readCoordinator=_readCoordinator;
- (id)readObjectWithIdentifier:(long long)arg1;
- (id)initWithObjects:(id)arg1 readCoordinator:(id)arg2 finalizeHandlerQueue:(id)arg3;

@end

