//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WorkflowKit/WFTrigger.h>

@interface WFPredictedLocationTransitionTrigger : WFTrigger
{
    unsigned long long _destinationType;
    unsigned long long _minutesBefore;
}

+ (_Bool)supportsSecureCoding;
+ (id)localizedDisplayExplanation;
+ (id)localizedDisplayName;
@property(nonatomic) unsigned long long minutesBefore; // @synthesize minutesBefore=_minutesBefore;
@property(nonatomic) unsigned long long destinationType; // @synthesize destinationType=_destinationType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)localizedTitleWithConfigurationSummary;
- (_Bool)hasValidConfiguration;

@end

