//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GEOPlatform : NSObject
{
}

+ (id)sharedPlatform;
+ (_Bool)isRunningInGeod;
+ (void)setIsRunningInGeod:(_Bool)arg1;
- (double)deviceScreenScale;
- (long long)deviceScreenHeightInPixels;
- (long long)deviceScreenWidthInPixels;
- (id)clientCapabilities;
- (_Bool)isCellDataPossible;
- (_Bool)supportsForceTouch;
- (_Bool)supportsNavigation;
- (_Bool)supportsRealisticTiles;
- (_Bool)mapsFeatureFreedomEnabled;
- (_Bool)_deviceSupportsNavigation;
- (id)deviceCountrySKUForServiceRequests;
- (id)deviceCountrySKU;
- (id)hardwareModel;
- (id)hardwareIdentifier;
- (id)osAndBuildVersion;
- (id)buildVersion;
- (id)osVersion;
- (id)productName;
- (_Bool)isInternalInstall;
- (id)init;

@end

