//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

__attribute__((visibility("hidden")))
@interface WKDataListSuggestionsPopover
{
    struct RetainPtr<WKFormRotatingAccessoryPopover> _popover;
    struct RetainPtr<WKDataListSuggestionsViewController> _suggestionsViewController;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didSelectOptionAtIndex:(long long)arg1;
- (void)invalidate;
- (void)showSuggestionsDropdown:(void *)arg1 activationType:(unsigned char)arg2;
- (void)updateWithInformation:(void *)arg1;
- (id)initWithInformation:(void *)arg1 inView:(id)arg2;

@end

