//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;
@protocol MTLDevice;

__attribute__((visibility("hidden")))
@interface VNMetalContext : NSObject
{
    _Bool _useGPU;
    id <MTLDevice> _metalDevice;
    NSDictionary *_wisdomParams;
}

- (void).cxx_destruct;
@property(readonly) _Bool useGPU; // @synthesize useGPU=_useGPU;
@property(readonly) NSDictionary *wisdomParams; // @synthesize wisdomParams=_wisdomParams;
@property(readonly) id <MTLDevice> metalDevice; // @synthesize metalDevice=_metalDevice;
- (id)initWithMetalDevice:(id)arg1;

@end

