//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PLCGPathCache : NSObject
{
    struct __CFDictionary *_pathCache;
}

+ (id)sharedPathCache;
- (struct CGPath *)pathForKey:(struct CGRect)arg1;
- (void)setPath:(struct CGPath *)arg1 forKey:(struct CGRect)arg2;
- (void)dealloc;
- (id)init;

@end

