//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface NTKBundleComplicationDataSourceBundleCache : NSObject
{
    NSMutableDictionary *_cachedBundles;
    struct os_unfair_lock_s _bundleLock;
}

+ (id)sharedBundleCache;
- (void).cxx_destruct;
- (id)bundleAtPath:(id)arg1;
- (void)dealloc;
- (id)_init;

@end

