//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <MediaControls/NSObject-Protocol.h>

@class MRUNowPlayingTransportControlsView, MRUTransportButton;

@protocol MRUNowPlayingTransportControlsViewDelegate <NSObject>
- (void)transportControlsView:(MRUNowPlayingTransportControlsView *)arg1 didSelectRoutingButton:(MRUTransportButton *)arg2;
- (void)transportControlsView:(MRUNowPlayingTransportControlsView *)arg1 didSelectTVRemoteButton:(MRUTransportButton *)arg2;
@end

