//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIActivity.h>

#import <SafariServices/LSOpenResourceOperationDelegate-Protocol.h>

@class LSApplicationProxy, NSString;

__attribute__((visibility("hidden")))
@interface _SFOpenWithAppUIActivity : UIActivity <LSOpenResourceOperationDelegate>
{
    LSApplicationProxy *_appProxy;
    NSString *_filePath;
}

- (void).cxx_destruct;
- (void)openResourceOperation:(id)arg1 didFinishCopyingResource:(id)arg2;
- (void)performActivity;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)_activityImage;
- (id)activityTitle;
- (id)activityType;
- (id)initWithApplicationIdentifier:(id)arg1 andFilePath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

