//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIDragItem.h>

@class NSURL, WebBookmark, _SFTabStateData;

@interface UIDragItem (SafariServicesExtras)
+ (id)_sf_itemWithTabStateData:(id)arg1 userActivity:(id)arg2;
+ (void)_sf_loadObjectsFromDragItems:(id)arg1 usingLocalObjectLoader:(CDUnknownFunctionPointerType)arg2 objectLoader:(CDUnknownFunctionPointerType)arg3 completionHandler:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) _SFTabStateData *_sf_tabStateData;
@property(readonly, nonatomic) NSURL *_sf_localURL;
@property(readonly, nonatomic) WebBookmark *_sf_localBookmark;
- (id)_sf_initWithSiriSuggestion:(id)arg1;
- (id)_sf_initWithBookmark:(id)arg1;
@end

