//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GameController/_GCDeviceManager-Protocol.h>

@class NSNumber, _GCCControllerHIDServiceInfo;
@protocol GCPhysicalDeviceRegistry, _GCDeviceDriverConnection;

@protocol _GCPhysicalDeviceManager <_GCDeviceManager>
@property __weak id <GCPhysicalDeviceRegistry> deviceRegistry;
- (void)relinquishHIDDevice:(_GCCControllerHIDServiceInfo *)arg1;
- (void)claimHIDDevice:(_GCCControllerHIDServiceInfo *)arg1;
- (NSNumber *)matchHIDDevice:(_GCCControllerHIDServiceInfo *)arg1;

@optional
- (id <_GCDeviceDriverConnection>)driverConnectionForHIDDevice:(_GCCControllerHIDServiceInfo *)arg1;
- (_Bool)acceptDriverConnection:(id <_GCDeviceDriverConnection>)arg1 forHIDDevice:(_GCCControllerHIDServiceInfo *)arg2;
@end

