//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WFAction, WFLibraryRunCoordinator, WFWorkflowControllerState, WFWorkflowReference;
@protocol WFUserInterfaceHost;

@protocol WFLibraryRunCoordinatorDelegate <NSObject>
- (id <WFUserInterfaceHost>)runCoordinator:(WFLibraryRunCoordinator *)arg1 userInterfaceForWorkflow:(WFWorkflowReference *)arg2;

@optional
- (void)runCoordinator:(WFLibraryRunCoordinator *)arg1 openWorkflow:(WFWorkflowReference *)arg2 scrolledToActionIndex:(long long)arg3;
- (_Bool)runCoordinator:(WFLibraryRunCoordinator *)arg1 handleUnsupportedEnvironmentForAction:(WFAction *)arg2 currentState:(WFWorkflowControllerState *)arg3 completionHandler:(void (^)(WFContentCollection *, NSError *))arg4;
- (void)runCoordinator:(WFLibraryRunCoordinator *)arg1 handOffWithState:(WFWorkflowControllerState *)arg2 completionHandler:(void (^)(_Bool))arg3;
@end

