//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CarPlay/CPTemplateDelegate-Protocol.h>

@class CPListItem, CPListTemplate;

@protocol CPListClientTemplateDelegate <CPTemplateDelegate>
- (void)listTemplate:(CPListTemplate *)arg1 didSelectListItem:(CPListItem *)arg2 completionHandler:(void (^)(void))arg3;
@end

