//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSArray, NSString, NUIContainerGridView;

__attribute__((visibility("hidden")))
@interface NUIGridDimension : NSObject
{
    NUIContainerGridView *_gridView;
    NSArray *_arrangedSubviews;
    double _length;
    double _spacing;
    struct {
        unsigned int align:8;
        unsigned int isRow:1;
        unsigned int hidden:1;
        unsigned int wasDetached:1;
    } _flags;
}

@property(nonatomic) long long alignment;
@property(nonatomic) double spacingAfter;
@property(nonatomic) double length;
@property(nonatomic, getter=isHidden) _Bool hidden;
@property(copy, nonatomic) NSArray *arrangedSubviews; // @dynamic arrangedSubviews;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

