//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AVFoundation/AVCaptureSynchronizedData.h>

@class AVCameraCalibrationData;

@interface AVCaptureSynchronizedCameraCalibrationData : AVCaptureSynchronizedData
{
    AVCameraCalibrationData *_cameraCalibrationData;
    _Bool _cameraCalibrationDataWasDropped;
    long long _droppedReason;
}

@property(readonly) long long droppedReason;
@property(readonly) _Bool cameraCalibrationDataWasDropped;
@property(readonly) AVCameraCalibrationData *cameraCalibrationData;
- (void)dealloc;
- (id)_initWithCameraCalibrationData:(id)arg1 timestamp:(CDStruct_1b6d18a9)arg2 cameraCalibrationDataWasDropped:(_Bool)arg3 droppedReason:(long long)arg4;

@end

