//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol HAP2Accessory;

@interface HAP2CharacteristicTuple : NSObject
{
    id <HAP2Accessory> _accessory;
    NSMutableArray *_values;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *values; // @synthesize values=_values;
@property(readonly, nonatomic) id <HAP2Accessory> accessory; // @synthesize accessory=_accessory;
- (id)initWithAccessory:(id)arg1;

@end

