//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol LPComponentViewDelegate;

__attribute__((visibility("hidden")))
@interface LPComponentView : UIView
{
    id <LPComponentViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <LPComponentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)shouldAllowHighlightToRecognizeSimultaneouslyWithGesture:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)componentViewDidMoveToWindow;
- (void)layoutComponentView;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (_Bool)isFlipped;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

