//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@interface APSigningServerRequestor : NSObject
{
}

- (void)requestSetupForData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)requestCertificate:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)init;

@end

