//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9SeymourUI22ShelfLazyLockupFetcher : _TtCs12_SwiftObject
{
    MISSING_TYPE *catalogClient;
    MISSING_TYPE *contentRatingCache;
    MISSING_TYPE *mediaTagStringBuilder;
    MISSING_TYPE *batchSize;
    MISSING_TYPE *displayStyle;
    MISSING_TYPE *backgroundDisplayStyle;
    MISSING_TYPE *lazyLockups;
    MISSING_TYPE *fetchedIdentiferToLockupMap;
    MISSING_TYPE *currentlyFetchingPlaceholders;
}

@end

