//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface UserNotificationCenter : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSMutableArray *_userNotifications;
}

+ (id)defaultCenter;
- (void)_showPreparedNotification:(id)arg1;
- (void)_finishUserNotification:(struct __CFUserNotification *)arg1 withResponseFlags:(unsigned long long)arg2;
- (void)updateUserNotification:(id)arg1 withUserNotification:(id)arg2;
- (void)updateUserNotification:(id)arg1 withDictionary:(struct __CFDictionary *)arg2 options:(unsigned long long)arg3;
- (void)updateUserNotification:(id)arg1 withDialog:(id)arg2;
- (id)showUserNotification:(struct __CFDictionary *)arg1 withOptions:(unsigned long long)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)showUserNotification:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)showPreparedNotification:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)showDialog:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)prepareUserNotificationWithDialog:(id)arg1;
- (void)cancelUserNotifications:(id)arg1;
- (void)cancelUserNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

