//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardUIServices/NSObject-Protocol.h>

@class UIControl;

@protocol SBNumberPadDelegate <NSObject>

@optional
- (void)buttonCancelled:(UIControl *)arg1;
- (void)buttonDown:(UIControl *)arg1;
- (void)buttonUp:(UIControl *)arg1;
@end

