//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <SAObjects/SADecoratedString.h>

@interface SADecoratedString (SiriUIFoundationAdditions)
- (id)sruif_attributedStringValueWithAttribute:(id)arg1 value:(id)arg2 forRegionsWithProperty:(id)arg3;
- (void)sruif_enumerateRangesOfRegionsWithProperty:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)sruif_enumeratePropertyRangesUsingBlock:(CDUnknownBlockType)arg1;
@end

