//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Translation/FTTranslationLocalePair.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FTMutableTranslationLocalePair : FTTranslationLocalePair
{
}

@property(copy, nonatomic) NSString *target_locale;
@property(copy, nonatomic) NSString *source_locale;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

