//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <KnowledgeGraphKit/MARelation.h>

@class MANodeFilter;

@interface MANodeFilterRelation : MARelation
{
    MANodeFilter *_nodeFilter;
}

+ (id)scanRelationWithScanner:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) MANodeFilter *nodeFilter; // @synthesize nodeFilter=_nodeFilter;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)visualString;
- (_Bool)unionAdjacencySetFromSourceNodeIdentifiers:(id)arg1 toTargetNodeIdentifiers:(id)arg2 graphStore:(id)arg3 error:(id *)arg4;
- (void)unionAdjacencyListFromSources:(id)arg1 toTargets:(id)arg2;
- (void)unionAdjacencyListFromSource:(id)arg1 toTargets:(id)arg2;
- (id)inverse;
- (id)initWithNodeFilter:(id)arg1;

@end

