//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <NetworkExtension/NEVPNPluginManager-Protocol.h>

@protocol NEFlowDivertPluginManager <NEVPNPluginManager>
- (void)createFlowDivertControlSocketWithCompletionHandler:(void (^)(NSFileHandle *))arg1;
@end

