//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC7NewsUI227AudioPlaybackCommandHandler : NSObject
{
    MISSING_TYPE *dataManager;
    MISSING_TYPE *playbackConductor;
    MISSING_TYPE *audioPlaybackTracker;
    MISSING_TYPE *playbackQueue;
    MISSING_TYPE *resumeSlot;
    MISSING_TYPE *bundleSubscriptionManager;
    MISSING_TYPE *offlineManager;
    MISSING_TYPE *offlineArticleManager;
    MISSING_TYPE *offlineAlertControllerFactory;
    MISSING_TYPE *commandCenter;
    MISSING_TYPE *sceneProvider;
}

- (void).cxx_destruct;
- (id)init;

@end

