//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class WBSCRDTPosition;

__attribute__((visibility("hidden")))
@interface _WBBookmarkSyncDataForPositionDecoding : NSObject
{
    WBSCRDTPosition *_position;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) WBSCRDTPosition *position; // @synthesize position=_position;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

