//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

@class NSString, NSTimer, WBTabGroupManager;

__attribute__((visibility("hidden")))
@interface _WBTabCyclerTabGroupUpdateObserver : NSObject
{
    CDUnknownBlockType _handler;
    WBTabGroupManager *_tabGroupManager;
    NSTimer *_timeoutTimer;
    _Bool _waitForTabGroups;
}

+ (id)observeTabGroupManager:(id)arg1 waitForTabGroups:(_Bool)arg2 handler:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (void)tabGroupManagerDidUpdateTabGroups:(id)arg1;
- (void)_timeout;
- (void)startObserving;
- (id)initWithTabGroupManager:(id)arg1 handler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

