//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV19HealthRecordsDaemon12PBLookupInfoP33_7F26719F6460C689CB3D83DDA4DE2FF013_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_dlid;
    MISSING_TYPE *_key;
    MISSING_TYPE *_vkHr;
    MISSING_TYPE *_lastSyncTime;
    MISSING_TYPE *_deviceID;
    MISSING_TYPE *_deviceName;
    MISSING_TYPE *_timesShared;
    MISSING_TYPE *_expiresAt;
    MISSING_TYPE *_healthInstituteID;
    MISSING_TYPE *_testFlowData;
}

@end

