//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSTextRange;
@protocol NSTextViewportElementProvider, NSTextViewportLayoutDelegate;

@interface NSTextViewportLayoutController : NSObject
{
    struct CGRect _viewportBounds;
    struct CGPoint _viewportOffset;
    NSTextRange *_viewportRange;
    NSArray *_viewportElements;
    NSMutableArray *_viewportLayoutObservers;
    id <NSTextViewportLayoutDelegate> _delegate;
    _Bool _layoutIsValid;
    _Bool _delegateSupportsLocationPositionMapping;
    id <NSTextViewportElementProvider> _elementProvider;
}

- (void).cxx_destruct;
@property(readonly) struct CGRect viewportBounds; // @synthesize viewportBounds=_viewportBounds;
@property(readonly) __weak id <NSTextViewportElementProvider> elementProvider; // @synthesize elementProvider=_elementProvider;
- (void)removeViewportLayoutObserver:(id)arg1;
- (void)addViewportLayoutObserver:(id)arg1;
- (id)textViewportElementForLocation:(id)arg1;
- (id)locationAtPoint:(struct CGPoint)arg1;
- (void)enumerateTextViewportElementsInRect:(struct CGRect)arg1 options:(long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)textViewportElementsInRect:(struct CGRect)arg1;
- (id)textViewportElementAtPoint:(struct CGPoint)arg1;
@property(readonly) NSTextRange *viewportRange;
- (struct CGRect)viewport;
- (void)adjustViewport:(double)arg1 atLocation:(id)arg2 verticalOffsetFromLocation:(double)arg3;
- (void)adjustViewport:(double)arg1;
- (double)relocateViewport:(id)arg1;
- (void)layoutViewport;
@property __weak id <NSTextViewportLayoutDelegate> delegate;
- (void)dealloc;
- (id)initWithElementProvider:(id)arg1;

@end

