//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 12 2019 23:20:19).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UserNotificationsSettings/UNNotificationSystemSettings.h>

@interface UNMutableNotificationSystemSettings : UNNotificationSystemSettings
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) long long spokenNotificationSetting; // @dynamic spokenNotificationSetting;
@property(nonatomic) long long announcementSetting; // @dynamic announcementSetting;
@property(nonatomic) long long showPreviewsSetting; // @dynamic showPreviewsSetting;

@end

