//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import "CADOperationGroup.h"

__attribute__((visibility("hidden")))
@interface CADSyncOperationGroup : CADOperationGroup
{
}

+ (_Bool)requiresEventAccess;
- (void)CADDatabaseGetDeletableSources:(CDUnknownBlockType)arg1;
- (void)CADDatabaseGetDeletableCalendars:(CDUnknownBlockType)arg1;
- (_Bool)accessGranted;

@end

