//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDate, NSDictionary;

@interface WBSPasswordBreachResultQuery : NSObject
{
    NSData *_persistentIdentifier;
    NSDate *_dateLastModified;
}

+ (id)dictionaryRepresentationsForResultQueries:(id)arg1;
+ (id)resultQueriesFromDictionaryRepresentations:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *dateLastModified; // @synthesize dateLastModified=_dateLastModified;
@property(readonly, nonatomic) NSData *persistentIdentifier; // @synthesize persistentIdentifier=_persistentIdentifier;
- (id)description;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithPersistentIdentifier:(id)arg1 dateLastModified:(id)arg2;

@end

