//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AMSMutableBagKeySet, NSDate, NSMutableDictionary, NSString;

@interface AMSMockBagBuilder : NSObject
{
    NSDate *_expirationDate;
    NSString *_profile;
    NSString *_profileVersion;
    AMSMutableBagKeySet *_bagKeySet;
    NSMutableDictionary *_data;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) AMSMutableBagKeySet *bagKeySet; // @synthesize bagKeySet=_bagKeySet;
@property(retain, nonatomic) NSString *profileVersion; // @synthesize profileVersion=_profileVersion;
@property(retain, nonatomic) NSString *profile; // @synthesize profile=_profile;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
- (void)unionBagKeySet:(id)arg1;
- (id)createMockBag;
- (void)addBagKey:(id)arg1 value:(id)arg2 valueType:(unsigned long long)arg3;
- (id)initWithData:(id)arg1;
- (id)init;

@end

