//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface AMSRestrictions : NSObject
{
}

+ (id)_featureNameForMediaType:(unsigned long long)arg1;
+ (id)rankForMediaType:(unsigned long long)arg1;
+ (_Bool)requirePasswordImmediately;
+ (_Bool)onDeviceDiagnosticsAllowed;
+ (long long)maximumMediaRank;
+ (_Bool)isParentalControlEnabled;
+ (_Bool)inAppPurchaseAllowed;
+ (_Bool)explicitContentAllowed;
+ (_Bool)eroticaAllowed;
+ (_Bool)allowActiveAccountModifications;
+ (_Bool)allowAccountModifications;

@end

