//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <PhotosUIPrivate/NSObject-Protocol.h>

@class PUEditPluginHostViewController;

@protocol PUEditPluginHostViewControllerDelegate <NSObject>

@optional
- (void)editPluginHostViewController:(PUEditPluginHostViewController *)arg1 didFinishWithCompletionType:(unsigned long long)arg2;
@end

