//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <UIKit/UIView.h>

@class NSString, UIButton, UILabel;
@protocol PUImportAddToAlbumsToolbarViewDelegate;

__attribute__((visibility("hidden")))
@interface PUImportAddToAlbumsToolbarView : UIView
{
    NSString *_destinationDescriptionTitle;
    UIButton *_destinationButton;
    id <PUImportAddToAlbumsToolbarViewDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_destinationLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *destinationLabel; // @synthesize destinationLabel=_destinationLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <PUImportAddToAlbumsToolbarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *destinationButton; // @synthesize destinationButton=_destinationButton;
@property(retain, nonatomic) NSString *destinationDescriptionTitle; // @synthesize destinationDescriptionTitle=_destinationDescriptionTitle;
- (struct CGRect)accessibilityFrame;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)buttonPressed:(id)arg1;
- (void)buttonTouchDragOutside:(id)arg1;
- (void)buttonTouchDragInside:(id)arg1;
- (void)_animateButtonAlpha:(double)arg1;
- (void)buttonTouchDown:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)_updateButtonText;
- (void)_setupButton;
- (id)_destinationDescription;
- (void)_setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

