//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKitCore/UIStatusBarItemView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface UIStatusBarNotChargingItemView : UIStatusBarItemView
{
    NSString *_notChargingString;
}

- (void).cxx_destruct;
- (id)accessibilityHUDRepresentation;
- (id)contentsImage;
- (_Bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end

