//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MapKit/MKTableViewCell.h>

@class NSLayoutConstraint, TransitDirectionsListItem, UIFont, UILayoutGuide, UIView;

__attribute__((visibility("hidden")))
@interface TransitDirectionsCell : MKTableViewCell
{
    TransitDirectionsListItem *_transitListItem;
    NSLayoutConstraint *_leadingAccessoryLayoutGuideWidthConstraint;
    NSLayoutConstraint *_bottomSpacingLayoutGuideHeightConstraint;
    UILayoutGuide *_trailingContentLayoutGuide;
    NSLayoutConstraint *_trailingContentLayoutGuideWidthConstraint;
    NSLayoutConstraint *_trailingGuideToContentViewConstraint;
    _Bool _useLeadingInstructionMarginAsLeadingSeparatorInset;
    double _leadingInstructionMargin;
    long long _navigationState;
    UILayoutGuide *_leadingAccessoryLayoutGuide;
    UILayoutGuide *_contentLayoutGuide;
    UILayoutGuide *_bottomSpacingLayoutGuide;
    UIView *_trailingView;
}

+ (double)estimatedHeightForListItem:(id)arg1;
+ (id)cellIdentifier;
+ (id)dequeueCellForListItem:(id)arg1 fromTableView:(id)arg2 atIndexPath:(id)arg3;
+ (void)registerCellsForTableView:(id)arg1;
+ (id)cellIdentifierForListItem:(id)arg1;
+ (Class)cellClassForListItem:(id)arg1;
+ (id)cellMapping;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *trailingView; // @synthesize trailingView=_trailingView;
@property(readonly, nonatomic) UILayoutGuide *bottomSpacingLayoutGuide; // @synthesize bottomSpacingLayoutGuide=_bottomSpacingLayoutGuide;
@property(readonly, nonatomic) UILayoutGuide *contentLayoutGuide; // @synthesize contentLayoutGuide=_contentLayoutGuide;
@property(readonly, nonatomic) UILayoutGuide *leadingAccessoryLayoutGuide; // @synthesize leadingAccessoryLayoutGuide=_leadingAccessoryLayoutGuide;
@property(nonatomic) _Bool useLeadingInstructionMarginAsLeadingSeparatorInset; // @synthesize useLeadingInstructionMarginAsLeadingSeparatorInset=_useLeadingInstructionMarginAsLeadingSeparatorInset;
@property(nonatomic) long long navigationState; // @synthesize navigationState=_navigationState;
@property(nonatomic) double leadingInstructionMargin; // @synthesize leadingInstructionMargin=_leadingInstructionMargin;
@property(readonly, nonatomic) TransitDirectionsListItem *transitListItem; // @synthesize transitListItem=_transitListItem;
@property(readonly, nonatomic) UIFont *fontForScalingBottomSpacerHeight;
@property(readonly, nonatomic) double bottomSpacerHeight;
- (void)setAccessoryType:(long long)arg1;
- (void)_contentSizeCategoryDidChange;
- (double)_trailingGuideToContentViewDistance;
- (void)updateConstraints;
- (id)_initialConstraints;
- (void)_updateForParentExpansionOrCollapse;
- (struct CGRect)_separatorFrame;
- (void)_createSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

