//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <PhotosGraph/NSObject-Protocol.h>

@class CLCircularRegion, NSArray, NSDateInterval, NSString;

@protocol PGGraphIngestBusiness <NSObject>
@property(readonly, nonatomic) CLCircularRegion *region;
@property(readonly, nonatomic) _Bool hasRoutineVisit;
@property(readonly, nonatomic) double routineVisitConfidence;
@property(readonly, nonatomic) NSDateInterval *dateInterval;
@property(readonly, nonatomic) long long venueCapacity;
@property(readonly, nonatomic) unsigned long long muid;
@property(readonly, nonatomic) NSArray *businessCategories;
@property(readonly, nonatomic) NSString *name;
@end

