//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BackBoardServices/BKSHIDEventDescriptor.h>

@interface BKSHIDEventBiometricDescriptor : BKSHIDEventDescriptor
{
    unsigned int _biometricEventType;
}

+ (_Bool)supportsSecureCoding;
+ (id)descriptorWithBiometricEventType:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int biometricEventType; // @synthesize biometricEventType=_biometricEventType;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)describes:(id)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithBiometricEventType:(unsigned int)arg1;

@end

