//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDateComponents.h>

@interface NSDateComponents (CloudKitCoding)
+ (id)as_dateComponentsWithCodable:(id)arg1;
- (id)as_codableDateComponents;
@end

