//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8VideosUI11VideosColor : _TtCs12_SwiftObject
{
    MISSING_TYPE *lightUIColor;
    MISSING_TYPE *darkUIColor;
    MISSING_TYPE *_dynamicUIColor;
    MISSING_TYPE *$__lazy_storage_$_color;
}

- (id)copyWithZone:(void *)arg1;

@end

