//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//
//  Build 2022-10-30 xybp888 Dump.
//  

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface OADTableColumn : NSObject
{
    float mWidth;
}

- (id)description;
- (void)setWidth:(float)arg1;
- (float)width;

@end

