//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreDuetContext/_CDContextServer-Protocol.h>

@class NSArray, NSObject, NSPredicate, _CDContextualKeyPath;
@protocol NSCopying><NSSecureCoding;

@protocol _CDLocalContextServer <_CDContextServer>
- (void)removeObjectsMatchingPredicate:(NSPredicate *)arg1 fromArrayAtPath:(_CDContextualKeyPath *)arg2 handler:(void (^)(NSArray *))arg3;
- (void)addObjects:(NSArray *)arg1 andRemoveObjects:(NSArray *)arg2 forArrayAtPath:(_CDContextualKeyPath *)arg3 handler:(void (^)(_Bool))arg4;
- (void)setObject:(NSObject<NSCopying><NSSecureCoding> *)arg1 forPath:(_CDContextualKeyPath *)arg2 handler:(void (^)(_Bool))arg3;
@end

