//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreDuetContext/_CDLocalContextServer-Protocol.h>

@class NSArray, _CDContextualPredicate;

@protocol _CDUserContextServer <_CDLocalContextServer>
- (void)valuesForPaths:(NSArray *)arg1 handler:(void (^)(NSDictionary *))arg2;
- (void)valuesForPaths:(NSArray *)arg1 inContextsMatching:(_CDContextualPredicate *)arg2 handler:(void (^)(NSArray *))arg3;
@end

